name: zephyr_reader
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.12.1
  flutter: '>=3.44.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    # --- Routing ---
  go_router: ^17.0.1

  # --- State Management ---
  signals_flutter: ^7.1.0
  signals_hooks: ^7.1.0
  flutter_hooks: ^0.21.3+1

  # --- Dependency Injection ---
  get_it: ^9.2.0
  injectable: ^3.0.0

  # --- Data & Persistence ---
  shared_preferences: ^2.5.3
  path_provider: ^2.1.3
  path: ^1.9.0

  # --- UI & Assets ---
  flutter_animate: ^4.5.2
  fl_chart: ^1.2.0
  file_picker: ^12.0.0-beta.5
  url_launcher: ^6.3.1

  # --- Utils & Others ---
  logger: ^2.6.2
  freezed_annotation: ^3.1.0
  package_info_plus: ^10.1.0

  rust_lib_zephyr_reader:
    path: rust_builder
  flutter_rust_bridge: 2.12.0
  intl: ^0.20.2

  phosphoricons_flutter: 1.0.0
  flutter_readium: ^0.4.0

dependency_overrides:
  flutter_readium:
    path: third_party/flutter_readium

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # --- Code Generation ---
  build_runner: ^2.4.14
  ffigen: ^21.0.0
  json_serializable: ^6.9.3
  injectable_generator: ^3.0.2
  integration_test:
    sdk: flutter
  freezed: ^3.2.5
  mocktail: ^1.0.4
flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env

  fonts:
    - family: Noto Serif SC
      fonts:
        - asset: assets/fonts/NotoSerifSC-Regular.ttf
          weight: 400
