// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'error.freezed.dart';

@freezed
sealed class ParserError with _$ParserError implements FrbException {
  const ParserError._();

  /// 文件不存在
  const factory ParserError.fileNotFound({
    required String path,
    required String reason,
  }) = ParserError_FileNotFound;

  /// 文件读取失败
  const factory ParserError.fileReadError({
    required String path,
    required String message,
  }) = ParserError_FileReadError;

  /// 编码检测失败
  const factory ParserError.encodingError(String field0) =
      ParserError_EncodingError;

  /// EPUB 解析失败
  const factory ParserError.epubParseError(String field0) =
      ParserError_EpubParseError;

  /// PDF 解析失败
  const factory ParserError.pdfParseError(String field0) =
      ParserError_PdfParseError;

  /// TXT 解析失败
  const factory ParserError.txtParseError(String field0) =
      ParserError_TxtParseError;

  /// 章节提取失败
  const factory ParserError.chapterExtractError(String field0) =
      ParserError_ChapterExtractError;

  /// 排版处理失败
  const factory ParserError.typeset(String field0) = ParserError_Typeset;

  /// 流式加载失败
  const factory ParserError.streamError(String field0) =
      ParserError_StreamError;

  /// 不支持的文件格式
  const factory ParserError.unsupportedFormat(String field0) =
      ParserError_UnsupportedFormat;

  /// 文件写入失败
  const factory ParserError.fileWriteError(String field0) =
      ParserError_FileWriteError;

  /// 内部错误
  const factory ParserError.internalError(String field0) =
      ParserError_InternalError;

  /// 配置错误
  const factory ParserError.configError(String field0) =
      ParserError_ConfigError;

  /// 页面提取失败
  const factory ParserError.pageExtractError(String field0) =
      ParserError_PageExtractError;

  /// 文本提取失败
  const factory ParserError.textExtractError(String field0) =
      ParserError_TextExtractError;

  /// 其他错误（通用错误消息）
  const factory ParserError.other(String field0) = ParserError_Other;

  /// 安全错误（路径遍历攻击等）
  const factory ParserError.securityError(String field0) =
      ParserError_SecurityError;
}
