// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'error.freezed.dart';

@freezed
sealed class ParserError with _$ParserError {
  const ParserError._();

  /// 文件不存在  const factory ParserError.fileNotFound({required String path}) = ParserError_FileNotFound;

  /// 文件读取失败
  const factory ParserError.fileReadError({
    required String path,
    required String message,
  }) = ParserError_FileReadError;

  /// 编码检测失  const factory ParserError.encodingError(String field0) =
      ParserError_EncodingError;

  /// EPUB 解析失败
  const factory ParserError.epubParseError(String field0) =
      ParserError_EpubParseError;

  /// TXT 解析失败
  const factory ParserError.txtParseError(String field0) =
      ParserError_TxtParseError;

  /// 章节提取失败
  const factory ParserError.chapterExtractError(String field0) =
      ParserError_ChapterExtractError;

  /// 排版处理失败
  const factory ParserError.typeset(String field0) = ParserError_Typeset;

  /// 流式加载失败
  const factory ParserError.streamError(String field0) =
      ParserError_StreamError;

  /// 不支持的文件格式
  const factory ParserError.unsupportedFormat(String field0) =
      ParserError_UnsupportedFormat;

  /// 内部错误
  const factory ParserError.internalError(String field0) =
      ParserError_InternalError;

  /// 其他错误（通用错误消息）
  const factory ParserError.other(String field0) = ParserError_Other;
}
