// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 书签信息
class Bookmark {
  /// 书签唯一标识
  final String bookmarkId;

  /// 书籍 ID
  final String bookId;

  /// 章节 ID
  final int chapterId;

  /// 页码
  final int pageIndex;

  /// 书签标题（用户自定义或自动生成）
  final String title;

  /// 创建时间戳（Unix 时间戳）
  final PlatformInt64 createdTimestamp;

  /// 备注
  final String? note;

  const Bookmark({
    required this.bookmarkId,
    required this.bookId,
    required this.chapterId,
    required this.pageIndex,
    required this.title,
    required this.createdTimestamp,
    this.note,
  });

  @override
  int get hashCode =>
      bookmarkId.hashCode ^
      bookId.hashCode ^
      chapterId.hashCode ^
      pageIndex.hashCode ^
      title.hashCode ^
      createdTimestamp.hashCode ^
      note.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Bookmark &&
          runtimeType == other.runtimeType &&
          bookmarkId == other.bookmarkId &&
          bookId == other.bookId &&
          chapterId == other.chapterId &&
          pageIndex == other.pageIndex &&
          title == other.title &&
          createdTimestamp == other.createdTimestamp &&
          note == other.note;
}

/// 文本语言类型
enum LanguageType {
  /// 中文
  chinese,

  /// 英文
  english,

  /// 混合
  mixed,

  /// 自动检测
  auto,
}

/// 分页内容结构体
class PageContent {
  /// 章节 ID
  final int chapterId;

  /// 页码
  final int pageIndex;

  /// 页面内容
  final String content;

  /// 是否为最后一页
  final bool isLastPage;

  const PageContent({
    required this.chapterId,
    required this.pageIndex,
    required this.content,
    required this.isLastPage,
  });

  @override
  int get hashCode =>
      chapterId.hashCode ^
      pageIndex.hashCode ^
      content.hashCode ^
      isLastPage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PageContent &&
          runtimeType == other.runtimeType &&
          chapterId == other.chapterId &&
          pageIndex == other.pageIndex &&
          content == other.content &&
          isLastPage == other.isLastPage;
}

/// 阅读进度信息
class ReadingProgress {
  /// 当前章节 ID
  final int chapterId;

  /// 当前页码
  final int pageIndex;

  /// 总页数
  final int totalPages;

  /// 进度百分比（0.0 - 1.0）
  final double progress;

  /// 已阅读时间（秒）
  final PlatformInt64 readingTimeSeconds;

  /// 最后阅读时间戳（Unix 时间戳）
  final PlatformInt64 lastReadTimestamp;

  const ReadingProgress({
    required this.chapterId,
    required this.pageIndex,
    required this.totalPages,
    required this.progress,
    required this.readingTimeSeconds,
    required this.lastReadTimestamp,
  });

  @override
  int get hashCode =>
      chapterId.hashCode ^
      pageIndex.hashCode ^
      totalPages.hashCode ^
      progress.hashCode ^
      readingTimeSeconds.hashCode ^
      lastReadTimestamp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReadingProgress &&
          runtimeType == other.runtimeType &&
          chapterId == other.chapterId &&
          pageIndex == other.pageIndex &&
          totalPages == other.totalPages &&
          progress == other.progress &&
          readingTimeSeconds == other.readingTimeSeconds &&
          lastReadTimestamp == other.lastReadTimestamp;
}

/// 排版配置
class TypesetConfig {
  /// 页面宽度（像素）
  final int pageWidth;

  /// 页面高度（像素）
  final int pageHeight;

  /// 字体大小（像素）
  final int fontSize;

  /// 行间距
  final double lineSpacing;

  /// 字间距
  final double letterSpacing;

  /// 段落间距
  final double paragraphSpacing;

  /// 首行缩进字符数
  final int firstLineIndent;

  /// 语言类型
  final LanguageType language;

  const TypesetConfig({
    required this.pageWidth,
    required this.pageHeight,
    required this.fontSize,
    required this.lineSpacing,
    required this.letterSpacing,
    required this.paragraphSpacing,
    required this.firstLineIndent,
    required this.language,
  });

  @override
  int get hashCode =>
      pageWidth.hashCode ^
      pageHeight.hashCode ^
      fontSize.hashCode ^
      lineSpacing.hashCode ^
      letterSpacing.hashCode ^
      paragraphSpacing.hashCode ^
      firstLineIndent.hashCode ^
      language.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TypesetConfig &&
          runtimeType == other.runtimeType &&
          pageWidth == other.pageWidth &&
          pageHeight == other.pageHeight &&
          fontSize == other.fontSize &&
          lineSpacing == other.lineSpacing &&
          letterSpacing == other.letterSpacing &&
          paragraphSpacing == other.paragraphSpacing &&
          firstLineIndent == other.firstLineIndent &&
          language == other.language;
}
