// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'types.freezed.dart';

/// 文本语言类型
enum LanguageType {
  /// 中文
  chinese,

  /// 英文
  english,

  /// 混合
  mixed,

  /// 自动检测
  auto,
}

/// 分页内容结构体
class PageContent {
  /// 章节索引（顺序号，从 0 开始）
  final int chapterIndex;

  /// 页码
  final int pageIndex;

  /// 页面内容
  final String content;

  /// 是否为最后一页
  final bool isLastPage;

  const PageContent({
    required this.chapterIndex,
    required this.pageIndex,
    required this.content,
    required this.isLastPage,
  });

  @override
  int get hashCode =>
      chapterIndex.hashCode ^
      pageIndex.hashCode ^
      content.hashCode ^
      isLastPage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PageContent &&
          runtimeType == other.runtimeType &&
          chapterIndex == other.chapterIndex &&
          pageIndex == other.pageIndex &&
          content == other.content &&
          isLastPage == other.isLastPage;
}

/// 富文本段落
///
/// 由多个富文本片段组成的段落，支持首行缩进和标题标题等。
class RichParagraph {
  /// 文本片段列表
  final List<RichTextSpan> spans;

  /// 首行缩进字符数
  final int indent;

  /// 是否为标题
  final bool isHeading;

  /// 标题层级（1-6），表示非标题时为 0
  final int headingLevel;

  /// 段落样式类名（来自 HTML class 属性）
  final String? className;

  const RichParagraph({
    required this.spans,
    required this.indent,
    required this.isHeading,
    required this.headingLevel,
    this.className,
  });

  @override
  int get hashCode =>
      spans.hashCode ^
      indent.hashCode ^
      isHeading.hashCode ^
      headingLevel.hashCode ^
      className.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RichParagraph &&
          runtimeType == other.runtimeType &&
          spans == other.spans &&
          indent == other.indent &&
          isHeading == other.isHeading &&
          headingLevel == other.headingLevel &&
          className == other.className;
}

@freezed
sealed class RichTextSpan with _$RichTextSpan {
  const RichTextSpan._();

  /// 纯文本
  const factory RichTextSpan.plain({required String text}) = RichTextSpan_Plain;

  /// 加粗
  const factory RichTextSpan.bold({required String text}) = RichTextSpan_Bold;

  /// 倾斜
  const factory RichTextSpan.italic({required String text}) =
      RichTextSpan_Italic;

  /// 加粗 + 倾斜
  const factory RichTextSpan.boldItalic({required String text}) =
      RichTextSpan_BoldItalic;

  /// 下划线
  const factory RichTextSpan.underline({required String text}) =
      RichTextSpan_Underline;

  /// 删除线
  const factory RichTextSpan.strikethrough({required String text}) =
      RichTextSpan_Strikethrough;

  /// 行内代码
  const factory RichTextSpan.code({required String text}) = RichTextSpan_Code;

  /// 超链接
  const factory RichTextSpan.link({required String text, required String url}) =
      RichTextSpan_Link;
}

/// 排版配置
class TypesetConfig {
  /// 页面宽度（像素）
  final int pageWidth;

  /// 页面高度（像素）
  final int pageHeight;

  /// 字体大小（像素）
  final int fontSize;

  /// 行间距
  final double lineSpacing;

  /// 字间距
  final double letterSpacing;

  /// 段落间距
  final double paragraphSpacing;

  /// 首行缩进字符数
  final int firstLineIndent;

  /// 语言类型
  final LanguageType language;

  /// 是否启用英文连字
  final bool enableHyphenation;

  /// 连字语言（如 "en-us", "en-gb"）
  final String? hyphenationLanguage;

  const TypesetConfig({
    required this.pageWidth,
    required this.pageHeight,
    required this.fontSize,
    required this.lineSpacing,
    required this.letterSpacing,
    required this.paragraphSpacing,
    required this.firstLineIndent,
    required this.language,
    required this.enableHyphenation,
    this.hyphenationLanguage,
  });

  @override
  int get hashCode =>
      pageWidth.hashCode ^
      pageHeight.hashCode ^
      fontSize.hashCode ^
      lineSpacing.hashCode ^
      letterSpacing.hashCode ^
      paragraphSpacing.hashCode ^
      firstLineIndent.hashCode ^
      language.hashCode ^
      enableHyphenation.hashCode ^
      hyphenationLanguage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TypesetConfig &&
          runtimeType == other.runtimeType &&
          pageWidth == other.pageWidth &&
          pageHeight == other.pageHeight &&
          fontSize == other.fontSize &&
          lineSpacing == other.lineSpacing &&
          letterSpacing == other.letterSpacing &&
          paragraphSpacing == other.paragraphSpacing &&
          firstLineIndent == other.firstLineIndent &&
          language == other.language &&
          enableHyphenation == other.enableHyphenation &&
          hyphenationLanguage == other.hyphenationLanguage;
}
