// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'ffi/types.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'parser/incremental.dart';
import 'stream/page_stream.dart';

// These functions are ignored because they are not marked as `pub`: `extract_epub_cover`, `get_incremental_parser`, `get_storage`, `is_safe_path`, `parse_jpeg_size`, `try_parse_image_size`, `validate_file_path`

/// 初始化存储
///
/// 在应用启动时调用，设置 SQLite 数据库路径。
/// 如果未调用此函数，进度和书签将使用临时内存存储（不推荐）。
///
/// # 参数
///
/// * `db_path` - SQLite 数据库文件路径（建议放在应用文档目录）
///
/// # 示例
///
/// Flutter 侧：
/// ```dart
/// final directory = await getApplicationDocumentsDirectory();
/// await initStorage('${directory.path}/zephyr_reader.db');
/// ```
ApiResult initStorage({required String dbPath}) =>
    RustLib.instance.api.crateApiInitStorage(dbPath: dbPath);

/// 测试连接
///
/// 用于验证 Rust 引擎是否正常工作。
///
/// # 返回值
///
/// 返回固定字符串 "Zephyr Reader Rust Engine OK"
String testConnection() => RustLib.instance.api.crateApiTestConnection();

/// 异步解析 TXT 文件
///
/// 异步版本适用于大文件解析，不阻塞主线程。
/// 在后台线程池中执行 CPU 密集型的解析操作。
///
/// # 参数
///
/// * `file_path` - TXT 文件的完整路径
///
/// # 返回值
///
/// * `Ok(ParseResult)` - 解析成功，包含书籍信息和章节列表
/// * `Err(ParserError)` - 解析失败
Future<ApiResultParseResult> asyncParseTxtFile({required String filePath}) =>
    RustLib.instance.api.crateApiAsyncParseTxtFile(filePath: filePath);

/// 异步解析 EPUB 文件
///
/// 异步版本适用于大文件解析，不阻塞主线程。
/// 在后台线程池中执行 CPU 密集型的解析操作。
///
/// # 参数
///
/// * `file_path` - EPUB 文件的完整路径
///
/// # 返回值
///
/// * `Ok(ParseResult)` - 解析成功，包含书籍信息和章节列表
/// * `Err(ParserError)` - 解析失败
Future<ApiResultParseResult> asyncParseEpubFile({required String filePath}) =>
    RustLib.instance.api.crateApiAsyncParseEpubFile(filePath: filePath);

/// 异步解析 PDF 文件
///
/// 异步版本适用于大文件解析，不阻塞主线程。
/// 在后台线程池中执行 CPU 密集型的解析操作。
///
/// # 参数
///
/// * `file_path` - PDF 文件的完整路径
///
/// # 返回值
///
/// * `Ok(ParseResult)` - 解析成功，包含书籍信息和章节列表
/// * `Err(ParserError)` - 解析失败
Future<ApiResultParseResult> asyncParsePdfFile({required String filePath}) =>
    RustLib.instance.api.crateApiAsyncParsePdfFile(filePath: filePath);

/// 异步解析本地书籍文件
///
/// 自动检测文件类型（TXT、EPUB 或 PDF）并调用相应的异步解析器。
/// 适用于大文件解析，不阻塞主线程。
///
/// # 参数
///
/// * `file_path` - 本地书籍文件的完整路径
///
/// # 返回值
///
/// * `Ok(LocalBookInfo)` - 解析成功，包含书籍信息和章节列表
/// * `Err(ParserError)` - 解析失败
Future<ApiResultLocalBookInfo> asyncParseLocalBook({
  required String filePath,
}) => RustLib.instance.api.crateApiAsyncParseLocalBook(filePath: filePath);

/// 解析 TXT 文件
///
/// 读取并解析 TXT 文件，提取章节信息和书籍元数据。
/// 支持多种中文编码自动检测（UTF-8、GBK、GB2312、Big5）。
///
/// # 参数
///
/// * `file_path` - TXT 文件的完整路径
///
/// # 返回值
///
/// * `Ok(ParseResult)` - 解析成功，包含书籍信息和章节列表
/// * `Err(ParserError)` - 解析失败，可能的错误：
///   - `FileNotFound` - 文件不存在
///   - `FileReadError` - 文件读取失败
///   - `EncodingError` - 编码检测失败
///   - `TxtParseError` - TXT 解析失败
ApiResultParseResult parseTxtFile({required String filePath}) =>
    RustLib.instance.api.crateApiParseTxtFile(filePath: filePath);

/// 解析 EPUB 文件
///
/// 读取并解析 EPUB 文件，提取章节信息、书籍元数据和封面路径。
/// EPUB 规范要求 UTF-8 编码，本函数自动处理。
///
/// # 参数
///
/// * `file_path` - EPUB 文件的完整路径
///
/// # 返回值
///
/// * `Ok(ParseResult)` - 解析成功，包含书籍信息和章节列表
/// * `Err(ParserError)` - 解析失败，可能的错误：
///   - `FileNotFound` - 文件不存在
///   - `FileReadError` - 文件读取失败
///   - `EncodingError` - 编码检测失败
///   - `EpubParseError` - EPUB 解析失败
ApiResultParseResult parseEpubFile({required String filePath}) =>
    RustLib.instance.api.crateApiParseEpubFile(filePath: filePath);

/// 排版处理文本
///
/// 对文本进行智能排版处理，包括：
/// - 首行缩进
/// - 标点符号避首避尾
/// - 中英文混排优化
/// - 智能断行
///
/// # 参数
///
/// * `content` - 待排版的原始文本
/// * `language` - 语言类型（"auto"、"zh"、"en"、"mix"）
/// * `config` - 排版配置（字体大小、行间距等）
///
/// # 返回值
///
/// * `Ok(String)` - 排版后的文本
/// * `Err(ParserError)` - 处理失败
ApiResultString typesetText({
  required String content,
  required String language,
  required TypesetConfig config,
}) => RustLib.instance.api.crateApiTypesetText(
  content: content,
  language: language,
  config: config,
);

/// 获取文件大小
///
/// 获取指定文件的大小（字节数）。
///
/// # 参数
///
/// * `file_path` - 文件的完整路径
///
/// # 返回值
///
/// * `Ok(i64)` - 文件大小（字节）
/// * `Err(ParserError)` - 获取失败
ApiResultI64 getFileSize({required String filePath}) =>
    RustLib.instance.api.crateApiGetFileSize(filePath: filePath);

/// 读取文件块
///
/// 从指定位置读取文件的一块内容，适用于大文件流式读取。
///
/// # 参数
///
/// * `file_path` - 文件的完整路径
/// * `start_pos` - 起始位置（字节偏移）
/// * `chunk_size` - 读取的字节数
///
/// # 返回值
///
/// * `Ok(String)` - 读取的内容（UTF-8 解码）
/// * `Err(ParserError)` - 读取失败
ApiResultString readFileChunk({
  required String filePath,
  required PlatformInt64 startPos,
  required PlatformInt64 chunkSize,
}) => RustLib.instance.api.crateApiReadFileChunk(
  filePath: filePath,
  startPos: startPos,
  chunkSize: chunkSize,
);

/// 创建分页器
///
/// 基于像素宽度精确计算，创建文本分页器。
/// 支持中英文混合排版，自动处理字符宽度差异。
///
/// # 参数
///
/// * `content` - 待分页的文本内容
/// * `config` - 排版配置（页面尺寸、字体大小等）
///
/// # 返回值
///
/// 返回 `PageStreamer` 分页器实例，可用于：
/// - 获取当前页
/// - 翻页（上一页/下一页）
/// - 跳转到指定页
/// - 获取进度
PageStreamer createPageStreamer({
  required String content,
  required TypesetConfig config,
}) => RustLib.instance.api.crateApiCreatePageStreamer(
  content: content,
  config: config,
);

/// 将所有内容分页
///
/// 一次性将全部内容分页，返回所有页面。
/// 适用于内容较少或需要预加载的场景。
///
/// # 参数
///
/// * `content` - 待分页的文本内容
/// * `chapter_id` - 章节 ID
/// * `config` - 排版配置
///
/// # 返回值
///
/// 返回 `Vec<PageContent>`，包含所有页面的内容。
List<PageContent> paginateAllContent({
  required String content,
  required int chapterId,
  required TypesetConfig config,
}) => RustLib.instance.api.crateApiPaginateAllContent(
  content: content,
  chapterId: chapterId,
  config: config,
);

/// 创建或更新阅读进度（支持阅读时间统计）
///
/// 记录用户的阅读进度，包括当前章节、页码和进度百分比。
/// 自动记录最后阅读时间戳。数据会持久化到 SQLite 数据库。
///
/// # 参数
///
/// * `book_id` - 书籍唯一标识
/// * `chapter_id` - 当前章节 ID
/// * `page_index` - 当前页码
/// * `total_pages` - 总页数
/// * `session_duration` - 本次阅读时长（秒），用于累加总阅读时间
///
/// # 返回值
///
/// 返回更新后的 `ReadingProgress` 进度信息
ReadingProgress updateReadingProgressWithDuration({
  required String bookId,
  required int chapterId,
  required int pageIndex,
  required int totalPages,
  required PlatformInt64 sessionDuration,
}) => RustLib.instance.api.crateApiUpdateReadingProgressWithDuration(
  bookId: bookId,
  chapterId: chapterId,
  pageIndex: pageIndex,
  totalPages: totalPages,
  sessionDuration: sessionDuration,
);

/// 创建或更新阅读进度（简化版，不记录阅读时间）
///
/// 记录用户的阅读进度，包括当前章节、页码和进度百分比。
/// 注意：此函数不更新阅读时间统计，如需记录阅读时间请使用 `update_reading_progress_with_duration`。
///
/// # 参数
///
/// * `book_id` - 书籍唯一标识
/// * `chapter_id` - 当前章节 ID
/// * `page_index` - 当前页码
/// * `total_pages` - 总页数
///
/// # 返回值
///
/// 返回更新后的 `ReadingProgress` 进度信息
ReadingProgress updateReadingProgress({
  required String bookId,
  required int chapterId,
  required int pageIndex,
  required int totalPages,
}) => RustLib.instance.api.crateApiUpdateReadingProgress(
  bookId: bookId,
  chapterId: chapterId,
  pageIndex: pageIndex,
  totalPages: totalPages,
);

/// 获取阅读进度
///
/// 获取指定书籍的阅读进度。
///
/// # 参数
///
/// * `book_id` - 书籍唯一标识
///
/// # 返回值
///
/// 返回 `ReadingProgress` 进度信息，如果没有找到则返回默认进度
ReadingProgress getReadingProgress({required String bookId}) =>
    RustLib.instance.api.crateApiGetReadingProgress(bookId: bookId);

/// 清除阅读进度
///
/// 删除指定书籍的阅读进度记录。
///
/// # 参数
///
/// * `book_id` - 书籍唯一标识
///
/// # 返回值
///
/// * `true` - 成功清除进度
/// * `false` - 该书籍没有进度记录或存储未初始化
bool clearReadingProgress({required String bookId}) =>
    RustLib.instance.api.crateApiClearReadingProgress(bookId: bookId);

/// 获取所有书籍的阅读进度
///
/// # 返回值
///
/// 返回所有书籍的进度列表，按最后阅读时间降序排列
List<ReadingProgress> getAllReadingProgress() =>
    RustLib.instance.api.crateApiGetAllReadingProgress();

/// 添加书签
///
/// 在指定位置添加书签，可选备注。数据会持久化到 SQLite 数据库。
///
/// # 参数
///
/// * `book_id` - 书籍唯一标识
/// * `chapter_id` - 章节 ID
/// * `page_index` - 页码
/// * `title` - 书签标题
/// * `note` - 备注（可选）
///
/// # 返回值
///
/// 返回创建的 `Bookmark` 书签信息，包含自动生成的 UUID 和时间戳
Bookmark addBookmark({
  required String bookId,
  required int chapterId,
  required int pageIndex,
  required String title,
  String? note,
}) => RustLib.instance.api.crateApiAddBookmark(
  bookId: bookId,
  chapterId: chapterId,
  pageIndex: pageIndex,
  title: title,
  note: note,
);

/// 获取书籍的所有书签
///
/// # 参数
///
/// * `book_id` - 书籍唯一标识
///
/// # 返回值
///
/// 返回该书的所有书签列表，如果没有书签则返回空列表
///
/// # 错误
///
/// 如果存储未初始化，返回错误
List<Bookmark> getBookmarks({required String bookId}) =>
    RustLib.instance.api.crateApiGetBookmarks(bookId: bookId);

/// 删除书签
///
/// # 参数
///
/// * `book_id` - 书籍唯一标识
/// * `bookmark_id` - 书签唯一标识
///
/// # 返回值
///
/// * `true` - 成功删除
/// * `false` - 书签不存在或存储未初始化
bool removeBookmark({required String bookId, required String bookmarkId}) =>
    RustLib.instance.api.crateApiRemoveBookmark(
      bookId: bookId,
      bookmarkId: bookmarkId,
    );

/// 清除书籍的所有书签
///
/// # 参数
///
/// * `book_id` - 书籍唯一标识
///
/// # 返回值
///
/// 返回删除的书签数量
int clearBookmarks({required String bookId}) =>
    RustLib.instance.api.crateApiClearBookmarks(bookId: bookId);

/// 解析本地书籍文件
///
/// 自动检测文件类型（TXT、EPUB 或 PDF）并调用相应的解析器。
/// 返回完整的书籍信息，包括章节列表。
///
/// # 参数
///
/// * `file_path` - 本地书籍文件的完整路径
///
/// # 返回值
///
/// * `Ok(LocalBookInfo)` - 解析成功，包含书籍信息和章节列表
/// * `Err(ParserError)` - 解析失败
ApiResultLocalBookInfo parseLocalBook({required String filePath}) =>
    RustLib.instance.api.crateApiParseLocalBook(filePath: filePath);

/// 获取书籍封面图片
///
/// 从 EPUB 或 PDF 文件中提取封面图片并保存到指定目录。
///
/// # 参数
///
/// * `file_path` - 文件路径（EPUB 或 PDF）
/// * `output_dir` - 输出目录
///
/// # 返回值
///
/// * `Ok(String)` - 封面图片保存路径
/// * `Err(ParserError)` - 提取失败
ApiResultString extractBookCover({
  required String filePath,
  required String outputDir,
}) => RustLib.instance.api.crateApiExtractBookCover(
  filePath: filePath,
  outputDir: outputDir,
);

/// 获取 EPUB 封面图片数据（零拷贝优化）
///
/// 从 EPUB 文件中提取封面图片的原始字节数据，使用 ZeroCopyBuffer 避免 FFI 拷贝。
/// 适用于需要直接在内存中处理封面数据的场景。
///
/// # 参数
///
/// * `file_path` - EPUB 文件路径
///
/// # 返回值
///
/// * `Ok(ZeroCopyBuffer<Vec<u8>>)` - 封面图片的原始字节数据
/// * `Err(ParserError)` - 提取失败
///
/// # 性能优势
///
/// 使用 `ZeroCopyBuffer` 可以直接传递内存缓冲区，避免在 Rust 和 Dart 之间进行数据拷贝。
/// 对于大尺寸封面图片（如高清封面），性能提升显著。
ApiResultZeroCopyBufferVecU8 getEpubCoverData({required String filePath}) =>
    RustLib.instance.api.crateApiGetEpubCoverData(filePath: filePath);

/// 获取 PDF 封面图片数据（零拷贝优化）
///
/// 从 PDF 文件中提取封面图片的原始字节数据，使用 ZeroCopyBuffer 避免 FFI 拷贝。
/// 适用于需要直接在内存中处理封面数据的场景。
///
/// # 参数
///
/// * `file_path` - PDF 文件路径
///
/// # 返回值
///
/// * `Ok(ZeroCopyBuffer<Vec<u8>>)` - 封面图片的原始字节数据
/// * `Err(ParserError)` - 提取失败或 PDF 无封面
ApiResultZeroCopyBufferVecU8 getPdfCoverData({required String filePath}) =>
    RustLib.instance.api.crateApiGetPdfCoverData(filePath: filePath);

///
/// # 返回值
///
/// 返回所有书籍的所有书签列表，按创建时间降序排列
List<Bookmark> getAllBookmarks() =>
    RustLib.instance.api.crateApiGetAllBookmarks();

/// 记录阅读会话
///
/// 记录一次阅读会话的数据，包括阅读时长和阅读字数。
/// 会自动更新累计统计数据和每日阅读记录。
///
/// # 参数
///
/// * `book_id` - 书籍 ID
/// * `chapter_id` - 章节 ID
/// * `duration_seconds` - 阅读时长（秒）
/// * `characters_read` - 阅读字数
///
/// # 示例
///
/// ```dart
/// // 记录一次 5 分钟的阅读，阅读了 1000 字
/// await recordReadingSession(bookId, chapterId, 300, 1000);
/// ```
void recordReadingSession({
  required String bookId,
  required int chapterId,
  required PlatformInt64 durationSeconds,
  required PlatformInt64 charactersRead,
}) => RustLib.instance.api.crateApiRecordReadingSession(
  bookId: bookId,
  chapterId: chapterId,
  durationSeconds: durationSeconds,
  charactersRead: charactersRead,
);

/// 获取阅读统计
///
/// 获取用户的阅读统计数据，包括总阅读时长、总字数、连续阅读天数等。
///
/// # 返回值
///
/// 返回 `ReadingStats` 统计信息
ReadingStats getReadingStats() =>
    RustLib.instance.api.crateApiGetReadingStats();

/// 获取今日阅读数据
///
/// 获取今日的阅读统计（阅读时长和字数）。
///
/// # 返回值
///
/// 返回 `(reading_time_seconds, characters_read)` 元组
(PlatformInt64, PlatformInt64) getTodayReadingData() =>
    RustLib.instance.api.crateApiGetTodayReadingData();

/// 获取指定日期的阅读记录
///
/// # 参数
///
/// * `date` - 日期（YYYY-MM-DD 格式）
///
/// # 返回值
///
/// 返回 `DailyReadingRecord`，如果没有记录返回默认结构
DailyReadingRecord getDailyReadingRecord({required String date}) =>
    RustLib.instance.api.crateApiGetDailyReadingRecord(date: date);

/// 获取日期范围内的阅读记录
///
/// # 参数
///
/// * `start_date` - 开始日期（YYYY-MM-DD 格式）
/// * `end_date` - 结束日期（YYYY-MM-DD 格式）
///
/// # 返回值
///
/// 返回 `DailyReadingRecord` 列表
List<DailyReadingRecord> getDailyReadingRecordsInRange({
  required String startDate,
  required String endDate,
}) => RustLib.instance.api.crateApiGetDailyReadingRecordsInRange(
  startDate: startDate,
  endDate: endDate,
);

/// 获取最近 N 天的阅读记录
///
/// # 参数
///
/// * `days` - 天数
///
/// # 返回值
///
/// 返回 `DailyReadingRecord` 列表，按日期升序排列
List<DailyReadingRecord> getRecentReadingRecords({required int days}) =>
    RustLib.instance.api.crateApiGetRecentReadingRecords(days: days);

/// 获取连续阅读天数
///
/// # 返回值
///
/// 返回连续阅读天数
int getConsecutiveReadingDays() =>
    RustLib.instance.api.crateApiGetConsecutiveReadingDays();

/// 获取阅读速度（字/分钟）
///
/// 基于历史阅读数据计算平均阅读速度。
///
/// # 返回值
///
/// 返回平均阅读速度（字/分钟）
double getReadingSpeed() => RustLib.instance.api.crateApiGetReadingSpeed();

/// 更新书籍阅读计数
///
/// 当开始阅读一本新书时调用。
void incrementBooksReadCount() =>
    RustLib.instance.api.crateApiIncrementBooksReadCount();

/// 更新完成阅读书籍计数
///
/// 当完成阅读一本书时调用。
void incrementBooksCompletedCount() =>
    RustLib.instance.api.crateApiIncrementBooksCompletedCount();

/// 计算排版配置的哈希值
///
/// 用于缓存键的生成，相同的配置会产生相同的哈希值。
///
/// # 参数
///
/// * `config` - 排版配置
///
/// # 返回值
///
/// 返回配置哈希值（16 进制字符串）
String computeConfigHash({required TypesetConfig config}) =>
    RustLib.instance.api.crateApiComputeConfigHash(config: config);

/// 保存排版缓存
///
/// 将分页后的偏移量缓存到 SQLite 数据库，实现章节"秒开"。
/// 数据会持久化，应用重启后仍然有效。
///
/// # 参数
///
/// * `book_id` - 书籍 ID
/// * `chapter_id` - 章节 ID
/// * `config` - 排版配置（会自动计算哈希）
/// * `page_offsets` - 页面偏移量列表
///
/// # 返回值
///
/// * `Ok(())` - 保存成功
/// * `Err(ParserError)` - 保存失败
ApiResult saveLayoutCache({
  required String bookId,
  required int chapterId,
  required TypesetConfig config,
  required List<PageOffset> pageOffsets,
}) => RustLib.instance.api.crateApiSaveLayoutCache(
  bookId: bookId,
  chapterId: chapterId,
  config: config,
  pageOffsets: pageOffsets,
);

/// 获取排版缓存
///
/// 从 SQLite 数据库获取缓存的分页偏移量。
///
/// # 参数
///
/// * `book_id` - 书籍 ID
/// * `chapter_id` - 章节 ID
/// * `config` - 排版配置（会自动计算哈希）
///
/// # 返回值
///
/// 返回 `LayoutCacheResult`，包含：
/// - `hit: true` 表示命中缓存，`cached_layout` 包含缓存数据
/// - `hit: false` 表示未命中缓存，需要重新分页
LayoutCacheResult getLayoutCache({
  required String bookId,
  required int chapterId,
  required TypesetConfig config,
}) => RustLib.instance.api.crateApiGetLayoutCache(
  bookId: bookId,
  chapterId: chapterId,
  config: config,
);

/// 清除书籍的所有排版缓存
///
/// 当用户更改排版设置或删除书籍时调用。
///
/// # 参数
///
/// * `book_id` - 书籍 ID
///
/// # 返回值
///
/// 返回删除的缓存数量
int clearLayoutCache({required String bookId}) =>
    RustLib.instance.api.crateApiClearLayoutCache(bookId: bookId);

/// 清除指定章节的排版缓存
///
/// 当章节内容发生变化时调用。
///
/// # 参数
///
/// * `book_id` - 书籍 ID
/// * `chapter_id` - 章节 ID
///
/// # 返回值
///
/// 返回删除的缓存数量
int clearChapterLayoutCache({required String bookId, required int chapterId}) =>
    RustLib.instance.api.crateApiClearChapterLayoutCache(
      bookId: bookId,
      chapterId: chapterId,
    );

/// 获取书籍的所有排版缓存信息
///
/// 用于调试和统计目的。
///
/// # 参数
///
/// * `book_id` - 书籍 ID
///
/// # 返回值
///
/// 返回所有缓存的列表，包含章节 ID、配置哈希、页数等信息
List<CachedLayout> getAllLayoutCache({required String bookId}) =>
    RustLib.instance.api.crateApiGetAllLayoutCache(bookId: bookId);

/// 获取 EPUB 封面图片（原始字节）
///
/// 提取 EPUB 文件的封面图片数据，可用于 Flutter 侧显示。
///
/// # 参数
///
/// * `file_path` - EPUB 文件的完整路径
///
/// # 返回值
///
/// * `Ok(Vec<u8>)` - 封面图片的原始字节（JPEG 或 PNG 格式）
/// * `Err(String)` - 获取失败，返回错误消息
Uint8List getEpubCoverImage({required String filePath}) =>
    RustLib.instance.api.crateApiGetEpubCoverImage(filePath: filePath);

/// 获取 EPUB 完整元数据
///
/// 提取 EPUB 文件的全部元数据，包括标题、作者、封面、目录和阅读顺序。
///
/// # 参数
///
/// * `file_path` - EPUB 文件的完整路径
///
/// # 返回值
///
/// * `Ok(EpubMetadata)` - 完整的元数据信息
/// * `Err(ParserError)` - 获取失败
ApiResultEpubMetadata getEpubFullMetadata({required String filePath}) =>
    RustLib.instance.api.crateApiGetEpubFullMetadata(filePath: filePath);

/// 获取 EPUB 中所有图片资源的列表
///
/// 列出 EPUB 文件中所有图片资源的信息，包括文件名、格式、大小等。
/// 可用于显示图片列表或选择要查看的图片。
///
/// # 参数
///
/// * `file_path` - EPUB 文件的完整路径
///
/// # 返回值
///
/// * `Ok(EpubImageList)` - 图片列表信息
/// * `Err(ParserError)` - 获取失败
ApiResultEpubImageList getEpubImages({required String filePath}) =>
    RustLib.instance.api.crateApiGetEpubImages(filePath: filePath);

/// 提取 EPUB 中指定图片资源的字节数据
///
/// 根据图片的 href 提取图片资源的原始字节，用于 Flutter 侧显示。
///
/// # 参数
///
/// * `file_path` - EPUB 文件的完整路径
/// * `image_href` - 图片资源的 href（从 get_epub_images 获取）
///
/// # 返回值
///
/// * `Ok(Vec<u8>)` - 图片的原始字节数据
/// * `Err(String)` - 提取失败，返回错误消息
Uint8List getEpubImageResource({
  required String filePath,
  required String imageHref,
}) => RustLib.instance.api.crateApiGetEpubImageResource(
  filePath: filePath,
  imageHref: imageHref,
);

/// 获取 EPUB 中指定图片的元数据
///
/// 提取单个图片的详细信息，包括格式、尺寸、文件大小等。
///
/// # 参数
///
/// * `file_path` - EPUB 文件的完整路径
/// * `image_href` - 图片资源的 href
///
/// # 返回值
///
/// * `Ok(EpubImageInfo)` - 图片元数据信息
/// * `Err(ParserError)` - 获取失败
ApiResultEpubImageInfo getEpubImageMetadata({
  required String filePath,
  required String imageHref,
}) => RustLib.instance.api.crateApiGetEpubImageMetadata(
  filePath: filePath,
  imageHref: imageHref,
);

/// 解析 HTML 内容为富文本
///
/// 将 HTML 格式的内容解析为结构化的富文本数据，保留加粗、斜体等样式信息。
///
/// # 参数
///
/// * `html_content` - HTML 格式的内容
///
/// # 返回值
///
/// 返回 `RichChapterContent`，包含段落列表和样式信息
RichChapterContent parseHtmlContent({required String htmlContent}) =>
    RustLib.instance.api.crateApiParseHtmlContent(htmlContent: htmlContent);

/// 解析 HTML 内容为富文本（简化版）
///
/// 使用简化的 HTML 解析器，适用于格式简单的 HTML 内容。
/// 性能更好，但支持的标签较少。
///
/// # 参数
///
/// * `html_content` - HTML 格式的内容
///
/// # 返回值
///
/// 返回富文本段落列表
List<RichParagraph> parseHtmlContentSimple({required String htmlContent}) =>
    RustLib.instance.api.crateApiParseHtmlContentSimple(
      htmlContent: htmlContent,
    );

/// 将富文本转换为纯文本
///
/// 从富文本数据中提取纯文本内容，移除所有样式信息。
///
/// # 参数
///
/// * `rich_content` - 富文本内容
///
/// # 返回值
///
/// 返回纯文本字符串
String richTextToPlain({required RichChapterContent richContent}) =>
    RustLib.instance.api.crateApiRichTextToPlain(richContent: richContent);

/// 解析 EPUB 章节为富文本
///
/// 从 EPUB 文件中提取指定章节的 HTML 内容并解析为富文本格式。
///
/// # 参数
///
/// * `file_path` - EPUB 文件路径
/// * `chapter_index` - 章节索引（从 0 开始）
///
/// # 返回值
///
/// 返回 `RichChapterContent`，包含解析后的富文本内容
ApiResultRichChapterContent parseEpubChapterRich({
  required String filePath,
  required int chapterIndex,
}) => RustLib.instance.api.crateApiParseEpubChapterRich(
  filePath: filePath,
  chapterIndex: chapterIndex,
);

/// 初始化书籍的搜索引擎
///
/// 创建或打开书籍的全文索引。
///
/// # 参数
///
/// * `book_id` - 书籍 ID
/// * `index_path` - 索引存储路径
///
/// # 返回值
///
/// * `Ok(())` - 初始化成功
/// * `Err(ParserError)` - 初始化失败
ApiResult initSearchIndex({
  required String bookId,
  required String indexPath,
}) => RustLib.instance.api.crateApiInitSearchIndex(
  bookId: bookId,
  indexPath: indexPath,
);

/// 索引章节内容
///
/// 将章节内容添加到搜索索引中。
///
/// # 参数
///
/// * `book_id` - 书籍 ID
/// * `index_path` - 索引路径
/// * `chapter_id` - 章节 ID
/// * `chapter_title` - 章节标题
/// * `content` - 章节内容
///
/// # 返回值
///
/// * `Ok(())` - 索引成功
/// * `Err(ParserError)` - 索引失败
ApiResult indexChapterContent({
  required String bookId,
  required String indexPath,
  required int chapterId,
  required String chapterTitle,
  required String content,
}) => RustLib.instance.api.crateApiIndexChapterContent(
  bookId: bookId,
  indexPath: indexPath,
  chapterId: chapterId,
  chapterTitle: chapterTitle,
  content: content,
);

/// 搜索书籍内容
///
/// 在书籍中搜索关键字，返回匹配的结果。
///
/// # 参数
///
/// * `book_id` - 书籍 ID
/// * `index_path` - 索引路径
/// * `query` - 搜索关键字
/// * `limit` - 最大返回结果数
///
/// # 返回值
///
/// 返回 `SearchResults` 搜索结果
SearchResults searchInBook({
  required String bookId,
  required String indexPath,
  required String query,
  required int limit,
}) => RustLib.instance.api.crateApiSearchInBook(
  bookId: bookId,
  indexPath: indexPath,
  query: query,
  limit: limit,
);

/// 删除书籍的搜索索引
///
/// # 参数
///
/// * `book_id` - 书籍 ID
/// * `index_path` - 索引路径
///
/// # 返回值
///
/// * `true` - 删除成功
/// * `false` - 删除失败
bool deleteSearchIndex({required String bookId, required String indexPath}) =>
    RustLib.instance.api.crateApiDeleteSearchIndex(
      bookId: bookId,
      indexPath: indexPath,
    );

/// 清除所有搜索索引
///
/// 删除索引文件中的所有搜索数据。
/// 用于重置搜索索引或释放存储空间。
///
/// # 参数
///
/// * `index_path` - 索引路径
///
/// # 返回值
///
/// * `true` - 清除成功
/// * `false` - 清除失败
bool clearAllSearchIndex({required String indexPath}) =>
    RustLib.instance.api.crateApiClearAllSearchIndex(indexPath: indexPath);

/// 获取章节内容（零拷贝版本）
///
/// 使用 `ZeroCopyBuffer` 直接传递字节数据，避免 FFI 拷贝。
/// 适用于大章节内容传输，性能更优。
///
/// # 参数
///
/// * `file_path` - 文件路径
/// * `chapter_id` - 章节 ID
///
/// # 返回值
///
/// * `Ok(ZeroCopyBuffer<Vec<u8>>)` - 章节内容的原始字节数据
/// * `Err(ParserError)` - 提取失败
ApiResultZeroCopyBufferVecU8 getChapterContentZeroCopy({
  required String filePath,
  required int chapterId,
}) => RustLib.instance.api.crateApiGetChapterContentZeroCopy(
  filePath: filePath,
  chapterId: chapterId,
);

/// 搜索书籍（零拷贝版本）
///
/// 使用 `ZeroCopyBuffer` 传递搜索结果，避免大数据拷贝。
/// 适用于搜索结果较多的场景。
///
/// # 参数
///
/// * `book_id` - 书籍 ID
/// * `query` - 搜索关键词
/// * `limit` - 最大结果数
/// * `index_path` - 索引路径
///
/// # 返回值
///
/// * `Ok(ZeroCopyBuffer<Vec<SearchHit>>)` - 搜索结果的零拷贝缓冲区
/// * `Err(ParserError)` - 搜索失败
ApiResultZeroCopyBufferVecSearchHit searchBooksZeroCopy({
  required String bookId,
  required String query,
  required int limit,
  required String indexPath,
}) => RustLib.instance.api.crateApiSearchBooksZeroCopy(
  bookId: bookId,
  query: query,
  limit: limit,
  indexPath: indexPath,
);

/// 获取 PDF 封面图片数据（零拷贝优化）
///
/// 从 PDF 文件中提取封面图片的原始字节数据，使用 ZeroCopyBuffer 避免 FFI 拷贝。
/// 适用于需要直接在内存中处理封面数据的场景。
///
/// # 参数
///
/// * `file_path` - PDF 文件路径
///
/// # 返回值
///
/// * `Ok(ZeroCopyBuffer<Vec<u8>>)` - 封面图片的原始字节数据
/// * `Err(ParserError)` - 提取失败或 PDF 无封面
ApiResultZeroCopyBufferVecU8 getPdfCoverDataZeroCopy({
  required String filePath,
}) => RustLib.instance.api.crateApiGetPdfCoverDataZeroCopy(filePath: filePath);

/// 获取 EPUB 封面图片数据（零拷贝优化）
///
/// 从 EPUB 文件中提取封面图片的原始字节数据，使用 ZeroCopyBuffer 避免 FFI 拷贝。
/// 适用于需要直接在内存中处理封面数据的场景。
///
/// # 参数
///
/// * `file_path` - EPUB 文件路径
///
/// # 返回值
///
/// * `Ok(ZeroCopyBuffer<Vec<u8>>)` - 封面图片的原始字节数据
/// * `Err(ParserError)` - 提取失败
ApiResultZeroCopyBufferVecU8 getEpubCoverDataZeroCopy({
  required String filePath,
}) => RustLib.instance.api.crateApiGetEpubCoverDataZeroCopy(filePath: filePath);

/// 初始化增量解析器
///
/// 在应用启动时调用，初始化增量解析器全局实例。
///
/// # 返回值
///
/// * `Ok(())` - 初始化成功
/// * `Err(ParserError)` - 初始化失败（已经初始化）
ApiResult initIncrementalParser() =>
    RustLib.instance.api.crateApiInitIncrementalParser();

/// 解析本地书籍文件（增量解析版本）
///
/// 使用增量解析器检查文件变更，仅当文件变更时重新解析。
/// 适用于书架刷新等场景，显著提升性能。
///
/// # 参数
///
/// * `file_path` - 本地书籍文件的完整路径
///
/// # 返回值
///
/// * `Ok(LocalBookInfo)` - 解析成功，包含书籍信息和章节列表
/// * `Err(ParserError)` - 解析失败
ApiResultLocalBookInfo parseLocalBookIncremental({required String filePath}) =>
    RustLib.instance.api.crateApiParseLocalBookIncremental(filePath: filePath);

/// 清除增量解析器缓存
///
/// 清除所有文件的解析缓存，释放内存。
///
/// # 返回值
///
/// * `Ok(())` - 清除成功
/// * `Err(ParserError)` - 清除失败
ApiResult clearIncrementalParserCache() =>
    RustLib.instance.api.crateApiClearIncrementalParserCache();

/// 获取增量解析器缓存统计
///
/// 获取当前缓存的文件数量、章节数量和内存占用估算。
///
/// # 返回值
///
/// 返回 `CacheStats` 缓存统计信息
CacheStats getIncrementalParserStats() =>
    RustLib.instance.api.crateApiGetIncrementalParserStats();

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < () >>>
abstract class ApiResult implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < EpubImageInfo >>>
abstract class ApiResultEpubImageInfo implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < EpubImageList >>>
abstract class ApiResultEpubImageList implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < EpubMetadata >>>
abstract class ApiResultEpubMetadata implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < LocalBookInfo >>>
abstract class ApiResultLocalBookInfo implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < ParseResult >>>
abstract class ApiResultParseResult implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < RichChapterContent >>>
abstract class ApiResultRichChapterContent implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < String >>>
abstract class ApiResultString implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < ZeroCopyBuffer < Vec < SearchHit > > >>>
abstract class ApiResultZeroCopyBufferVecSearchHit
    implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < ZeroCopyBuffer < Vec < u8 > > >>>
abstract class ApiResultZeroCopyBufferVecU8 implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < i64 >>>
abstract class ApiResultI64 implements RustOpaqueInterface {}
