// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'ffi/types.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'stream/page_stream.dart';

/// 测试连接
String testConnection() => RustLib.instance.api.crateApiTestConnection();

/// 解析 TXT 文件
ApiResultParseResult parseTxtFile({required String filePath}) =>
    RustLib.instance.api.crateApiParseTxtFile(filePath: filePath);

/// 解析 EPUB 文件
ApiResultParseResult parseEpubFile({required String filePath}) =>
    RustLib.instance.api.crateApiParseEpubFile(filePath: filePath);

/// 排版处理文本
ApiResultString typesetText({
  required String content,
  required String language,
  required TypesetConfig config,
}) => RustLib.instance.api.crateApiTypesetText(
  content: content,
  language: language,
  config: config,
);

/// 获取文件大小
ApiResultI64 getFileSize({required String filePath}) =>
    RustLib.instance.api.crateApiGetFileSize(filePath: filePath);

/// 读取文件块
ApiResultString readFileChunk({
  required String filePath,
  required PlatformInt64 startPos,
  required PlatformInt64 chunkSize,
}) => RustLib.instance.api.crateApiReadFileChunk(
  filePath: filePath,
  startPos: startPos,
  chunkSize: chunkSize,
);

/// 创建分页器
PageStreamer createPageStreamer({
  required String content,
  required TypesetConfig config,
}) => RustLib.instance.api.crateApiCreatePageStreamer(
  content: content,
  config: config,
);

/// 将所有内容分页
List<PageContent> paginateAllContent({
  required String content,
  required int chapterId,
  required TypesetConfig config,
}) => RustLib.instance.api.crateApiPaginateAllContent(
  content: content,
  chapterId: chapterId,
  config: config,
);

/// 创建或更新阅读进度
ReadingProgress updateReadingProgress({
  required String bookId,
  required int chapterId,
  required int pageIndex,
  required int totalPages,
}) => RustLib.instance.api.crateApiUpdateReadingProgress(
  bookId: bookId,
  chapterId: chapterId,
  pageIndex: pageIndex,
  totalPages: totalPages,
);

/// 获取阅读进度
ReadingProgress? getReadingProgress({required String bookId}) =>
    RustLib.instance.api.crateApiGetReadingProgress(bookId: bookId);

/// 清除阅读进度
bool clearReadingProgress({required String bookId}) =>
    RustLib.instance.api.crateApiClearReadingProgress(bookId: bookId);

/// 获取所有书籍的阅读进度
List<ReadingProgress> getAllReadingProgress() =>
    RustLib.instance.api.crateApiGetAllReadingProgress();

/// 添加书签
Bookmark addBookmark({
  required String bookId,
  required int chapterId,
  required int pageIndex,
  required String title,
  String? note,
}) => RustLib.instance.api.crateApiAddBookmark(
  bookId: bookId,
  chapterId: chapterId,
  pageIndex: pageIndex,
  title: title,
  note: note,
);

/// 获取书籍的所有书签
List<Bookmark> getBookmarks({required String bookId}) =>
    RustLib.instance.api.crateApiGetBookmarks(bookId: bookId);

/// 删除书签
bool removeBookmark({required String bookId, required String bookmarkId}) =>
    RustLib.instance.api.crateApiRemoveBookmark(
      bookId: bookId,
      bookmarkId: bookmarkId,
    );

/// 清除书籍的所有书签
BigInt clearBookmarks({required String bookId}) =>
    RustLib.instance.api.crateApiClearBookmarks(bookId: bookId);

/// 获取所有书签
List<Bookmark> getAllBookmarks() =>
    RustLib.instance.api.crateApiGetAllBookmarks();

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < ParseResult >>>
abstract class ApiResultParseResult implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < String >>>
abstract class ApiResultString implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < i64 >>>
abstract class ApiResultI64 implements RustOpaqueInterface {}
