// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'api/bilingual.dart';
import 'api/book.dart';
import 'api/cover.dart';
import 'api/epub.dart';
import 'api/file.dart';
import 'api/search.dart';
import 'api/storage.dart';
import 'api/typeset.dart';
import 'dart:async';
import 'dart:convert';
import 'domain/error.dart';
import 'domain/parser.dart';
import 'domain/types.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'storage/models.dart';
import 'text/pagination.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_PageStreamerPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPageStreamer;

  @protected
  PageStreamer
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPageStreamer(
    dynamic raw,
  );

  @protected
  DateTime dco_decode_Chrono_Utc(dynamic raw);

  @protected
  PageStreamer
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPageStreamer(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AlignedSegment dco_decode_aligned_segment(dynamic raw);

  @protected
  AppError dco_decode_app_error(dynamic raw);

  @protected
  BilingualAlignment dco_decode_bilingual_alignment(dynamic raw);

  @protected
  Book dco_decode_book(dynamic raw);

  @protected
  BookCategory dco_decode_book_category(dynamic raw);

  @protected
  BookFormat dco_decode_book_format(dynamic raw);

  @protected
  BookMetadata dco_decode_book_metadata(dynamic raw);

  @protected
  BookStatus dco_decode_book_status(dynamic raw);

  @protected
  Bookmark dco_decode_bookmark(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DateTime dco_decode_box_autoadd_Chrono_Utc(dynamic raw);

  @protected
  Book dco_decode_box_autoadd_book(dynamic raw);

  @protected
  BookCategory dco_decode_box_autoadd_book_category(dynamic raw);

  @protected
  Bookmark dco_decode_box_autoadd_bookmark(dynamic raw);

  @protected
  Chapter dco_decode_box_autoadd_chapter(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  LayoutCache dco_decode_box_autoadd_layout_cache(dynamic raw);

  @protected
  LayoutCacheKey dco_decode_box_autoadd_layout_cache_key(dynamic raw);

  @protected
  Note dco_decode_box_autoadd_note(dynamic raw);

  @protected
  NoteType dco_decode_box_autoadd_note_type(dynamic raw);

  @protected
  ReadingProgress dco_decode_box_autoadd_reading_progress(dynamic raw);

  @protected
  ReadingSession dco_decode_box_autoadd_reading_session(dynamic raw);

  @protected
  ReadingStats dco_decode_box_autoadd_reading_stats(dynamic raw);

  @protected
  TypesetConfig dco_decode_box_autoadd_typeset_config(dynamic raw);

  @protected
  Chapter dco_decode_chapter(dynamic raw);

  @protected
  ChapterContent dco_decode_chapter_content(dynamic raw);

  @protected
  EpubMetadata dco_decode_epub_metadata(dynamic raw);

  @protected
  EpubTocItem dco_decode_epub_toc_item(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  GlobalStats dco_decode_global_stats(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  LanguageType dco_decode_language_type(dynamic raw);

  @protected
  LayoutCache dco_decode_layout_cache(dynamic raw);

  @protected
  LayoutCacheKey dco_decode_layout_cache_key(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AlignedSegment> dco_decode_list_aligned_segment(dynamic raw);

  @protected
  List<Book> dco_decode_list_book(dynamic raw);

  @protected
  List<BookCategory> dco_decode_list_book_category(dynamic raw);

  @protected
  List<Bookmark> dco_decode_list_bookmark(dynamic raw);

  @protected
  List<Chapter> dco_decode_list_chapter(dynamic raw);

  @protected
  List<EpubTocItem> dco_decode_list_epub_toc_item(dynamic raw);

  @protected
  List<Note> dco_decode_list_note(dynamic raw);

  @protected
  List<PageContent> dco_decode_list_page_content(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ReadingSession> dco_decode_list_reading_session(dynamic raw);

  @protected
  List<ReadingStats> dco_decode_list_reading_stats(dynamic raw);

  @protected
  List<(PlatformInt64, PlatformInt64)> dco_decode_list_record_i_64_i_64(
    dynamic raw,
  );

  @protected
  List<RichParagraph> dco_decode_list_rich_paragraph(dynamic raw);

  @protected
  List<RichTextSpan> dco_decode_list_rich_text_span(dynamic raw);

  @protected
  List<SearchResult> dco_decode_list_search_result(dynamic raw);

  @protected
  Note dco_decode_note(dynamic raw);

  @protected
  NoteStats dco_decode_note_stats(dynamic raw);

  @protected
  NoteType dco_decode_note_type(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  DateTime? dco_decode_opt_box_autoadd_Chrono_Utc(dynamic raw);

  @protected
  Book? dco_decode_opt_box_autoadd_book(dynamic raw);

  @protected
  BookCategory? dco_decode_opt_box_autoadd_book_category(dynamic raw);

  @protected
  Bookmark? dco_decode_opt_box_autoadd_bookmark(dynamic raw);

  @protected
  Chapter? dco_decode_opt_box_autoadd_chapter(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  LayoutCache? dco_decode_opt_box_autoadd_layout_cache(dynamic raw);

  @protected
  NoteType? dco_decode_opt_box_autoadd_note_type(dynamic raw);

  @protected
  ReadingProgress? dco_decode_opt_box_autoadd_reading_progress(dynamic raw);

  @protected
  TypesetConfig? dco_decode_opt_box_autoadd_typeset_config(dynamic raw);

  @protected
  PageContent dco_decode_page_content(dynamic raw);

  @protected
  ParseBookResult dco_decode_parse_book_result(dynamic raw);

  @protected
  ParseResult dco_decode_parse_result(dynamic raw);

  @protected
  ReadingProgress dco_decode_reading_progress(dynamic raw);

  @protected
  ReadingSession dco_decode_reading_session(dynamic raw);

  @protected
  ReadingStats dco_decode_reading_stats(dynamic raw);

  @protected
  (PlatformInt64, PlatformInt64) dco_decode_record_i_64_i_64(dynamic raw);

  @protected
  RichChapterContent dco_decode_rich_chapter_content(dynamic raw);

  @protected
  RichParagraph dco_decode_rich_paragraph(dynamic raw);

  @protected
  RichTextSpan dco_decode_rich_text_span(dynamic raw);

  @protected
  SearchResult dco_decode_search_result(dynamic raw);

  @protected
  TypesetConfig dco_decode_typeset_config(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  PageStreamer
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPageStreamer(
    SseDeserializer deserializer,
  );

  @protected
  DateTime sse_decode_Chrono_Utc(SseDeserializer deserializer);

  @protected
  PageStreamer
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPageStreamer(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AlignedSegment sse_decode_aligned_segment(SseDeserializer deserializer);

  @protected
  AppError sse_decode_app_error(SseDeserializer deserializer);

  @protected
  BilingualAlignment sse_decode_bilingual_alignment(
    SseDeserializer deserializer,
  );

  @protected
  Book sse_decode_book(SseDeserializer deserializer);

  @protected
  BookCategory sse_decode_book_category(SseDeserializer deserializer);

  @protected
  BookFormat sse_decode_book_format(SseDeserializer deserializer);

  @protected
  BookMetadata sse_decode_book_metadata(SseDeserializer deserializer);

  @protected
  BookStatus sse_decode_book_status(SseDeserializer deserializer);

  @protected
  Bookmark sse_decode_bookmark(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DateTime sse_decode_box_autoadd_Chrono_Utc(SseDeserializer deserializer);

  @protected
  Book sse_decode_box_autoadd_book(SseDeserializer deserializer);

  @protected
  BookCategory sse_decode_box_autoadd_book_category(
    SseDeserializer deserializer,
  );

  @protected
  Bookmark sse_decode_box_autoadd_bookmark(SseDeserializer deserializer);

  @protected
  Chapter sse_decode_box_autoadd_chapter(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  LayoutCache sse_decode_box_autoadd_layout_cache(SseDeserializer deserializer);

  @protected
  LayoutCacheKey sse_decode_box_autoadd_layout_cache_key(
    SseDeserializer deserializer,
  );

  @protected
  Note sse_decode_box_autoadd_note(SseDeserializer deserializer);

  @protected
  NoteType sse_decode_box_autoadd_note_type(SseDeserializer deserializer);

  @protected
  ReadingProgress sse_decode_box_autoadd_reading_progress(
    SseDeserializer deserializer,
  );

  @protected
  ReadingSession sse_decode_box_autoadd_reading_session(
    SseDeserializer deserializer,
  );

  @protected
  ReadingStats sse_decode_box_autoadd_reading_stats(
    SseDeserializer deserializer,
  );

  @protected
  TypesetConfig sse_decode_box_autoadd_typeset_config(
    SseDeserializer deserializer,
  );

  @protected
  Chapter sse_decode_chapter(SseDeserializer deserializer);

  @protected
  ChapterContent sse_decode_chapter_content(SseDeserializer deserializer);

  @protected
  EpubMetadata sse_decode_epub_metadata(SseDeserializer deserializer);

  @protected
  EpubTocItem sse_decode_epub_toc_item(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  GlobalStats sse_decode_global_stats(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  LanguageType sse_decode_language_type(SseDeserializer deserializer);

  @protected
  LayoutCache sse_decode_layout_cache(SseDeserializer deserializer);

  @protected
  LayoutCacheKey sse_decode_layout_cache_key(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AlignedSegment> sse_decode_list_aligned_segment(
    SseDeserializer deserializer,
  );

  @protected
  List<Book> sse_decode_list_book(SseDeserializer deserializer);

  @protected
  List<BookCategory> sse_decode_list_book_category(
    SseDeserializer deserializer,
  );

  @protected
  List<Bookmark> sse_decode_list_bookmark(SseDeserializer deserializer);

  @protected
  List<Chapter> sse_decode_list_chapter(SseDeserializer deserializer);

  @protected
  List<EpubTocItem> sse_decode_list_epub_toc_item(SseDeserializer deserializer);

  @protected
  List<Note> sse_decode_list_note(SseDeserializer deserializer);

  @protected
  List<PageContent> sse_decode_list_page_content(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ReadingSession> sse_decode_list_reading_session(
    SseDeserializer deserializer,
  );

  @protected
  List<ReadingStats> sse_decode_list_reading_stats(
    SseDeserializer deserializer,
  );

  @protected
  List<(PlatformInt64, PlatformInt64)> sse_decode_list_record_i_64_i_64(
    SseDeserializer deserializer,
  );

  @protected
  List<RichParagraph> sse_decode_list_rich_paragraph(
    SseDeserializer deserializer,
  );

  @protected
  List<RichTextSpan> sse_decode_list_rich_text_span(
    SseDeserializer deserializer,
  );

  @protected
  List<SearchResult> sse_decode_list_search_result(
    SseDeserializer deserializer,
  );

  @protected
  Note sse_decode_note(SseDeserializer deserializer);

  @protected
  NoteStats sse_decode_note_stats(SseDeserializer deserializer);

  @protected
  NoteType sse_decode_note_type(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  DateTime? sse_decode_opt_box_autoadd_Chrono_Utc(SseDeserializer deserializer);

  @protected
  Book? sse_decode_opt_box_autoadd_book(SseDeserializer deserializer);

  @protected
  BookCategory? sse_decode_opt_box_autoadd_book_category(
    SseDeserializer deserializer,
  );

  @protected
  Bookmark? sse_decode_opt_box_autoadd_bookmark(SseDeserializer deserializer);

  @protected
  Chapter? sse_decode_opt_box_autoadd_chapter(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  LayoutCache? sse_decode_opt_box_autoadd_layout_cache(
    SseDeserializer deserializer,
  );

  @protected
  NoteType? sse_decode_opt_box_autoadd_note_type(SseDeserializer deserializer);

  @protected
  ReadingProgress? sse_decode_opt_box_autoadd_reading_progress(
    SseDeserializer deserializer,
  );

  @protected
  TypesetConfig? sse_decode_opt_box_autoadd_typeset_config(
    SseDeserializer deserializer,
  );

  @protected
  PageContent sse_decode_page_content(SseDeserializer deserializer);

  @protected
  ParseBookResult sse_decode_parse_book_result(SseDeserializer deserializer);

  @protected
  ParseResult sse_decode_parse_result(SseDeserializer deserializer);

  @protected
  ReadingProgress sse_decode_reading_progress(SseDeserializer deserializer);

  @protected
  ReadingSession sse_decode_reading_session(SseDeserializer deserializer);

  @protected
  ReadingStats sse_decode_reading_stats(SseDeserializer deserializer);

  @protected
  (PlatformInt64, PlatformInt64) sse_decode_record_i_64_i_64(
    SseDeserializer deserializer,
  );

  @protected
  RichChapterContent sse_decode_rich_chapter_content(
    SseDeserializer deserializer,
  );

  @protected
  RichParagraph sse_decode_rich_paragraph(SseDeserializer deserializer);

  @protected
  RichTextSpan sse_decode_rich_text_span(SseDeserializer deserializer);

  @protected
  SearchResult sse_decode_search_result(SseDeserializer deserializer);

  @protected
  TypesetConfig sse_decode_typeset_config(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  JSAny cst_encode_Chrono_Utc(DateTime raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_64(BigInt.from(raw.millisecondsSinceEpoch));
  }

  @protected
  String cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  JSAny cst_encode_aligned_segment(AlignedSegment raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.chinese),
      cst_encode_String(raw.english),
      cst_encode_f_32(raw.similarityScore),
      cst_encode_usize(raw.chinesePosition),
      cst_encode_usize(raw.englishPosition),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_app_error(AppError raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    if (raw is AppError_FileNotFound) {
      return [0, cst_encode_String(raw.path)].jsify()!;
    }
    if (raw is AppError_FileReadError) {
      return [
        1,
        cst_encode_String(raw.path),
        cst_encode_String(raw.details),
      ].jsify()!;
    }
    if (raw is AppError_UnsupportedFormat) {
      return [2, cst_encode_String(raw.format)].jsify()!;
    }
    if (raw is AppError_EpubParseError) {
      return [3, cst_encode_String(raw.reason)].jsify()!;
    }
    if (raw is AppError_PdfParseError) {
      return [4, cst_encode_String(raw.reason)].jsify()!;
    }
    if (raw is AppError_ChapterExtractError) {
      return [
        5,
        cst_encode_i_32(raw.index),
        cst_encode_String(raw.reason),
      ].jsify()!;
    }
    if (raw is AppError_TypesetConfigError) {
      return [6, cst_encode_String(raw.reason)].jsify()!;
    }
    if (raw is AppError_DatabaseError) {
      return [7, cst_encode_String(raw.reason)].jsify()!;
    }
    if (raw is AppError_SearchError) {
      return [8, cst_encode_String(raw.reason)].jsify()!;
    }
    if (raw is AppError_SecurityError) {
      return [
        9,
        cst_encode_String(raw.reason),
        cst_encode_String(raw.path),
      ].jsify()!;
    }
    if (raw is AppError_InvalidInput) {
      return [10, cst_encode_String(raw.reason)].jsify()!;
    }
    if (raw is AppError_InternalError) {
      return [11, cst_encode_String(raw.reason)].jsify()!;
    }
    if (raw is AppError_Other) {
      return [12, cst_encode_String(raw.field0)].jsify()!;
    }

    throw Exception('unreachable');
  }

  @protected
  JSAny cst_encode_bilingual_alignment(BilingualAlignment raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_list_aligned_segment(raw.segments),
      cst_encode_list_String(raw.unmatchedChinese),
      cst_encode_list_String(raw.unmatchedEnglish),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_book(Book raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.bookId),
      cst_encode_String(raw.filePath),
      cst_encode_opt_String(raw.fileHash),
      cst_encode_i_64(raw.fileSize),
      cst_encode_opt_box_autoadd_i_64(raw.fileMtime),
      cst_encode_String(raw.title),
      cst_encode_opt_String(raw.author),
      cst_encode_opt_String(raw.description),
      cst_encode_opt_String(raw.coverPath),
      cst_encode_i_32(raw.chapterCount),
      cst_encode_i_64(raw.totalCharacters),
      cst_encode_book_format(raw.format),
      cst_encode_Chrono_Utc(raw.addedAt),
      cst_encode_opt_box_autoadd_Chrono_Utc(raw.lastOpenedAt),
      cst_encode_book_status(raw.status),
      cst_encode_bool(raw.isPinned),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_book_category(BookCategory raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.id),
      cst_encode_String(raw.name),
      cst_encode_opt_String(raw.description),
      cst_encode_String(raw.color),
      cst_encode_i_32(raw.sortOrder),
      cst_encode_bool(raw.isSystem),
      cst_encode_Chrono_Utc(raw.createdAt),
      cst_encode_opt_box_autoadd_Chrono_Utc(raw.updatedAt),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_book_metadata(BookMetadata raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.title),
      cst_encode_String(raw.author),
      cst_encode_opt_String(raw.description),
      cst_encode_opt_String(raw.coverPath),
      cst_encode_opt_box_autoadd_i_32(raw.publishYear),
      cst_encode_opt_String(raw.language),
      cst_encode_i_32(raw.chapterCount),
      cst_encode_i_64(raw.totalCharacters),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_bookmark(Bookmark raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.id),
      cst_encode_String(raw.bookId),
      cst_encode_i_32(raw.chapterIndex),
      cst_encode_opt_String(raw.chapterId),
      cst_encode_i_64(raw.charOffset),
      cst_encode_String(raw.title),
      cst_encode_Chrono_Utc(raw.createdAt),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_box_autoadd_Chrono_Utc(DateTime raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_Chrono_Utc(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_book(Book raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_book(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_book_category(BookCategory raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_book_category(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_bookmark(Bookmark raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_bookmark(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_chapter(Chapter raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_chapter(raw);
  }

  @protected
  int cst_encode_box_autoadd_i_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_32(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_i_64(PlatformInt64 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_64(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_layout_cache(LayoutCache raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_layout_cache(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_layout_cache_key(LayoutCacheKey raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_layout_cache_key(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_note(Note raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_note(raw);
  }

  @protected
  int cst_encode_box_autoadd_note_type(NoteType raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_note_type(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_reading_progress(ReadingProgress raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_reading_progress(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_reading_session(ReadingSession raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_reading_session(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_reading_stats(ReadingStats raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_reading_stats(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_typeset_config(TypesetConfig raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_typeset_config(raw);
  }

  @protected
  JSAny cst_encode_chapter(Chapter raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.id),
      cst_encode_String(raw.bookId),
      cst_encode_String(raw.title),
      cst_encode_String(raw.contentFile),
      cst_encode_i_32(raw.chapterIndex),
      cst_encode_i_64(raw.wordCount),
      cst_encode_Chrono_Utc(raw.cachedAt),
      cst_encode_i_32(raw.level),
      cst_encode_i_64(raw.startIndex),
      cst_encode_i_64(raw.endIndex),
      cst_encode_i_64(raw.contentLength),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_chapter_content(ChapterContent raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    if (raw is ChapterContent_Raw) {
      return [0, cst_encode_String(raw.field0)].jsify()!;
    }
    if (raw is ChapterContent_Pages) {
      return [1, cst_encode_list_page_content(raw.field0)].jsify()!;
    }

    throw Exception('unreachable');
  }

  @protected
  JSAny cst_encode_epub_metadata(EpubMetadata raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.title),
      cst_encode_String(raw.author),
      cst_encode_opt_String(raw.coverPath),
      cst_encode_list_epub_toc_item(raw.toc),
      cst_encode_list_String(raw.spine),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_epub_toc_item(EpubTocItem raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.label),
      cst_encode_String(raw.href),
      cst_encode_i_32(raw.level),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_global_stats(GlobalStats raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_i_64(raw.totalReadingTimeSeconds),
      cst_encode_i_64(raw.totalCharactersRead),
      cst_encode_i_32(raw.booksReadCount),
      cst_encode_i_32(raw.booksCompletedCount),
      cst_encode_i_32(raw.consecutiveReadingDays),
      cst_encode_i_64(raw.todayReadingTimeSeconds),
      cst_encode_i_64(raw.todayCharactersRead),
      cst_encode_f_32(raw.averageReadingSpeed),
      cst_encode_i_32(raw.totalBooksCount),
      cst_encode_i_32(raw.totalNotesCount),
      cst_encode_i_32(raw.totalBookmarksCount),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_i_64(PlatformInt64 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return castNativeBigInt(raw);
  }

  @protected
  JSAny cst_encode_layout_cache(LayoutCache raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_list_record_i_64_i_64(raw.pageOffsets),
      cst_encode_i_32(raw.totalPages),
      cst_encode_Chrono_Utc(raw.createdAt),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_layout_cache_key(LayoutCacheKey raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.bookId),
      cst_encode_i_32(raw.chapterIndex),
      cst_encode_String(raw.configHash),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_list_String(List<String> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_String).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_aligned_segment(List<AlignedSegment> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_aligned_segment).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_book(List<Book> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_book).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_book_category(List<BookCategory> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_book_category).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_bookmark(List<Bookmark> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_bookmark).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_chapter(List<Chapter> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_chapter).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_epub_toc_item(List<EpubTocItem> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_epub_toc_item).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_note(List<Note> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_note).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_page_content(List<PageContent> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_page_content).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_u_8_strict(Uint8List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  JSAny cst_encode_list_reading_session(List<ReadingSession> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_reading_session).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_reading_stats(List<ReadingStats> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_reading_stats).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_record_i_64_i_64(
    List<(PlatformInt64, PlatformInt64)> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_record_i_64_i_64).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_rich_paragraph(List<RichParagraph> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_rich_paragraph).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_rich_text_span(List<RichTextSpan> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_rich_text_span).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_search_result(List<SearchResult> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_search_result).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_note(Note raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.id),
      cst_encode_String(raw.bookId),
      cst_encode_i_32(raw.chapterIndex),
      cst_encode_opt_String(raw.chapterId),
      cst_encode_i_64(raw.charOffset),
      cst_encode_i_64(raw.length),
      cst_encode_note_type(raw.noteType),
      cst_encode_String(raw.content),
      cst_encode_opt_String(raw.selectedText),
      cst_encode_opt_box_autoadd_i_32(raw.highlightColor),
      cst_encode_Chrono_Utc(raw.createdAt),
      cst_encode_Chrono_Utc(raw.updatedAt),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_note_stats(NoteStats raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_i_32(raw.totalCount),
      cst_encode_i_32(raw.highlightCount),
      cst_encode_i_32(raw.annotationCount),
    ].jsify()!;
  }

  @protected
  String? cst_encode_opt_String(String? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_String(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_Chrono_Utc(DateTime? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_Chrono_Utc(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_book(Book? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_book(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_book_category(BookCategory? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_book_category(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_bookmark(Bookmark? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_bookmark(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_chapter(Chapter? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_chapter(raw);
  }

  @protected
  int? cst_encode_opt_box_autoadd_i_32(int? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_i_32(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_i_64(PlatformInt64? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_i_64(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_layout_cache(LayoutCache? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_layout_cache(raw);
  }

  @protected
  int? cst_encode_opt_box_autoadd_note_type(NoteType? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_note_type(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_reading_progress(ReadingProgress? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_reading_progress(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_typeset_config(TypesetConfig? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_typeset_config(raw);
  }

  @protected
  JSAny cst_encode_page_content(PageContent raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_i_32(raw.chapterIndex),
      cst_encode_i_32(raw.pageIndex),
      cst_encode_String(raw.content),
      cst_encode_bool(raw.isLastPage),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_parse_book_result(ParseBookResult raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_parse_result(raw.parseResult),
      cst_encode_bool(raw.persistenceSucceeded),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_parse_result(ParseResult raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_book(raw.bookInfo),
      cst_encode_list_chapter(raw.chapters),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_reading_progress(ReadingProgress raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.bookId),
      cst_encode_i_32(raw.chapterIndex),
      cst_encode_opt_String(raw.chapterId),
      cst_encode_i_64(raw.charOffset),
      cst_encode_f_32(raw.progress),
      cst_encode_i_64(raw.readingTimeSeconds),
      cst_encode_Chrono_Utc(raw.lastReadAt),
      cst_encode_bool(raw.isCompleted),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_reading_session(ReadingSession raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.id),
      cst_encode_String(raw.bookId),
      cst_encode_i_32(raw.chapterIndex),
      cst_encode_opt_String(raw.chapterId),
      cst_encode_i_64(raw.startCharOffset),
      cst_encode_i_64(raw.endCharOffset),
      cst_encode_Chrono_Utc(raw.startedAt),
      cst_encode_Chrono_Utc(raw.endedAt),
      cst_encode_i_64(raw.durationSeconds),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_reading_stats(ReadingStats raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.bookId),
      cst_encode_String(raw.date),
      cst_encode_i_64(raw.readingTimeSeconds),
      cst_encode_i_64(raw.charactersRead),
      cst_encode_i_32(raw.sessionCount),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_record_i_64_i_64((PlatformInt64, PlatformInt64) raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [cst_encode_i_64(raw.$1), cst_encode_i_64(raw.$2)].jsify()!;
  }

  @protected
  JSAny cst_encode_rich_chapter_content(RichChapterContent raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.chapterId),
      cst_encode_list_rich_paragraph(raw.paragraphs),
      cst_encode_i_64(raw.totalCharacters),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_rich_paragraph(RichParagraph raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_list_rich_text_span(raw.spans),
      cst_encode_u_8(raw.indent),
      cst_encode_bool(raw.isHeading),
      cst_encode_u_8(raw.headingLevel),
      cst_encode_opt_String(raw.className),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_rich_text_span(RichTextSpan raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    if (raw is RichTextSpan_Plain) {
      return [0, cst_encode_String(raw.text)].jsify()!;
    }
    if (raw is RichTextSpan_Bold) {
      return [1, cst_encode_String(raw.text)].jsify()!;
    }
    if (raw is RichTextSpan_Italic) {
      return [2, cst_encode_String(raw.text)].jsify()!;
    }
    if (raw is RichTextSpan_BoldItalic) {
      return [3, cst_encode_String(raw.text)].jsify()!;
    }
    if (raw is RichTextSpan_Underline) {
      return [4, cst_encode_String(raw.text)].jsify()!;
    }
    if (raw is RichTextSpan_Strikethrough) {
      return [5, cst_encode_String(raw.text)].jsify()!;
    }
    if (raw is RichTextSpan_Code) {
      return [6, cst_encode_String(raw.text)].jsify()!;
    }
    if (raw is RichTextSpan_Link) {
      return [
        7,
        cst_encode_String(raw.text),
        cst_encode_String(raw.url),
      ].jsify()!;
    }

    throw Exception('unreachable');
  }

  @protected
  JSAny cst_encode_search_result(SearchResult raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_i_32(raw.chapterId),
      cst_encode_String(raw.chapterTitle),
      cst_encode_String(raw.snippet),
      cst_encode_i_64(raw.position),
      cst_encode_f_32(raw.score),
      cst_encode_i_64(raw.charOffset),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_typeset_config(TypesetConfig raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_i_32(raw.pageWidth),
      cst_encode_i_32(raw.pageHeight),
      cst_encode_i_32(raw.fontSize),
      cst_encode_f_32(raw.lineSpacing),
      cst_encode_f_32(raw.letterSpacing),
      cst_encode_f_32(raw.paragraphSpacing),
      cst_encode_u_8(raw.firstLineIndent),
      cst_encode_language_type(raw.language),
      cst_encode_bool(raw.enableHyphenation),
      cst_encode_opt_String(raw.hyphenationLanguage),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_usize(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return castNativeBigInt(raw);
  }

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPageStreamer(
    PageStreamer raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPageStreamer(
    PageStreamer raw,
  );

  @protected
  int cst_encode_book_format(BookFormat raw);

  @protected
  int cst_encode_book_status(BookStatus raw);

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  double cst_encode_f_32(double raw);

  @protected
  int cst_encode_i_32(int raw);

  @protected
  int cst_encode_language_type(LanguageType raw);

  @protected
  int cst_encode_note_type(NoteType raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPageStreamer(
    PageStreamer self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Chrono_Utc(DateTime self, SseSerializer serializer);

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPageStreamer(
    PageStreamer self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_aligned_segment(
    AlignedSegment self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_app_error(AppError self, SseSerializer serializer);

  @protected
  void sse_encode_bilingual_alignment(
    BilingualAlignment self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_book(Book self, SseSerializer serializer);

  @protected
  void sse_encode_book_category(BookCategory self, SseSerializer serializer);

  @protected
  void sse_encode_book_format(BookFormat self, SseSerializer serializer);

  @protected
  void sse_encode_book_metadata(BookMetadata self, SseSerializer serializer);

  @protected
  void sse_encode_book_status(BookStatus self, SseSerializer serializer);

  @protected
  void sse_encode_bookmark(Bookmark self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_Chrono_Utc(
    DateTime self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_book(Book self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_book_category(
    BookCategory self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bookmark(Bookmark self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_chapter(Chapter self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_layout_cache(
    LayoutCache self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_layout_cache_key(
    LayoutCacheKey self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_note(Note self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_note_type(
    NoteType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_reading_progress(
    ReadingProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_reading_session(
    ReadingSession self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_reading_stats(
    ReadingStats self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_typeset_config(
    TypesetConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_chapter(Chapter self, SseSerializer serializer);

  @protected
  void sse_encode_chapter_content(
    ChapterContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_epub_metadata(EpubMetadata self, SseSerializer serializer);

  @protected
  void sse_encode_epub_toc_item(EpubTocItem self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_global_stats(GlobalStats self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_language_type(LanguageType self, SseSerializer serializer);

  @protected
  void sse_encode_layout_cache(LayoutCache self, SseSerializer serializer);

  @protected
  void sse_encode_layout_cache_key(
    LayoutCacheKey self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_aligned_segment(
    List<AlignedSegment> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_book(List<Book> self, SseSerializer serializer);

  @protected
  void sse_encode_list_book_category(
    List<BookCategory> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bookmark(List<Bookmark> self, SseSerializer serializer);

  @protected
  void sse_encode_list_chapter(List<Chapter> self, SseSerializer serializer);

  @protected
  void sse_encode_list_epub_toc_item(
    List<EpubTocItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_note(List<Note> self, SseSerializer serializer);

  @protected
  void sse_encode_list_page_content(
    List<PageContent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_reading_session(
    List<ReadingSession> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_reading_stats(
    List<ReadingStats> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_i_64_i_64(
    List<(PlatformInt64, PlatformInt64)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rich_paragraph(
    List<RichParagraph> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rich_text_span(
    List<RichTextSpan> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_search_result(
    List<SearchResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_note(Note self, SseSerializer serializer);

  @protected
  void sse_encode_note_stats(NoteStats self, SseSerializer serializer);

  @protected
  void sse_encode_note_type(NoteType self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_Chrono_Utc(
    DateTime? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_book(Book? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_book_category(
    BookCategory? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bookmark(
    Bookmark? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_chapter(
    Chapter? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_layout_cache(
    LayoutCache? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_note_type(
    NoteType? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_reading_progress(
    ReadingProgress? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_typeset_config(
    TypesetConfig? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_page_content(PageContent self, SseSerializer serializer);

  @protected
  void sse_encode_parse_book_result(
    ParseBookResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_parse_result(ParseResult self, SseSerializer serializer);

  @protected
  void sse_encode_reading_progress(
    ReadingProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_reading_session(
    ReadingSession self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_reading_stats(ReadingStats self, SseSerializer serializer);

  @protected
  void sse_encode_record_i_64_i_64(
    (PlatformInt64, PlatformInt64) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rich_chapter_content(
    RichChapterContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rich_paragraph(RichParagraph self, SseSerializer serializer);

  @protected
  void sse_encode_rich_text_span(RichTextSpan self, SseSerializer serializer);

  @protected
  void sse_encode_search_result(SearchResult self, SseSerializer serializer);

  @protected
  void sse_encode_typeset_config(TypesetConfig self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void wire__crate__api__bilingual__align_bilingual_content(
    NativePortType port_,
    String chinese_content,
    String english_content,
    double min_similarity,
  ) => wasmModule.wire__crate__api__bilingual__align_bilingual_content(
    port_,
    chinese_content,
    english_content,
    min_similarity,
  );

  void wire__crate__api__storage__assign_category_to_book(
    NativePortType port_,
    String book_id,
    String category_id,
  ) => wasmModule.wire__crate__api__storage__assign_category_to_book(
    port_,
    book_id,
    category_id,
  );

  void wire__crate__api__storage__cleanup_expired_layout_cache(
    NativePortType port_,
    JSAny max_age_days,
  ) => wasmModule.wire__crate__api__storage__cleanup_expired_layout_cache(
    port_,
    max_age_days,
  );

  void wire__crate__api__search__clear_all_search_index(NativePortType port_) =>
      wasmModule.wire__crate__api__search__clear_all_search_index(port_);

  void wire__crate__api__storage__clear_categories_for_book(
    NativePortType port_,
    String book_id,
  ) => wasmModule.wire__crate__api__storage__clear_categories_for_book(
    port_,
    book_id,
  );

  void wire__crate__api__storage__clear_layout_cache(
    NativePortType port_,
    String book_id,
  ) => wasmModule.wire__crate__api__storage__clear_layout_cache(port_, book_id);

  void wire__crate__api__storage__clear_reading_progress(
    NativePortType port_,
    String book_id,
  ) => wasmModule.wire__crate__api__storage__clear_reading_progress(
    port_,
    book_id,
  );

  void wire__crate__api__storage__create_bookmark(
    NativePortType port_,
    JSAny bookmark,
  ) => wasmModule.wire__crate__api__storage__create_bookmark(port_, bookmark);

  void wire__crate__api__storage__create_note(
    NativePortType port_,
    JSAny note,
  ) => wasmModule.wire__crate__api__storage__create_note(port_, note);

  void wire__crate__api__book__create_page_streamer(
    NativePortType port_,
    String file_path,
    int chapter_index,
    JSAny config,
  ) => wasmModule.wire__crate__api__book__create_page_streamer(
    port_,
    file_path,
    chapter_index,
    config,
  );

  void wire__crate__api__storage__delete_book(
    NativePortType port_,
    String book_id,
  ) => wasmModule.wire__crate__api__storage__delete_book(port_, book_id);

  void wire__crate__api__search__delete_book_search_index(
    NativePortType port_,
    String book_id,
  ) => wasmModule.wire__crate__api__search__delete_book_search_index(
    port_,
    book_id,
  );

  void wire__crate__api__storage__delete_bookmark(
    NativePortType port_,
    String bookmark_id,
  ) =>
      wasmModule.wire__crate__api__storage__delete_bookmark(port_, bookmark_id);

  void wire__crate__api__storage__delete_bookmarks_by_book(
    NativePortType port_,
    String book_id,
  ) => wasmModule.wire__crate__api__storage__delete_bookmarks_by_book(
    port_,
    book_id,
  );

  void wire__crate__api__storage__delete_category(
    NativePortType port_,
    String category_id,
  ) =>
      wasmModule.wire__crate__api__storage__delete_category(port_, category_id);

  void wire__crate__api__storage__delete_chapters_by_book(
    NativePortType port_,
    String book_id,
  ) => wasmModule.wire__crate__api__storage__delete_chapters_by_book(
    port_,
    book_id,
  );

  void wire__crate__api__storage__delete_note(
    NativePortType port_,
    String note_id,
  ) => wasmModule.wire__crate__api__storage__delete_note(port_, note_id);

  void wire__crate__api__storage__delete_notes_by_book(
    NativePortType port_,
    String book_id,
  ) => wasmModule.wire__crate__api__storage__delete_notes_by_book(
    port_,
    book_id,
  );

  void wire__crate__api__storage__delete_sessions_by_book(
    NativePortType port_,
    String book_id,
  ) => wasmModule.wire__crate__api__storage__delete_sessions_by_book(
    port_,
    book_id,
  );

  void wire__crate__api__storage__export_database(
    NativePortType port_,
    String dest_path,
  ) => wasmModule.wire__crate__api__storage__export_database(port_, dest_path);

  void wire__crate__api__cover__extract_book_cover(
    NativePortType port_,
    String file_path,
    String output_dir,
  ) => wasmModule.wire__crate__api__cover__extract_book_cover(
    port_,
    file_path,
    output_dir,
  );

  void wire__crate__api__book__extract_metadata(
    NativePortType port_,
    String file_path,
  ) => wasmModule.wire__crate__api__book__extract_metadata(port_, file_path);

  void wire__crate__api__storage__get_all_books(NativePortType port_) =>
      wasmModule.wire__crate__api__storage__get_all_books(port_);

  void wire__crate__api__storage__get_all_categories(NativePortType port_) =>
      wasmModule.wire__crate__api__storage__get_all_categories(port_);

  void wire__crate__api__storage__get_book(
    NativePortType port_,
    String book_id,
  ) => wasmModule.wire__crate__api__storage__get_book(port_, book_id);

  void wire__crate__api__storage__get_book_count(NativePortType port_) =>
      wasmModule.wire__crate__api__storage__get_book_count(port_);

  void wire__crate__api__storage__get_bookmark(
    NativePortType port_,
    String bookmark_id,
  ) => wasmModule.wire__crate__api__storage__get_bookmark(port_, bookmark_id);

  void wire__crate__api__storage__get_bookmark_stats(
    NativePortType port_,
    String book_id,
  ) => wasmModule.wire__crate__api__storage__get_bookmark_stats(port_, book_id);

  void wire__crate__api__storage__get_bookmarks(
    NativePortType port_,
    String book_id,
  ) => wasmModule.wire__crate__api__storage__get_bookmarks(port_, book_id);

  void wire__crate__api__storage__get_books_by_status(
    NativePortType port_,
    int status,
  ) => wasmModule.wire__crate__api__storage__get_books_by_status(port_, status);

  void wire__crate__api__storage__get_books_paginated(
    NativePortType port_,
    int limit,
    int offset,
    String? sort_by,
    String? sort_order,
  ) => wasmModule.wire__crate__api__storage__get_books_paginated(
    port_,
    limit,
    offset,
    sort_by,
    sort_order,
  );

  void wire__crate__api__storage__get_categories_for_book(
    NativePortType port_,
    String book_id,
  ) => wasmModule.wire__crate__api__storage__get_categories_for_book(
    port_,
    book_id,
  );

  void wire__crate__api__storage__get_category(
    NativePortType port_,
    String category_id,
  ) => wasmModule.wire__crate__api__storage__get_category(port_, category_id);

  void wire__crate__api__book__get_chapter(
    NativePortType port_,
    String file_path,
    int chapter_index,
    JSAny? config,
  ) => wasmModule.wire__crate__api__book__get_chapter(
    port_,
    file_path,
    chapter_index,
    config,
  );

  void wire__crate__api__storage__get_chapter_by_index(
    NativePortType port_,
    String book_id,
    int chapter_index,
  ) => wasmModule.wire__crate__api__storage__get_chapter_by_index(
    port_,
    book_id,
    chapter_index,
  );

  void wire__crate__api__storage__get_chapters_by_book(
    NativePortType port_,
    String book_id,
  ) => wasmModule.wire__crate__api__storage__get_chapters_by_book(
    port_,
    book_id,
  );

  void wire__crate__api__epub__get_epub_chapter_rich_content(
    NativePortType port_,
    String file_path,
    int chapter_index,
    JSAny config,
  ) => wasmModule.wire__crate__api__epub__get_epub_chapter_rich_content(
    port_,
    file_path,
    chapter_index,
    config,
  );

  void wire__crate__api__epub__get_epub_metadata(
    NativePortType port_,
    String file_path,
  ) => wasmModule.wire__crate__api__epub__get_epub_metadata(port_, file_path);

  void wire__crate__api__file__get_file_size(
    NativePortType port_,
    String file_path,
  ) => wasmModule.wire__crate__api__file__get_file_size(port_, file_path);

  void wire__crate__api__storage__get_global_reading_stats(
    NativePortType port_,
  ) => wasmModule.wire__crate__api__storage__get_global_reading_stats(port_);

  void wire__crate__api__storage__get_layout_cache(
    NativePortType port_,
    String book_id,
    int chapter_index,
    String config_hash,
  ) => wasmModule.wire__crate__api__storage__get_layout_cache(
    port_,
    book_id,
    chapter_index,
    config_hash,
  );

  void wire__crate__api__storage__get_note_stats(
    NativePortType port_,
    String book_id,
  ) => wasmModule.wire__crate__api__storage__get_note_stats(port_, book_id);

  void wire__crate__api__storage__get_notes(
    NativePortType port_,
    String book_id,
    int? note_type,
  ) => wasmModule.wire__crate__api__storage__get_notes(
    port_,
    book_id,
    note_type,
  );

  void wire__crate__api__storage__get_pinned_books(NativePortType port_) =>
      wasmModule.wire__crate__api__storage__get_pinned_books(port_);

  void wire__crate__api__storage__get_reading_progress(
    NativePortType port_,
    String book_id,
  ) => wasmModule.wire__crate__api__storage__get_reading_progress(
    port_,
    book_id,
  );

  void wire__crate__api__storage__get_reading_sessions(
    NativePortType port_,
    String book_id,
    JSAny limit,
  ) => wasmModule.wire__crate__api__storage__get_reading_sessions(
    port_,
    book_id,
    limit,
  );

  void wire__crate__api__storage__get_reading_stats_range(
    NativePortType port_,
    String start_date,
    String end_date,
  ) => wasmModule.wire__crate__api__storage__get_reading_stats_range(
    port_,
    start_date,
    end_date,
  );

  void wire__crate__api__storage__get_recent_sessions(
    NativePortType port_,
    JSAny limit,
  ) => wasmModule.wire__crate__api__storage__get_recent_sessions(port_, limit);

  void wire__crate__api__storage__get_recently_read_books(
    NativePortType port_,
    JSAny limit,
  ) => wasmModule.wire__crate__api__storage__get_recently_read_books(
    port_,
    limit,
  );

  void wire__crate__api__storage__get_sessions_by_date_range(
    NativePortType port_,
    String book_id,
    String start_date,
    String end_date,
  ) => wasmModule.wire__crate__api__storage__get_sessions_by_date_range(
    port_,
    book_id,
    start_date,
    end_date,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__book__get_supported_formats() =>
      wasmModule.wire__crate__api__book__get_supported_formats();

  void wire__crate__api__storage__get_today_reading_stats(
    NativePortType port_,
  ) => wasmModule.wire__crate__api__storage__get_today_reading_stats(port_);

  void wire__crate__api__storage__import_bookmarks(
    NativePortType port_,
    JSAny bookmarks,
  ) => wasmModule.wire__crate__api__storage__import_bookmarks(port_, bookmarks);

  void wire__crate__api__search__index_chapter_content(
    NativePortType port_,
    String book_id,
    int chapter_id,
    String chapter_title,
    String content,
  ) => wasmModule.wire__crate__api__search__index_chapter_content(
    port_,
    book_id,
    chapter_id,
    chapter_title,
    content,
  );

  void wire__crate__api__search__init_search_engine(NativePortType port_) =>
      wasmModule.wire__crate__api__search__init_search_engine(port_);

  void wire__crate__api__storage__init_storage(
    NativePortType port_,
    String data_dir,
  ) => wasmModule.wire__crate__api__storage__init_storage(port_, data_dir);

  void wire__crate__api__book__paginate_all_content(
    NativePortType port_,
    String file_path,
    int chapter_index,
    JSAny config,
  ) => wasmModule.wire__crate__api__book__paginate_all_content(
    port_,
    file_path,
    chapter_index,
    config,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__epub__paginate_epub_rich_content(
    JSAny paragraphs,
    int chapter_index,
    JSAny config,
  ) => wasmModule.wire__crate__api__epub__paginate_epub_rich_content(
    paragraphs,
    chapter_index,
    config,
  );

  void wire__crate__api__book__parse_book(
    NativePortType port_,
    String file_path,
  ) => wasmModule.wire__crate__api__book__parse_book(port_, file_path);

  void wire__crate__api__epub__parse_epub_chapter_rich(
    NativePortType port_,
    String file_path,
    int chapter_index,
  ) => wasmModule.wire__crate__api__epub__parse_epub_chapter_rich(
    port_,
    file_path,
    chapter_index,
  );

  void wire__crate__api__file__read_file_chunk(
    NativePortType port_,
    String file_path,
    JSAny start_pos,
    JSAny chunk_size,
  ) => wasmModule.wire__crate__api__file__read_file_chunk(
    port_,
    file_path,
    start_pos,
    chunk_size,
  );

  void wire__crate__api__storage__record_reading_session(
    NativePortType port_,
    JSAny session,
  ) => wasmModule.wire__crate__api__storage__record_reading_session(
    port_,
    session,
  );

  void wire__crate__api__storage__remove_category_from_book(
    NativePortType port_,
    String book_id,
    String category_id,
  ) => wasmModule.wire__crate__api__storage__remove_category_from_book(
    port_,
    book_id,
    category_id,
  );

  void wire__crate__api__storage__restore_database(
    NativePortType port_,
    String backup_path,
  ) => wasmModule.wire__crate__api__storage__restore_database(
    port_,
    backup_path,
  );

  void wire__crate__api__storage__save_book(NativePortType port_, JSAny book) =>
      wasmModule.wire__crate__api__storage__save_book(port_, book);

  void wire__crate__api__storage__save_category(
    NativePortType port_,
    JSAny category,
  ) => wasmModule.wire__crate__api__storage__save_category(port_, category);

  void wire__crate__api__storage__save_chapters(
    NativePortType port_,
    String book_id,
    JSAny chapters,
  ) => wasmModule.wire__crate__api__storage__save_chapters(
    port_,
    book_id,
    chapters,
  );

  void wire__crate__api__storage__save_layout_cache(
    NativePortType port_,
    JSAny cache,
    JSAny key,
  ) => wasmModule.wire__crate__api__storage__save_layout_cache(
    port_,
    cache,
    key,
  );

  void wire__crate__api__storage__save_reading_progress(
    NativePortType port_,
    JSAny progress,
  ) => wasmModule.wire__crate__api__storage__save_reading_progress(
    port_,
    progress,
  );

  void wire__crate__api__storage__search_books(
    NativePortType port_,
    String keyword,
  ) => wasmModule.wire__crate__api__storage__search_books(port_, keyword);

  void wire__crate__api__search__search_in_book(
    NativePortType port_,
    String book_id,
    String query,
    int limit,
  ) => wasmModule.wire__crate__api__search__search_in_book(
    port_,
    book_id,
    query,
    limit,
  );

  void wire__crate__api__storage__set_categories_for_book(
    NativePortType port_,
    String book_id,
    JSAny category_ids,
  ) => wasmModule.wire__crate__api__storage__set_categories_for_book(
    port_,
    book_id,
    category_ids,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__bilingual__simple_bilingual_align(
    String chinese_content,
    String english_content,
  ) => wasmModule.wire__crate__api__bilingual__simple_bilingual_align(
    chinese_content,
    english_content,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__cover__supports_cover_extraction(String file_path) =>
      wasmModule.wire__crate__api__cover__supports_cover_extraction(file_path);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__book__supports_format(String format) =>
      wasmModule.wire__crate__api__book__supports_format(format);

  void wire__crate__api__storage__sync_bookmarks(
    NativePortType port_,
    JSAny local_bookmarks,
    JSAny remote_bookmarks,
  ) => wasmModule.wire__crate__api__storage__sync_bookmarks(
    port_,
    local_bookmarks,
    remote_bookmarks,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__test_connection() =>
      wasmModule.wire__crate__api__test_connection();

  void wire__crate__api__typeset__typeset_text(
    NativePortType port_,
    String content,
    JSAny config,
  ) => wasmModule.wire__crate__api__typeset__typeset_text(
    port_,
    content,
    config,
  );

  void wire__crate__api__storage__update_book_pin(
    NativePortType port_,
    String book_id,
    bool is_pinned,
  ) => wasmModule.wire__crate__api__storage__update_book_pin(
    port_,
    book_id,
    is_pinned,
  );

  void wire__crate__api__storage__update_book_status(
    NativePortType port_,
    String book_id,
    int status,
  ) => wasmModule.wire__crate__api__storage__update_book_status(
    port_,
    book_id,
    status,
  );

  void wire__crate__api__storage__update_daily_stats(
    NativePortType port_,
    JSAny stats,
  ) => wasmModule.wire__crate__api__storage__update_daily_stats(port_, stats);

  void wire__crate__api__storage__update_note(
    NativePortType port_,
    JSAny note,
  ) => wasmModule.wire__crate__api__storage__update_note(port_, note);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPageStreamer(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPageStreamer(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPageStreamer(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPageStreamer(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void wire__crate__api__bilingual__align_bilingual_content(
    NativePortType port_,
    String chinese_content,
    String english_content,
    double min_similarity,
  );

  external void wire__crate__api__storage__assign_category_to_book(
    NativePortType port_,
    String book_id,
    String category_id,
  );

  external void wire__crate__api__storage__cleanup_expired_layout_cache(
    NativePortType port_,
    JSAny max_age_days,
  );

  external void wire__crate__api__search__clear_all_search_index(
    NativePortType port_,
  );

  external void wire__crate__api__storage__clear_categories_for_book(
    NativePortType port_,
    String book_id,
  );

  external void wire__crate__api__storage__clear_layout_cache(
    NativePortType port_,
    String book_id,
  );

  external void wire__crate__api__storage__clear_reading_progress(
    NativePortType port_,
    String book_id,
  );

  external void wire__crate__api__storage__create_bookmark(
    NativePortType port_,
    JSAny bookmark,
  );

  external void wire__crate__api__storage__create_note(
    NativePortType port_,
    JSAny note,
  );

  external void wire__crate__api__book__create_page_streamer(
    NativePortType port_,
    String file_path,
    int chapter_index,
    JSAny config,
  );

  external void wire__crate__api__storage__delete_book(
    NativePortType port_,
    String book_id,
  );

  external void wire__crate__api__search__delete_book_search_index(
    NativePortType port_,
    String book_id,
  );

  external void wire__crate__api__storage__delete_bookmark(
    NativePortType port_,
    String bookmark_id,
  );

  external void wire__crate__api__storage__delete_bookmarks_by_book(
    NativePortType port_,
    String book_id,
  );

  external void wire__crate__api__storage__delete_category(
    NativePortType port_,
    String category_id,
  );

  external void wire__crate__api__storage__delete_chapters_by_book(
    NativePortType port_,
    String book_id,
  );

  external void wire__crate__api__storage__delete_note(
    NativePortType port_,
    String note_id,
  );

  external void wire__crate__api__storage__delete_notes_by_book(
    NativePortType port_,
    String book_id,
  );

  external void wire__crate__api__storage__delete_sessions_by_book(
    NativePortType port_,
    String book_id,
  );

  external void wire__crate__api__storage__export_database(
    NativePortType port_,
    String dest_path,
  );

  external void wire__crate__api__cover__extract_book_cover(
    NativePortType port_,
    String file_path,
    String output_dir,
  );

  external void wire__crate__api__book__extract_metadata(
    NativePortType port_,
    String file_path,
  );

  external void wire__crate__api__storage__get_all_books(NativePortType port_);

  external void wire__crate__api__storage__get_all_categories(
    NativePortType port_,
  );

  external void wire__crate__api__storage__get_book(
    NativePortType port_,
    String book_id,
  );

  external void wire__crate__api__storage__get_book_count(NativePortType port_);

  external void wire__crate__api__storage__get_bookmark(
    NativePortType port_,
    String bookmark_id,
  );

  external void wire__crate__api__storage__get_bookmark_stats(
    NativePortType port_,
    String book_id,
  );

  external void wire__crate__api__storage__get_bookmarks(
    NativePortType port_,
    String book_id,
  );

  external void wire__crate__api__storage__get_books_by_status(
    NativePortType port_,
    int status,
  );

  external void wire__crate__api__storage__get_books_paginated(
    NativePortType port_,
    int limit,
    int offset,
    String? sort_by,
    String? sort_order,
  );

  external void wire__crate__api__storage__get_categories_for_book(
    NativePortType port_,
    String book_id,
  );

  external void wire__crate__api__storage__get_category(
    NativePortType port_,
    String category_id,
  );

  external void wire__crate__api__book__get_chapter(
    NativePortType port_,
    String file_path,
    int chapter_index,
    JSAny? config,
  );

  external void wire__crate__api__storage__get_chapter_by_index(
    NativePortType port_,
    String book_id,
    int chapter_index,
  );

  external void wire__crate__api__storage__get_chapters_by_book(
    NativePortType port_,
    String book_id,
  );

  external void wire__crate__api__epub__get_epub_chapter_rich_content(
    NativePortType port_,
    String file_path,
    int chapter_index,
    JSAny config,
  );

  external void wire__crate__api__epub__get_epub_metadata(
    NativePortType port_,
    String file_path,
  );

  external void wire__crate__api__file__get_file_size(
    NativePortType port_,
    String file_path,
  );

  external void wire__crate__api__storage__get_global_reading_stats(
    NativePortType port_,
  );

  external void wire__crate__api__storage__get_layout_cache(
    NativePortType port_,
    String book_id,
    int chapter_index,
    String config_hash,
  );

  external void wire__crate__api__storage__get_note_stats(
    NativePortType port_,
    String book_id,
  );

  external void wire__crate__api__storage__get_notes(
    NativePortType port_,
    String book_id,
    int? note_type,
  );

  external void wire__crate__api__storage__get_pinned_books(
    NativePortType port_,
  );

  external void wire__crate__api__storage__get_reading_progress(
    NativePortType port_,
    String book_id,
  );

  external void wire__crate__api__storage__get_reading_sessions(
    NativePortType port_,
    String book_id,
    JSAny limit,
  );

  external void wire__crate__api__storage__get_reading_stats_range(
    NativePortType port_,
    String start_date,
    String end_date,
  );

  external void wire__crate__api__storage__get_recent_sessions(
    NativePortType port_,
    JSAny limit,
  );

  external void wire__crate__api__storage__get_recently_read_books(
    NativePortType port_,
    JSAny limit,
  );

  external void wire__crate__api__storage__get_sessions_by_date_range(
    NativePortType port_,
    String book_id,
    String start_date,
    String end_date,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__book__get_supported_formats();

  external void wire__crate__api__storage__get_today_reading_stats(
    NativePortType port_,
  );

  external void wire__crate__api__storage__import_bookmarks(
    NativePortType port_,
    JSAny bookmarks,
  );

  external void wire__crate__api__search__index_chapter_content(
    NativePortType port_,
    String book_id,
    int chapter_id,
    String chapter_title,
    String content,
  );

  external void wire__crate__api__search__init_search_engine(
    NativePortType port_,
  );

  external void wire__crate__api__storage__init_storage(
    NativePortType port_,
    String data_dir,
  );

  external void wire__crate__api__book__paginate_all_content(
    NativePortType port_,
    String file_path,
    int chapter_index,
    JSAny config,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__epub__paginate_epub_rich_content(
    JSAny paragraphs,
    int chapter_index,
    JSAny config,
  );

  external void wire__crate__api__book__parse_book(
    NativePortType port_,
    String file_path,
  );

  external void wire__crate__api__epub__parse_epub_chapter_rich(
    NativePortType port_,
    String file_path,
    int chapter_index,
  );

  external void wire__crate__api__file__read_file_chunk(
    NativePortType port_,
    String file_path,
    JSAny start_pos,
    JSAny chunk_size,
  );

  external void wire__crate__api__storage__record_reading_session(
    NativePortType port_,
    JSAny session,
  );

  external void wire__crate__api__storage__remove_category_from_book(
    NativePortType port_,
    String book_id,
    String category_id,
  );

  external void wire__crate__api__storage__restore_database(
    NativePortType port_,
    String backup_path,
  );

  external void wire__crate__api__storage__save_book(
    NativePortType port_,
    JSAny book,
  );

  external void wire__crate__api__storage__save_category(
    NativePortType port_,
    JSAny category,
  );

  external void wire__crate__api__storage__save_chapters(
    NativePortType port_,
    String book_id,
    JSAny chapters,
  );

  external void wire__crate__api__storage__save_layout_cache(
    NativePortType port_,
    JSAny cache,
    JSAny key,
  );

  external void wire__crate__api__storage__save_reading_progress(
    NativePortType port_,
    JSAny progress,
  );

  external void wire__crate__api__storage__search_books(
    NativePortType port_,
    String keyword,
  );

  external void wire__crate__api__search__search_in_book(
    NativePortType port_,
    String book_id,
    String query,
    int limit,
  );

  external void wire__crate__api__storage__set_categories_for_book(
    NativePortType port_,
    String book_id,
    JSAny category_ids,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__bilingual__simple_bilingual_align(
    String chinese_content,
    String english_content,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__cover__supports_cover_extraction(String file_path);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__book__supports_format(String format);

  external void wire__crate__api__storage__sync_bookmarks(
    NativePortType port_,
    JSAny local_bookmarks,
    JSAny remote_bookmarks,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__test_connection();

  external void wire__crate__api__typeset__typeset_text(
    NativePortType port_,
    String content,
    JSAny config,
  );

  external void wire__crate__api__storage__update_book_pin(
    NativePortType port_,
    String book_id,
    bool is_pinned,
  );

  external void wire__crate__api__storage__update_book_status(
    NativePortType port_,
    String book_id,
    int status,
  );

  external void wire__crate__api__storage__update_daily_stats(
    NativePortType port_,
    JSAny stats,
  );

  external void wire__crate__api__storage__update_note(
    NativePortType port_,
    JSAny note,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPageStreamer(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPageStreamer(
    int ptr,
  );
}
