// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/bilingual.dart';
import 'api/core.dart';
import 'api/cover.dart';
import 'api/epub.dart';
import 'api/incremental.dart';
import 'api/search.dart';
import 'api/security.dart';
import 'api/storage.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'ffi/error.dart';
import 'ffi/types.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'storage/models.dart';
import 'stream/page_stream.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApiResultPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApiResultBilingualAlignmentPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultBilingualAlignmentPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApiResultBookMetadataPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultBookMetadataPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApiResultCacheStatsPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultCacheStatsPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApiResultDbDailyReadingStatsPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultDbDailyReadingStatsPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApiResultDbGlobalStatsPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultDbGlobalStatsPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApiResultDbNotePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultDbNotePtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApiResultEpubMetadataPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultEpubMetadataPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApiResultLocalBookInfoPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultLocalBookInfoPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApiResultNoteStatsPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultNoteStatsPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApiResultOptionDbBookCategoryPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbBookCategoryPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApiResultOptionDbBookRecordPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbBookRecordPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApiResultOptionDbBookmarkPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbBookmarkPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApiResultOptionDbChapterPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbChapterPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApiResultOptionDbLayoutCachePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbLayoutCachePtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApiResultOptionDbReadingProgressPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbReadingProgressPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApiResultParseResultPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultParseResultPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApiResultRichChapterContentPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultRichChapterContentPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApiResultStringPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultStringPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApiResultVecDbBookCategoryPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbBookCategoryPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApiResultVecDbBookRecordPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbBookRecordPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApiResultVecDbBookmarkPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbBookmarkPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApiResultVecDbChapterPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbChapterPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApiResultVecDbDailyReadingStatsPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbDailyReadingStatsPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApiResultVecDbNotePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbNotePtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApiResultVecDbReadingSessionPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbReadingSessionPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApiResultVecPageContentPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecPageContentPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApiResultVecRichParagraphPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecRichParagraphPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApiResultVecSearchResultPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecSearchResultPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApiResultI32Ptr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResulti32Ptr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApiResultI64Ptr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResulti64Ptr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApiResultUsizePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultusizePtr;

  @protected
  ApiResult
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResult(
    dynamic raw,
  );

  @protected
  ApiResultBilingualAlignment
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultBilingualAlignment(
    dynamic raw,
  );

  @protected
  ApiResultBookMetadata
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultBookMetadata(
    dynamic raw,
  );

  @protected
  ApiResultCacheStats
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultCacheStats(
    dynamic raw,
  );

  @protected
  ApiResultDbDailyReadingStats
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultDbDailyReadingStats(
    dynamic raw,
  );

  @protected
  ApiResultDbGlobalStats
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultDbGlobalStats(
    dynamic raw,
  );

  @protected
  ApiResultDbNote
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultDbNote(
    dynamic raw,
  );

  @protected
  ApiResultEpubMetadata
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultEpubMetadata(
    dynamic raw,
  );

  @protected
  ApiResultLocalBookInfo
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultLocalBookInfo(
    dynamic raw,
  );

  @protected
  ApiResultNoteStats
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultNoteStats(
    dynamic raw,
  );

  @protected
  ApiResultOptionDbBookCategory
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbBookCategory(
    dynamic raw,
  );

  @protected
  ApiResultOptionDbBookRecord
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbBookRecord(
    dynamic raw,
  );

  @protected
  ApiResultOptionDbBookmark
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbBookmark(
    dynamic raw,
  );

  @protected
  ApiResultOptionDbChapter
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbChapter(
    dynamic raw,
  );

  @protected
  ApiResultOptionDbLayoutCache
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbLayoutCache(
    dynamic raw,
  );

  @protected
  ApiResultOptionDbReadingProgress
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbReadingProgress(
    dynamic raw,
  );

  @protected
  ApiResultParseResult
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultParseResult(
    dynamic raw,
  );

  @protected
  ApiResultRichChapterContent
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultRichChapterContent(
    dynamic raw,
  );

  @protected
  ApiResultString
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultString(
    dynamic raw,
  );

  @protected
  ApiResultVecDbBookCategory
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbBookCategory(
    dynamic raw,
  );

  @protected
  ApiResultVecDbBookRecord
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbBookRecord(
    dynamic raw,
  );

  @protected
  ApiResultVecDbBookmark
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbBookmark(
    dynamic raw,
  );

  @protected
  ApiResultVecDbChapter
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbChapter(
    dynamic raw,
  );

  @protected
  ApiResultVecDbDailyReadingStats
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbDailyReadingStats(
    dynamic raw,
  );

  @protected
  ApiResultVecDbNote
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbNote(
    dynamic raw,
  );

  @protected
  ApiResultVecDbReadingSession
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbReadingSession(
    dynamic raw,
  );

  @protected
  ApiResultVecPageContent
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecPageContent(
    dynamic raw,
  );

  @protected
  ApiResultVecRichParagraph
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecRichParagraph(
    dynamic raw,
  );

  @protected
  ApiResultVecSearchResult
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecSearchResult(
    dynamic raw,
  );

  @protected
  ApiResultI32
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResulti32(
    dynamic raw,
  );

  @protected
  ApiResultI64
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResulti64(
    dynamic raw,
  );

  @protected
  ApiResultUsize
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultusize(
    dynamic raw,
  );

  @protected
  DateTime dco_decode_Chrono_Utc(dynamic raw);

  @protected
  ApiResult
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResult(
    dynamic raw,
  );

  @protected
  ApiResultBilingualAlignment
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultBilingualAlignment(
    dynamic raw,
  );

  @protected
  ApiResultBookMetadata
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultBookMetadata(
    dynamic raw,
  );

  @protected
  ApiResultCacheStats
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultCacheStats(
    dynamic raw,
  );

  @protected
  ApiResultDbDailyReadingStats
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultDbDailyReadingStats(
    dynamic raw,
  );

  @protected
  ApiResultDbGlobalStats
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultDbGlobalStats(
    dynamic raw,
  );

  @protected
  ApiResultDbNote
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultDbNote(
    dynamic raw,
  );

  @protected
  ApiResultEpubMetadata
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultEpubMetadata(
    dynamic raw,
  );

  @protected
  ApiResultLocalBookInfo
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultLocalBookInfo(
    dynamic raw,
  );

  @protected
  ApiResultNoteStats
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultNoteStats(
    dynamic raw,
  );

  @protected
  ApiResultOptionDbBookCategory
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbBookCategory(
    dynamic raw,
  );

  @protected
  ApiResultOptionDbBookRecord
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbBookRecord(
    dynamic raw,
  );

  @protected
  ApiResultOptionDbBookmark
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbBookmark(
    dynamic raw,
  );

  @protected
  ApiResultOptionDbChapter
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbChapter(
    dynamic raw,
  );

  @protected
  ApiResultOptionDbLayoutCache
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbLayoutCache(
    dynamic raw,
  );

  @protected
  ApiResultOptionDbReadingProgress
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbReadingProgress(
    dynamic raw,
  );

  @protected
  ApiResultParseResult
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultParseResult(
    dynamic raw,
  );

  @protected
  ApiResultRichChapterContent
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultRichChapterContent(
    dynamic raw,
  );

  @protected
  ApiResultString
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultString(
    dynamic raw,
  );

  @protected
  ApiResultVecDbBookCategory
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbBookCategory(
    dynamic raw,
  );

  @protected
  ApiResultVecDbBookRecord
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbBookRecord(
    dynamic raw,
  );

  @protected
  ApiResultVecDbBookmark
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbBookmark(
    dynamic raw,
  );

  @protected
  ApiResultVecDbChapter
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbChapter(
    dynamic raw,
  );

  @protected
  ApiResultVecDbDailyReadingStats
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbDailyReadingStats(
    dynamic raw,
  );

  @protected
  ApiResultVecDbNote
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbNote(
    dynamic raw,
  );

  @protected
  ApiResultVecDbReadingSession
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbReadingSession(
    dynamic raw,
  );

  @protected
  ApiResultVecPageContent
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecPageContent(
    dynamic raw,
  );

  @protected
  ApiResultVecRichParagraph
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecRichParagraph(
    dynamic raw,
  );

  @protected
  ApiResultVecSearchResult
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecSearchResult(
    dynamic raw,
  );

  @protected
  ApiResultI32
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResulti32(
    dynamic raw,
  );

  @protected
  ApiResultI64
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResulti64(
    dynamic raw,
  );

  @protected
  ApiResultUsize
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultusize(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AlignedSegment dco_decode_aligned_segment(dynamic raw);

  @protected
  BilingualAlignment dco_decode_bilingual_alignment(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DateTime dco_decode_box_autoadd_Chrono_Utc(dynamic raw);

  @protected
  DbBookCategory dco_decode_box_autoadd_db_book_category(dynamic raw);

  @protected
  DbBookRecord dco_decode_box_autoadd_db_book_record(dynamic raw);

  @protected
  DbBookmark dco_decode_box_autoadd_db_bookmark(dynamic raw);

  @protected
  DbDailyReadingStats dco_decode_box_autoadd_db_daily_reading_stats(
    dynamic raw,
  );

  @protected
  DbLayoutCache dco_decode_box_autoadd_db_layout_cache(dynamic raw);

  @protected
  DbNote dco_decode_box_autoadd_db_note(dynamic raw);

  @protected
  DbNoteType dco_decode_box_autoadd_db_note_type(dynamic raw);

  @protected
  DbReadingProgress dco_decode_box_autoadd_db_reading_progress(dynamic raw);

  @protected
  DbReadingSession dco_decode_box_autoadd_db_reading_session(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  LayoutCacheKey dco_decode_box_autoadd_layout_cache_key(dynamic raw);

  @protected
  TypesetConfig dco_decode_box_autoadd_typeset_config(dynamic raw);

  @protected
  DbBookCategory dco_decode_db_book_category(dynamic raw);

  @protected
  DbBookFormat dco_decode_db_book_format(dynamic raw);

  @protected
  DbBookRecord dco_decode_db_book_record(dynamic raw);

  @protected
  DbBookStatus dco_decode_db_book_status(dynamic raw);

  @protected
  DbBookmark dco_decode_db_bookmark(dynamic raw);

  @protected
  DbChapter dco_decode_db_chapter(dynamic raw);

  @protected
  DbDailyReadingStats dco_decode_db_daily_reading_stats(dynamic raw);

  @protected
  DbLayoutCache dco_decode_db_layout_cache(dynamic raw);

  @protected
  DbNote dco_decode_db_note(dynamic raw);

  @protected
  DbNoteType dco_decode_db_note_type(dynamic raw);

  @protected
  DbReadingProgress dco_decode_db_reading_progress(dynamic raw);

  @protected
  DbReadingSession dco_decode_db_reading_session(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  LanguageType dco_decode_language_type(dynamic raw);

  @protected
  LayoutCacheKey dco_decode_layout_cache_key(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AlignedSegment> dco_decode_list_aligned_segment(dynamic raw);

  @protected
  List<DbBookmark> dco_decode_list_db_bookmark(dynamic raw);

  @protected
  List<DbChapter> dco_decode_list_db_chapter(dynamic raw);

  @protected
  List<PageContent> dco_decode_list_page_content(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(PlatformInt64, PlatformInt64)> dco_decode_list_record_i_64_i_64(
    dynamic raw,
  );

  @protected
  List<(BigInt, BigInt)> dco_decode_list_record_usize_usize(dynamic raw);

  @protected
  List<RichParagraph> dco_decode_list_rich_paragraph(dynamic raw);

  @protected
  List<RichTextSpan> dco_decode_list_rich_text_span(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  DateTime? dco_decode_opt_box_autoadd_Chrono_Utc(dynamic raw);

  @protected
  DbNoteType? dco_decode_opt_box_autoadd_db_note_type(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  PageContent dco_decode_page_content(dynamic raw);

  @protected
  PageStreamer dco_decode_page_streamer(dynamic raw);

  @protected
  ParserError dco_decode_parser_error(dynamic raw);

  @protected
  (PlatformInt64, PlatformInt64) dco_decode_record_i_64_i_64(dynamic raw);

  @protected
  (BigInt, BigInt) dco_decode_record_usize_usize(dynamic raw);

  @protected
  RichParagraph dco_decode_rich_paragraph(dynamic raw);

  @protected
  RichTextSpan dco_decode_rich_text_span(dynamic raw);

  @protected
  TypesetConfig dco_decode_typeset_config(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  ApiResult
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResult(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultBilingualAlignment
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultBilingualAlignment(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultBookMetadata
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultBookMetadata(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultCacheStats
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultCacheStats(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultDbDailyReadingStats
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultDbDailyReadingStats(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultDbGlobalStats
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultDbGlobalStats(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultDbNote
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultDbNote(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultEpubMetadata
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultEpubMetadata(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultLocalBookInfo
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultLocalBookInfo(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultNoteStats
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultNoteStats(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultOptionDbBookCategory
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbBookCategory(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultOptionDbBookRecord
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbBookRecord(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultOptionDbBookmark
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbBookmark(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultOptionDbChapter
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbChapter(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultOptionDbLayoutCache
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbLayoutCache(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultOptionDbReadingProgress
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbReadingProgress(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultParseResult
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultParseResult(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultRichChapterContent
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultRichChapterContent(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultString
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultString(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultVecDbBookCategory
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbBookCategory(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultVecDbBookRecord
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbBookRecord(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultVecDbBookmark
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbBookmark(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultVecDbChapter
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbChapter(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultVecDbDailyReadingStats
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbDailyReadingStats(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultVecDbNote
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbNote(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultVecDbReadingSession
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbReadingSession(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultVecPageContent
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecPageContent(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultVecRichParagraph
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecRichParagraph(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultVecSearchResult
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecSearchResult(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultI32
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResulti32(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultI64
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResulti64(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultUsize
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultusize(
    SseDeserializer deserializer,
  );

  @protected
  DateTime sse_decode_Chrono_Utc(SseDeserializer deserializer);

  @protected
  ApiResult
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResult(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultBilingualAlignment
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultBilingualAlignment(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultBookMetadata
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultBookMetadata(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultCacheStats
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultCacheStats(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultDbDailyReadingStats
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultDbDailyReadingStats(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultDbGlobalStats
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultDbGlobalStats(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultDbNote
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultDbNote(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultEpubMetadata
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultEpubMetadata(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultLocalBookInfo
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultLocalBookInfo(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultNoteStats
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultNoteStats(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultOptionDbBookCategory
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbBookCategory(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultOptionDbBookRecord
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbBookRecord(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultOptionDbBookmark
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbBookmark(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultOptionDbChapter
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbChapter(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultOptionDbLayoutCache
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbLayoutCache(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultOptionDbReadingProgress
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbReadingProgress(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultParseResult
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultParseResult(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultRichChapterContent
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultRichChapterContent(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultString
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultString(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultVecDbBookCategory
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbBookCategory(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultVecDbBookRecord
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbBookRecord(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultVecDbBookmark
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbBookmark(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultVecDbChapter
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbChapter(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultVecDbDailyReadingStats
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbDailyReadingStats(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultVecDbNote
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbNote(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultVecDbReadingSession
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbReadingSession(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultVecPageContent
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecPageContent(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultVecRichParagraph
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecRichParagraph(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultVecSearchResult
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecSearchResult(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultI32
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResulti32(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultI64
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResulti64(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultUsize
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultusize(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AlignedSegment sse_decode_aligned_segment(SseDeserializer deserializer);

  @protected
  BilingualAlignment sse_decode_bilingual_alignment(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DateTime sse_decode_box_autoadd_Chrono_Utc(SseDeserializer deserializer);

  @protected
  DbBookCategory sse_decode_box_autoadd_db_book_category(
    SseDeserializer deserializer,
  );

  @protected
  DbBookRecord sse_decode_box_autoadd_db_book_record(
    SseDeserializer deserializer,
  );

  @protected
  DbBookmark sse_decode_box_autoadd_db_bookmark(SseDeserializer deserializer);

  @protected
  DbDailyReadingStats sse_decode_box_autoadd_db_daily_reading_stats(
    SseDeserializer deserializer,
  );

  @protected
  DbLayoutCache sse_decode_box_autoadd_db_layout_cache(
    SseDeserializer deserializer,
  );

  @protected
  DbNote sse_decode_box_autoadd_db_note(SseDeserializer deserializer);

  @protected
  DbNoteType sse_decode_box_autoadd_db_note_type(SseDeserializer deserializer);

  @protected
  DbReadingProgress sse_decode_box_autoadd_db_reading_progress(
    SseDeserializer deserializer,
  );

  @protected
  DbReadingSession sse_decode_box_autoadd_db_reading_session(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  LayoutCacheKey sse_decode_box_autoadd_layout_cache_key(
    SseDeserializer deserializer,
  );

  @protected
  TypesetConfig sse_decode_box_autoadd_typeset_config(
    SseDeserializer deserializer,
  );

  @protected
  DbBookCategory sse_decode_db_book_category(SseDeserializer deserializer);

  @protected
  DbBookFormat sse_decode_db_book_format(SseDeserializer deserializer);

  @protected
  DbBookRecord sse_decode_db_book_record(SseDeserializer deserializer);

  @protected
  DbBookStatus sse_decode_db_book_status(SseDeserializer deserializer);

  @protected
  DbBookmark sse_decode_db_bookmark(SseDeserializer deserializer);

  @protected
  DbChapter sse_decode_db_chapter(SseDeserializer deserializer);

  @protected
  DbDailyReadingStats sse_decode_db_daily_reading_stats(
    SseDeserializer deserializer,
  );

  @protected
  DbLayoutCache sse_decode_db_layout_cache(SseDeserializer deserializer);

  @protected
  DbNote sse_decode_db_note(SseDeserializer deserializer);

  @protected
  DbNoteType sse_decode_db_note_type(SseDeserializer deserializer);

  @protected
  DbReadingProgress sse_decode_db_reading_progress(
    SseDeserializer deserializer,
  );

  @protected
  DbReadingSession sse_decode_db_reading_session(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  LanguageType sse_decode_language_type(SseDeserializer deserializer);

  @protected
  LayoutCacheKey sse_decode_layout_cache_key(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AlignedSegment> sse_decode_list_aligned_segment(
    SseDeserializer deserializer,
  );

  @protected
  List<DbBookmark> sse_decode_list_db_bookmark(SseDeserializer deserializer);

  @protected
  List<DbChapter> sse_decode_list_db_chapter(SseDeserializer deserializer);

  @protected
  List<PageContent> sse_decode_list_page_content(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(PlatformInt64, PlatformInt64)> sse_decode_list_record_i_64_i_64(
    SseDeserializer deserializer,
  );

  @protected
  List<(BigInt, BigInt)> sse_decode_list_record_usize_usize(
    SseDeserializer deserializer,
  );

  @protected
  List<RichParagraph> sse_decode_list_rich_paragraph(
    SseDeserializer deserializer,
  );

  @protected
  List<RichTextSpan> sse_decode_list_rich_text_span(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  DateTime? sse_decode_opt_box_autoadd_Chrono_Utc(SseDeserializer deserializer);

  @protected
  DbNoteType? sse_decode_opt_box_autoadd_db_note_type(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PageContent sse_decode_page_content(SseDeserializer deserializer);

  @protected
  PageStreamer sse_decode_page_streamer(SseDeserializer deserializer);

  @protected
  ParserError sse_decode_parser_error(SseDeserializer deserializer);

  @protected
  (PlatformInt64, PlatformInt64) sse_decode_record_i_64_i_64(
    SseDeserializer deserializer,
  );

  @protected
  (BigInt, BigInt) sse_decode_record_usize_usize(SseDeserializer deserializer);

  @protected
  RichParagraph sse_decode_rich_paragraph(SseDeserializer deserializer);

  @protected
  RichTextSpan sse_decode_rich_text_span(SseDeserializer deserializer);

  @protected
  TypesetConfig sse_decode_typeset_config(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  int cst_encode_Chrono_Utc(DateTime raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_64(raw.microsecondsSinceEpoch);
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_prim_u_8_strict(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<ffi.Int64> cst_encode_box_autoadd_Chrono_Utc(DateTime raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return wire.cst_new_box_autoadd_Chrono_Utc(cst_encode_Chrono_Utc(raw));
  }

  @protected
  ffi.Pointer<wire_cst_db_book_category>
  cst_encode_box_autoadd_db_book_category(DbBookCategory raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_db_book_category();
    cst_api_fill_to_wire_db_book_category(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_db_book_record> cst_encode_box_autoadd_db_book_record(
    DbBookRecord raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_db_book_record();
    cst_api_fill_to_wire_db_book_record(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_db_bookmark> cst_encode_box_autoadd_db_bookmark(
    DbBookmark raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_db_bookmark();
    cst_api_fill_to_wire_db_bookmark(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_db_daily_reading_stats>
  cst_encode_box_autoadd_db_daily_reading_stats(DbDailyReadingStats raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_db_daily_reading_stats();
    cst_api_fill_to_wire_db_daily_reading_stats(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_db_layout_cache> cst_encode_box_autoadd_db_layout_cache(
    DbLayoutCache raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_db_layout_cache();
    cst_api_fill_to_wire_db_layout_cache(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_db_note> cst_encode_box_autoadd_db_note(DbNote raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_db_note();
    cst_api_fill_to_wire_db_note(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<ffi.Int32> cst_encode_box_autoadd_db_note_type(DbNoteType raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return wire.cst_new_box_autoadd_db_note_type(cst_encode_db_note_type(raw));
  }

  @protected
  ffi.Pointer<wire_cst_db_reading_progress>
  cst_encode_box_autoadd_db_reading_progress(DbReadingProgress raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_db_reading_progress();
    cst_api_fill_to_wire_db_reading_progress(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_db_reading_session>
  cst_encode_box_autoadd_db_reading_session(DbReadingSession raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_db_reading_session();
    cst_api_fill_to_wire_db_reading_session(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<ffi.Int32> cst_encode_box_autoadd_i_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return wire.cst_new_box_autoadd_i_32(cst_encode_i_32(raw));
  }

  @protected
  ffi.Pointer<wire_cst_layout_cache_key>
  cst_encode_box_autoadd_layout_cache_key(LayoutCacheKey raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_layout_cache_key();
    cst_api_fill_to_wire_layout_cache_key(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_typeset_config> cst_encode_box_autoadd_typeset_config(
    TypesetConfig raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_typeset_config();
    cst_api_fill_to_wire_typeset_config(raw, ptr.ref);
    return ptr;
  }

  @protected
  int cst_encode_i_64(PlatformInt64 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toInt();
  }

  @protected
  ffi.Pointer<wire_cst_list_String> cst_encode_list_String(List<String> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_String(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      ans.ref.ptr[i] = cst_encode_String(raw[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_aligned_segment> cst_encode_list_aligned_segment(
    List<AlignedSegment> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_aligned_segment(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_aligned_segment(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_db_bookmark> cst_encode_list_db_bookmark(
    List<DbBookmark> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_db_bookmark(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_db_bookmark(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_db_chapter> cst_encode_list_db_chapter(
    List<DbChapter> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_db_chapter(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_db_chapter(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_page_content> cst_encode_list_page_content(
    List<PageContent> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_page_content(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_page_content(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_list_prim_u_8_strict(
    Uint8List raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_record_i_64_i_64> cst_encode_list_record_i_64_i_64(
    List<(PlatformInt64, PlatformInt64)> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_record_i_64_i_64(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_record_i_64_i_64(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_record_usize_usize>
  cst_encode_list_record_usize_usize(List<(BigInt, BigInt)> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_record_usize_usize(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_record_usize_usize(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_rich_paragraph> cst_encode_list_rich_paragraph(
    List<RichParagraph> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_rich_paragraph(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_rich_paragraph(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_rich_text_span> cst_encode_list_rich_text_span(
    List<RichTextSpan> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_rich_text_span(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_rich_text_span(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_opt_String(
    String? raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_String(raw);
  }

  @protected
  ffi.Pointer<ffi.Int64> cst_encode_opt_box_autoadd_Chrono_Utc(DateTime? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_Chrono_Utc(raw);
  }

  @protected
  ffi.Pointer<ffi.Int32> cst_encode_opt_box_autoadd_db_note_type(
    DbNoteType? raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_db_note_type(raw);
  }

  @protected
  ffi.Pointer<ffi.Int32> cst_encode_opt_box_autoadd_i_32(int? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_i_32(raw);
  }

  @protected
  int cst_encode_usize(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toSigned(64).toInt();
  }

  @protected
  void cst_api_fill_to_wire_aligned_segment(
    AlignedSegment apiObj,
    wire_cst_aligned_segment wireObj,
  ) {
    wireObj.chinese = cst_encode_String(apiObj.chinese);
    wireObj.english = cst_encode_String(apiObj.english);
    wireObj.similarity_score = cst_encode_f_32(apiObj.similarityScore);
    wireObj.chinese_position = cst_encode_usize(apiObj.chinesePosition);
    wireObj.english_position = cst_encode_usize(apiObj.englishPosition);
  }

  @protected
  void cst_api_fill_to_wire_bilingual_alignment(
    BilingualAlignment apiObj,
    wire_cst_bilingual_alignment wireObj,
  ) {
    wireObj.segments = cst_encode_list_aligned_segment(apiObj.segments);
    wireObj.unmatched_chinese = cst_encode_list_String(apiObj.unmatchedChinese);
    wireObj.unmatched_english = cst_encode_list_String(apiObj.unmatchedEnglish);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_db_book_category(
    DbBookCategory apiObj,
    ffi.Pointer<wire_cst_db_book_category> wireObj,
  ) {
    cst_api_fill_to_wire_db_book_category(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_db_book_record(
    DbBookRecord apiObj,
    ffi.Pointer<wire_cst_db_book_record> wireObj,
  ) {
    cst_api_fill_to_wire_db_book_record(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_db_bookmark(
    DbBookmark apiObj,
    ffi.Pointer<wire_cst_db_bookmark> wireObj,
  ) {
    cst_api_fill_to_wire_db_bookmark(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_db_daily_reading_stats(
    DbDailyReadingStats apiObj,
    ffi.Pointer<wire_cst_db_daily_reading_stats> wireObj,
  ) {
    cst_api_fill_to_wire_db_daily_reading_stats(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_db_layout_cache(
    DbLayoutCache apiObj,
    ffi.Pointer<wire_cst_db_layout_cache> wireObj,
  ) {
    cst_api_fill_to_wire_db_layout_cache(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_db_note(
    DbNote apiObj,
    ffi.Pointer<wire_cst_db_note> wireObj,
  ) {
    cst_api_fill_to_wire_db_note(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_db_reading_progress(
    DbReadingProgress apiObj,
    ffi.Pointer<wire_cst_db_reading_progress> wireObj,
  ) {
    cst_api_fill_to_wire_db_reading_progress(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_db_reading_session(
    DbReadingSession apiObj,
    ffi.Pointer<wire_cst_db_reading_session> wireObj,
  ) {
    cst_api_fill_to_wire_db_reading_session(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_layout_cache_key(
    LayoutCacheKey apiObj,
    ffi.Pointer<wire_cst_layout_cache_key> wireObj,
  ) {
    cst_api_fill_to_wire_layout_cache_key(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_typeset_config(
    TypesetConfig apiObj,
    ffi.Pointer<wire_cst_typeset_config> wireObj,
  ) {
    cst_api_fill_to_wire_typeset_config(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_db_book_category(
    DbBookCategory apiObj,
    wire_cst_db_book_category wireObj,
  ) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.name = cst_encode_String(apiObj.name);
    wireObj.description = cst_encode_opt_String(apiObj.description);
    wireObj.color = cst_encode_String(apiObj.color);
    wireObj.sort_order = cst_encode_i_32(apiObj.sortOrder);
    wireObj.is_system = cst_encode_bool(apiObj.isSystem);
    wireObj.created_at = cst_encode_Chrono_Utc(apiObj.createdAt);
    wireObj.updated_at = cst_encode_Chrono_Utc(apiObj.updatedAt);
  }

  @protected
  void cst_api_fill_to_wire_db_book_record(
    DbBookRecord apiObj,
    wire_cst_db_book_record wireObj,
  ) {
    wireObj.book_id = cst_encode_String(apiObj.bookId);
    wireObj.file_path = cst_encode_String(apiObj.filePath);
    wireObj.file_size = cst_encode_i_64(apiObj.fileSize);
    wireObj.title = cst_encode_String(apiObj.title);
    wireObj.author = cst_encode_String(apiObj.author);
    wireObj.description = cst_encode_opt_String(apiObj.description);
    wireObj.cover_path = cst_encode_opt_String(apiObj.coverPath);
    wireObj.chapter_count = cst_encode_i_32(apiObj.chapterCount);
    wireObj.total_characters = cst_encode_i_64(apiObj.totalCharacters);
    wireObj.format = cst_encode_db_book_format(apiObj.format);
    wireObj.added_at = cst_encode_Chrono_Utc(apiObj.addedAt);
    wireObj.last_opened_at = cst_encode_opt_box_autoadd_Chrono_Utc(
      apiObj.lastOpenedAt,
    );
    wireObj.status = cst_encode_db_book_status(apiObj.status);
    wireObj.is_pinned = cst_encode_bool(apiObj.isPinned);
  }

  @protected
  void cst_api_fill_to_wire_db_bookmark(
    DbBookmark apiObj,
    wire_cst_db_bookmark wireObj,
  ) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.book_id = cst_encode_String(apiObj.bookId);
    wireObj.chapter_index = cst_encode_i_32(apiObj.chapterIndex);
    wireObj.char_offset = cst_encode_i_64(apiObj.charOffset);
    wireObj.title = cst_encode_String(apiObj.title);
    wireObj.created_at = cst_encode_Chrono_Utc(apiObj.createdAt);
  }

  @protected
  void cst_api_fill_to_wire_db_chapter(
    DbChapter apiObj,
    wire_cst_db_chapter wireObj,
  ) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.book_id = cst_encode_String(apiObj.bookId);
    wireObj.title = cst_encode_String(apiObj.title);
    wireObj.content_file = cst_encode_String(apiObj.contentFile);
    wireObj.chapter_index = cst_encode_i_32(apiObj.chapterIndex);
    wireObj.word_count = cst_encode_i_64(apiObj.wordCount);
    wireObj.cached_at = cst_encode_Chrono_Utc(apiObj.cachedAt);
    wireObj.level = cst_encode_i_32(apiObj.level);
  }

  @protected
  void cst_api_fill_to_wire_db_daily_reading_stats(
    DbDailyReadingStats apiObj,
    wire_cst_db_daily_reading_stats wireObj,
  ) {
    wireObj.date = cst_encode_String(apiObj.date);
    wireObj.total_reading_time_seconds = cst_encode_i_64(
      apiObj.totalReadingTimeSeconds,
    );
    wireObj.total_characters_read = cst_encode_i_64(apiObj.totalCharactersRead);
    wireObj.books_read = cst_encode_list_String(apiObj.booksRead);
    wireObj.session_count = cst_encode_i_32(apiObj.sessionCount);
    wireObj.chapters_read = cst_encode_i_32(apiObj.chaptersRead);
    wireObj.pages_read = cst_encode_i_32(apiObj.pagesRead);
  }

  @protected
  void cst_api_fill_to_wire_db_layout_cache(
    DbLayoutCache apiObj,
    wire_cst_db_layout_cache wireObj,
  ) {
    wireObj.page_offsets = cst_encode_list_record_i_64_i_64(apiObj.pageOffsets);
    wireObj.total_pages = cst_encode_i_32(apiObj.totalPages);
    wireObj.created_at = cst_encode_Chrono_Utc(apiObj.createdAt);
  }

  @protected
  void cst_api_fill_to_wire_db_note(DbNote apiObj, wire_cst_db_note wireObj) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.book_id = cst_encode_String(apiObj.bookId);
    wireObj.chapter_index = cst_encode_i_32(apiObj.chapterIndex);
    wireObj.char_offset = cst_encode_i_64(apiObj.charOffset);
    wireObj.length = cst_encode_i_64(apiObj.length);
    wireObj.note_type = cst_encode_db_note_type(apiObj.noteType);
    wireObj.content = cst_encode_String(apiObj.content);
    wireObj.selected_text = cst_encode_opt_String(apiObj.selectedText);
    wireObj.highlight_color = cst_encode_opt_box_autoadd_i_32(
      apiObj.highlightColor,
    );
    wireObj.created_at = cst_encode_Chrono_Utc(apiObj.createdAt);
    wireObj.updated_at = cst_encode_Chrono_Utc(apiObj.updatedAt);
  }

  @protected
  void cst_api_fill_to_wire_db_reading_progress(
    DbReadingProgress apiObj,
    wire_cst_db_reading_progress wireObj,
  ) {
    wireObj.book_id = cst_encode_String(apiObj.bookId);
    wireObj.chapter_index = cst_encode_i_32(apiObj.chapterIndex);
    wireObj.char_offset = cst_encode_i_64(apiObj.charOffset);
    wireObj.page_index = cst_encode_i_32(apiObj.pageIndex);
    wireObj.total_pages = cst_encode_i_32(apiObj.totalPages);
    wireObj.progress = cst_encode_f_32(apiObj.progress);
    wireObj.reading_time_seconds = cst_encode_i_64(apiObj.readingTimeSeconds);
    wireObj.last_read_at = cst_encode_Chrono_Utc(apiObj.lastReadAt);
    wireObj.is_completed = cst_encode_bool(apiObj.isCompleted);
  }

  @protected
  void cst_api_fill_to_wire_db_reading_session(
    DbReadingSession apiObj,
    wire_cst_db_reading_session wireObj,
  ) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.book_id = cst_encode_String(apiObj.bookId);
    wireObj.chapter_index = cst_encode_i_32(apiObj.chapterIndex);
    wireObj.start_char_offset = cst_encode_i_64(apiObj.startCharOffset);
    wireObj.end_char_offset = cst_encode_i_64(apiObj.endCharOffset);
    wireObj.started_at = cst_encode_Chrono_Utc(apiObj.startedAt);
    wireObj.ended_at = cst_encode_Chrono_Utc(apiObj.endedAt);
    wireObj.duration_seconds = cst_encode_i_64(apiObj.durationSeconds);
    wireObj.characters_read = cst_encode_i_64(apiObj.charactersRead);
  }

  @protected
  void cst_api_fill_to_wire_layout_cache_key(
    LayoutCacheKey apiObj,
    wire_cst_layout_cache_key wireObj,
  ) {
    wireObj.book_id = cst_encode_String(apiObj.bookId);
    wireObj.chapter_index = cst_encode_i_32(apiObj.chapterIndex);
    wireObj.config_hash = cst_encode_String(apiObj.configHash);
  }

  @protected
  void cst_api_fill_to_wire_page_content(
    PageContent apiObj,
    wire_cst_page_content wireObj,
  ) {
    wireObj.chapter_index = cst_encode_i_32(apiObj.chapterIndex);
    wireObj.page_index = cst_encode_i_32(apiObj.pageIndex);
    wireObj.content = cst_encode_String(apiObj.content);
    wireObj.is_last_page = cst_encode_bool(apiObj.isLastPage);
  }

  @protected
  void cst_api_fill_to_wire_page_streamer(
    PageStreamer apiObj,
    wire_cst_page_streamer wireObj,
  ) {
    wireObj.lines = cst_encode_list_String(apiObj.lines);
    wireObj.current_page = cst_encode_usize(apiObj.currentPage);
    wireObj.lines_per_page = cst_encode_usize(apiObj.linesPerPage);
    wireObj.line_offsets = cst_encode_list_record_usize_usize(
      apiObj.lineOffsets,
    );
  }

  @protected
  void cst_api_fill_to_wire_parser_error(
    ParserError apiObj,
    wire_cst_parser_error wireObj,
  ) {
    if (apiObj is ParserError_FileNotFound) {
      var pre_path = cst_encode_String(apiObj.path);
      var pre_reason = cst_encode_String(apiObj.reason);
      wireObj.tag = 0;
      wireObj.kind.FileNotFound.path = pre_path;
      wireObj.kind.FileNotFound.reason = pre_reason;
      return;
    }
    if (apiObj is ParserError_FileReadError) {
      var pre_path = cst_encode_String(apiObj.path);
      var pre_message = cst_encode_String(apiObj.message);
      wireObj.tag = 1;
      wireObj.kind.FileReadError.path = pre_path;
      wireObj.kind.FileReadError.message = pre_message;
      return;
    }
    if (apiObj is ParserError_EncodingError) {
      var pre_field0 = cst_encode_String(apiObj.field0);
      wireObj.tag = 2;
      wireObj.kind.EncodingError.field0 = pre_field0;
      return;
    }
    if (apiObj is ParserError_EpubParseError) {
      var pre_field0 = cst_encode_String(apiObj.field0);
      wireObj.tag = 3;
      wireObj.kind.EpubParseError.field0 = pre_field0;
      return;
    }
    if (apiObj is ParserError_PdfParseError) {
      var pre_field0 = cst_encode_String(apiObj.field0);
      wireObj.tag = 4;
      wireObj.kind.PdfParseError.field0 = pre_field0;
      return;
    }
    if (apiObj is ParserError_TxtParseError) {
      var pre_field0 = cst_encode_String(apiObj.field0);
      wireObj.tag = 5;
      wireObj.kind.TxtParseError.field0 = pre_field0;
      return;
    }
    if (apiObj is ParserError_ChapterExtractError) {
      var pre_field0 = cst_encode_String(apiObj.field0);
      wireObj.tag = 6;
      wireObj.kind.ChapterExtractError.field0 = pre_field0;
      return;
    }
    if (apiObj is ParserError_Typeset) {
      var pre_field0 = cst_encode_String(apiObj.field0);
      wireObj.tag = 7;
      wireObj.kind.Typeset.field0 = pre_field0;
      return;
    }
    if (apiObj is ParserError_StreamError) {
      var pre_field0 = cst_encode_String(apiObj.field0);
      wireObj.tag = 8;
      wireObj.kind.StreamError.field0 = pre_field0;
      return;
    }
    if (apiObj is ParserError_UnsupportedFormat) {
      var pre_field0 = cst_encode_String(apiObj.field0);
      wireObj.tag = 9;
      wireObj.kind.UnsupportedFormat.field0 = pre_field0;
      return;
    }
    if (apiObj is ParserError_FileWriteError) {
      var pre_field0 = cst_encode_String(apiObj.field0);
      wireObj.tag = 10;
      wireObj.kind.FileWriteError.field0 = pre_field0;
      return;
    }
    if (apiObj is ParserError_InternalError) {
      var pre_field0 = cst_encode_String(apiObj.field0);
      wireObj.tag = 11;
      wireObj.kind.InternalError.field0 = pre_field0;
      return;
    }
    if (apiObj is ParserError_ConfigError) {
      var pre_field0 = cst_encode_String(apiObj.field0);
      wireObj.tag = 12;
      wireObj.kind.ConfigError.field0 = pre_field0;
      return;
    }
    if (apiObj is ParserError_PageExtractError) {
      var pre_field0 = cst_encode_String(apiObj.field0);
      wireObj.tag = 13;
      wireObj.kind.PageExtractError.field0 = pre_field0;
      return;
    }
    if (apiObj is ParserError_TextExtractError) {
      var pre_field0 = cst_encode_String(apiObj.field0);
      wireObj.tag = 14;
      wireObj.kind.TextExtractError.field0 = pre_field0;
      return;
    }
    if (apiObj is ParserError_Other) {
      var pre_field0 = cst_encode_String(apiObj.field0);
      wireObj.tag = 15;
      wireObj.kind.Other.field0 = pre_field0;
      return;
    }
    if (apiObj is ParserError_SecurityError) {
      var pre_field0 = cst_encode_String(apiObj.field0);
      wireObj.tag = 16;
      wireObj.kind.SecurityError.field0 = pre_field0;
      return;
    }
  }

  @protected
  void cst_api_fill_to_wire_record_i_64_i_64(
    (PlatformInt64, PlatformInt64) apiObj,
    wire_cst_record_i_64_i_64 wireObj,
  ) {
    wireObj.field0 = cst_encode_i_64(apiObj.$1);
    wireObj.field1 = cst_encode_i_64(apiObj.$2);
  }

  @protected
  void cst_api_fill_to_wire_record_usize_usize(
    (BigInt, BigInt) apiObj,
    wire_cst_record_usize_usize wireObj,
  ) {
    wireObj.field0 = cst_encode_usize(apiObj.$1);
    wireObj.field1 = cst_encode_usize(apiObj.$2);
  }

  @protected
  void cst_api_fill_to_wire_rich_paragraph(
    RichParagraph apiObj,
    wire_cst_rich_paragraph wireObj,
  ) {
    wireObj.spans = cst_encode_list_rich_text_span(apiObj.spans);
    wireObj.indent = cst_encode_u_8(apiObj.indent);
    wireObj.is_heading = cst_encode_bool(apiObj.isHeading);
    wireObj.heading_level = cst_encode_u_8(apiObj.headingLevel);
    wireObj.class_name = cst_encode_opt_String(apiObj.className);
  }

  @protected
  void cst_api_fill_to_wire_rich_text_span(
    RichTextSpan apiObj,
    wire_cst_rich_text_span wireObj,
  ) {
    if (apiObj is RichTextSpan_Plain) {
      var pre_text = cst_encode_String(apiObj.text);
      wireObj.tag = 0;
      wireObj.kind.Plain.text = pre_text;
      return;
    }
    if (apiObj is RichTextSpan_Bold) {
      var pre_text = cst_encode_String(apiObj.text);
      wireObj.tag = 1;
      wireObj.kind.Bold.text = pre_text;
      return;
    }
    if (apiObj is RichTextSpan_Italic) {
      var pre_text = cst_encode_String(apiObj.text);
      wireObj.tag = 2;
      wireObj.kind.Italic.text = pre_text;
      return;
    }
    if (apiObj is RichTextSpan_BoldItalic) {
      var pre_text = cst_encode_String(apiObj.text);
      wireObj.tag = 3;
      wireObj.kind.BoldItalic.text = pre_text;
      return;
    }
    if (apiObj is RichTextSpan_Underline) {
      var pre_text = cst_encode_String(apiObj.text);
      wireObj.tag = 4;
      wireObj.kind.Underline.text = pre_text;
      return;
    }
    if (apiObj is RichTextSpan_Strikethrough) {
      var pre_text = cst_encode_String(apiObj.text);
      wireObj.tag = 5;
      wireObj.kind.Strikethrough.text = pre_text;
      return;
    }
    if (apiObj is RichTextSpan_Code) {
      var pre_text = cst_encode_String(apiObj.text);
      wireObj.tag = 6;
      wireObj.kind.Code.text = pre_text;
      return;
    }
    if (apiObj is RichTextSpan_Link) {
      var pre_text = cst_encode_String(apiObj.text);
      var pre_url = cst_encode_String(apiObj.url);
      wireObj.tag = 7;
      wireObj.kind.Link.text = pre_text;
      wireObj.kind.Link.url = pre_url;
      return;
    }
  }

  @protected
  void cst_api_fill_to_wire_typeset_config(
    TypesetConfig apiObj,
    wire_cst_typeset_config wireObj,
  ) {
    wireObj.page_width = cst_encode_i_32(apiObj.pageWidth);
    wireObj.page_height = cst_encode_i_32(apiObj.pageHeight);
    wireObj.font_size = cst_encode_i_32(apiObj.fontSize);
    wireObj.line_spacing = cst_encode_f_32(apiObj.lineSpacing);
    wireObj.letter_spacing = cst_encode_f_32(apiObj.letterSpacing);
    wireObj.paragraph_spacing = cst_encode_f_32(apiObj.paragraphSpacing);
    wireObj.first_line_indent = cst_encode_u_8(apiObj.firstLineIndent);
    wireObj.language = cst_encode_language_type(apiObj.language);
    wireObj.enable_hyphenation = cst_encode_bool(apiObj.enableHyphenation);
    wireObj.hyphenation_language = cst_encode_opt_String(
      apiObj.hyphenationLanguage,
    );
  }

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResult(
    ApiResult raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultBilingualAlignment(
    ApiResultBilingualAlignment raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultBookMetadata(
    ApiResultBookMetadata raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultCacheStats(
    ApiResultCacheStats raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultDbDailyReadingStats(
    ApiResultDbDailyReadingStats raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultDbGlobalStats(
    ApiResultDbGlobalStats raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultDbNote(
    ApiResultDbNote raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultEpubMetadata(
    ApiResultEpubMetadata raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultLocalBookInfo(
    ApiResultLocalBookInfo raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultNoteStats(
    ApiResultNoteStats raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbBookCategory(
    ApiResultOptionDbBookCategory raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbBookRecord(
    ApiResultOptionDbBookRecord raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbBookmark(
    ApiResultOptionDbBookmark raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbChapter(
    ApiResultOptionDbChapter raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbLayoutCache(
    ApiResultOptionDbLayoutCache raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbReadingProgress(
    ApiResultOptionDbReadingProgress raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultParseResult(
    ApiResultParseResult raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultRichChapterContent(
    ApiResultRichChapterContent raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultString(
    ApiResultString raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbBookCategory(
    ApiResultVecDbBookCategory raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbBookRecord(
    ApiResultVecDbBookRecord raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbBookmark(
    ApiResultVecDbBookmark raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbChapter(
    ApiResultVecDbChapter raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbDailyReadingStats(
    ApiResultVecDbDailyReadingStats raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbNote(
    ApiResultVecDbNote raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbReadingSession(
    ApiResultVecDbReadingSession raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecPageContent(
    ApiResultVecPageContent raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecRichParagraph(
    ApiResultVecRichParagraph raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecSearchResult(
    ApiResultVecSearchResult raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResulti32(
    ApiResultI32 raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResulti64(
    ApiResultI64 raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultusize(
    ApiResultUsize raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResult(
    ApiResult raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultBilingualAlignment(
    ApiResultBilingualAlignment raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultBookMetadata(
    ApiResultBookMetadata raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultCacheStats(
    ApiResultCacheStats raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultDbDailyReadingStats(
    ApiResultDbDailyReadingStats raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultDbGlobalStats(
    ApiResultDbGlobalStats raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultDbNote(
    ApiResultDbNote raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultEpubMetadata(
    ApiResultEpubMetadata raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultLocalBookInfo(
    ApiResultLocalBookInfo raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultNoteStats(
    ApiResultNoteStats raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbBookCategory(
    ApiResultOptionDbBookCategory raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbBookRecord(
    ApiResultOptionDbBookRecord raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbBookmark(
    ApiResultOptionDbBookmark raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbChapter(
    ApiResultOptionDbChapter raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbLayoutCache(
    ApiResultOptionDbLayoutCache raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbReadingProgress(
    ApiResultOptionDbReadingProgress raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultParseResult(
    ApiResultParseResult raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultRichChapterContent(
    ApiResultRichChapterContent raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultString(
    ApiResultString raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbBookCategory(
    ApiResultVecDbBookCategory raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbBookRecord(
    ApiResultVecDbBookRecord raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbBookmark(
    ApiResultVecDbBookmark raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbChapter(
    ApiResultVecDbChapter raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbDailyReadingStats(
    ApiResultVecDbDailyReadingStats raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbNote(
    ApiResultVecDbNote raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbReadingSession(
    ApiResultVecDbReadingSession raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecPageContent(
    ApiResultVecPageContent raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecRichParagraph(
    ApiResultVecRichParagraph raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecSearchResult(
    ApiResultVecSearchResult raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResulti32(
    ApiResultI32 raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResulti64(
    ApiResultI64 raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultusize(
    ApiResultUsize raw,
  );

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  int cst_encode_db_book_format(DbBookFormat raw);

  @protected
  int cst_encode_db_book_status(DbBookStatus raw);

  @protected
  int cst_encode_db_note_type(DbNoteType raw);

  @protected
  double cst_encode_f_32(double raw);

  @protected
  int cst_encode_i_32(int raw);

  @protected
  int cst_encode_language_type(LanguageType raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResult(
    ApiResult self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultBilingualAlignment(
    ApiResultBilingualAlignment self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultBookMetadata(
    ApiResultBookMetadata self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultCacheStats(
    ApiResultCacheStats self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultDbDailyReadingStats(
    ApiResultDbDailyReadingStats self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultDbGlobalStats(
    ApiResultDbGlobalStats self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultDbNote(
    ApiResultDbNote self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultEpubMetadata(
    ApiResultEpubMetadata self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultLocalBookInfo(
    ApiResultLocalBookInfo self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultNoteStats(
    ApiResultNoteStats self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbBookCategory(
    ApiResultOptionDbBookCategory self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbBookRecord(
    ApiResultOptionDbBookRecord self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbBookmark(
    ApiResultOptionDbBookmark self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbChapter(
    ApiResultOptionDbChapter self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbLayoutCache(
    ApiResultOptionDbLayoutCache self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbReadingProgress(
    ApiResultOptionDbReadingProgress self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultParseResult(
    ApiResultParseResult self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultRichChapterContent(
    ApiResultRichChapterContent self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultString(
    ApiResultString self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbBookCategory(
    ApiResultVecDbBookCategory self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbBookRecord(
    ApiResultVecDbBookRecord self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbBookmark(
    ApiResultVecDbBookmark self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbChapter(
    ApiResultVecDbChapter self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbDailyReadingStats(
    ApiResultVecDbDailyReadingStats self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbNote(
    ApiResultVecDbNote self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbReadingSession(
    ApiResultVecDbReadingSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecPageContent(
    ApiResultVecPageContent self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecRichParagraph(
    ApiResultVecRichParagraph self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecSearchResult(
    ApiResultVecSearchResult self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResulti32(
    ApiResultI32 self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResulti64(
    ApiResultI64 self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultusize(
    ApiResultUsize self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Chrono_Utc(DateTime self, SseSerializer serializer);

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResult(
    ApiResult self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultBilingualAlignment(
    ApiResultBilingualAlignment self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultBookMetadata(
    ApiResultBookMetadata self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultCacheStats(
    ApiResultCacheStats self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultDbDailyReadingStats(
    ApiResultDbDailyReadingStats self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultDbGlobalStats(
    ApiResultDbGlobalStats self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultDbNote(
    ApiResultDbNote self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultEpubMetadata(
    ApiResultEpubMetadata self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultLocalBookInfo(
    ApiResultLocalBookInfo self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultNoteStats(
    ApiResultNoteStats self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbBookCategory(
    ApiResultOptionDbBookCategory self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbBookRecord(
    ApiResultOptionDbBookRecord self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbBookmark(
    ApiResultOptionDbBookmark self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbChapter(
    ApiResultOptionDbChapter self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbLayoutCache(
    ApiResultOptionDbLayoutCache self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultOptionDbReadingProgress(
    ApiResultOptionDbReadingProgress self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultParseResult(
    ApiResultParseResult self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultRichChapterContent(
    ApiResultRichChapterContent self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultString(
    ApiResultString self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbBookCategory(
    ApiResultVecDbBookCategory self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbBookRecord(
    ApiResultVecDbBookRecord self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbBookmark(
    ApiResultVecDbBookmark self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbChapter(
    ApiResultVecDbChapter self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbDailyReadingStats(
    ApiResultVecDbDailyReadingStats self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbNote(
    ApiResultVecDbNote self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecDbReadingSession(
    ApiResultVecDbReadingSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecPageContent(
    ApiResultVecPageContent self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecRichParagraph(
    ApiResultVecRichParagraph self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultVecSearchResult(
    ApiResultVecSearchResult self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResulti32(
    ApiResultI32 self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResulti64(
    ApiResultI64 self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultusize(
    ApiResultUsize self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_aligned_segment(
    AlignedSegment self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bilingual_alignment(
    BilingualAlignment self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_Chrono_Utc(
    DateTime self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_db_book_category(
    DbBookCategory self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_db_book_record(
    DbBookRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_db_bookmark(
    DbBookmark self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_db_daily_reading_stats(
    DbDailyReadingStats self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_db_layout_cache(
    DbLayoutCache self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_db_note(DbNote self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_db_note_type(
    DbNoteType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_db_reading_progress(
    DbReadingProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_db_reading_session(
    DbReadingSession self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_layout_cache_key(
    LayoutCacheKey self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_typeset_config(
    TypesetConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_db_book_category(
    DbBookCategory self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_db_book_format(DbBookFormat self, SseSerializer serializer);

  @protected
  void sse_encode_db_book_record(DbBookRecord self, SseSerializer serializer);

  @protected
  void sse_encode_db_book_status(DbBookStatus self, SseSerializer serializer);

  @protected
  void sse_encode_db_bookmark(DbBookmark self, SseSerializer serializer);

  @protected
  void sse_encode_db_chapter(DbChapter self, SseSerializer serializer);

  @protected
  void sse_encode_db_daily_reading_stats(
    DbDailyReadingStats self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_db_layout_cache(DbLayoutCache self, SseSerializer serializer);

  @protected
  void sse_encode_db_note(DbNote self, SseSerializer serializer);

  @protected
  void sse_encode_db_note_type(DbNoteType self, SseSerializer serializer);

  @protected
  void sse_encode_db_reading_progress(
    DbReadingProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_db_reading_session(
    DbReadingSession self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_language_type(LanguageType self, SseSerializer serializer);

  @protected
  void sse_encode_layout_cache_key(
    LayoutCacheKey self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_aligned_segment(
    List<AlignedSegment> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_db_bookmark(
    List<DbBookmark> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_db_chapter(
    List<DbChapter> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_page_content(
    List<PageContent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_i_64_i_64(
    List<(PlatformInt64, PlatformInt64)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_usize_usize(
    List<(BigInt, BigInt)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rich_paragraph(
    List<RichParagraph> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rich_text_span(
    List<RichTextSpan> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_Chrono_Utc(
    DateTime? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_db_note_type(
    DbNoteType? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_page_content(PageContent self, SseSerializer serializer);

  @protected
  void sse_encode_page_streamer(PageStreamer self, SseSerializer serializer);

  @protected
  void sse_encode_parser_error(ParserError self, SseSerializer serializer);

  @protected
  void sse_encode_record_i_64_i_64(
    (PlatformInt64, PlatformInt64) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_usize_usize(
    (BigInt, BigInt) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rich_paragraph(RichParagraph self, SseSerializer serializer);

  @protected
  void sse_encode_rich_text_span(RichTextSpan self, SseSerializer serializer);

  @protected
  void sse_encode_typeset_config(TypesetConfig self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import

/// generated by flutter_rust_bridge
class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  RustLibWire.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  void store_dart_post_cobject(DartPostCObjectFnType ptr) {
    return _store_dart_post_cobject(ptr);
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
        'store_dart_post_cobject',
      );
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  int dummy_method_to_enforce_bundling() {
    return _dummy_method_to_enforce_bundling();
  }

  late final _dummy_method_to_enforce_bundlingPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function()>>(
        'dummy_method_to_enforce_bundling',
      );
  late final _dummy_method_to_enforce_bundling =
      _dummy_method_to_enforce_bundlingPtr.asFunction<int Function()>();
}

typedef DartPort = ffi.Int64;
typedef DartDartPort = int;
typedef DartPostCObjectFnTypeFunction =
    ffi.Bool Function(DartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartDartPostCObjectFnTypeFunction =
    bool Function(DartDartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartPostCObjectFnType =
    ffi.Pointer<ffi.NativeFunction<DartPostCObjectFnTypeFunction>>;

const int EPUB_MIN_LINES_PER_PAGE = 10;

const int EPUB_MIN_CHARS_PER_PAGE = 500;

const int MIN_CHAPTER_LENGTH = 10;

const int PDF_CHARS_PER_PAGE = 500;

const int SEARCH_CHUNK_SIZE = 500;

const int MIN_CHARS_PER_LINE = 10;
