// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'ffi/types.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'stream/page_stream.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -819712932;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_zephyr_reader',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Bookmark crateApiAddBookmark({
    required String bookId,
    required int chapterId,
    required int pageIndex,
    required String title,
    String? note,
  });

  BigInt crateApiClearBookmarks({required String bookId});

  bool crateApiClearReadingProgress({required String bookId});

  PageStreamer crateApiCreatePageStreamer({
    required String content,
    required TypesetConfig config,
  });

  List<Bookmark> crateApiGetAllBookmarks();

  List<ReadingProgress> crateApiGetAllReadingProgress();

  List<Bookmark> crateApiGetBookmarks({required String bookId});

  ApiResultI64 crateApiGetFileSize({required String filePath});

  ReadingProgress? crateApiGetReadingProgress({required String bookId});

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiInitApp();

  List<PageContent> crateApiPaginateAllContent({
    required String content,
    required int chapterId,
    required TypesetConfig config,
  });

  ApiResultParseResult crateApiParseEpubFile({required String filePath});

  ApiResultParseResult crateApiParseTxtFile({required String filePath});

  ApiResultString crateApiReadFileChunk({
    required String filePath,
    required PlatformInt64 startPos,
    required PlatformInt64 chunkSize,
  });

  bool crateApiRemoveBookmark({
    required String bookId,
    required String bookmarkId,
  });

  String crateApiTestConnection();

  ApiResultString crateApiTypesetText({
    required String content,
    required String language,
    required TypesetConfig config,
  });

  ReadingProgress crateApiUpdateReadingProgress({
    required String bookId,
    required int chapterId,
    required int pageIndex,
    required int totalPages,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ApiResultParseResult;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ApiResultParseResult;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApiResultParseResultPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ApiResultString;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ApiResultString;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApiResultStringPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ApiResultI64;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ApiResultI64;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ApiResultI64Ptr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Bookmark crateApiAddBookmark({
    required String bookId,
    required int chapterId,
    required int pageIndex,
    required String title,
    String? note,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 = cst_encode_String(bookId);
          var arg1 = cst_encode_i_32(chapterId);
          var arg2 = cst_encode_i_32(pageIndex);
          var arg3 = cst_encode_String(title);
          var arg4 = cst_encode_opt_String(note);
          return wire.wire__crate__api__add_bookmark(
            arg0,
            arg1,
            arg2,
            arg3,
            arg4,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_bookmark,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAddBookmarkConstMeta,
        argValues: [bookId, chapterId, pageIndex, title, note],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAddBookmarkConstMeta => const TaskConstMeta(
    debugName: "add_bookmark",
    argNames: ["bookId", "chapterId", "pageIndex", "title", "note"],
  );

  @override
  BigInt crateApiClearBookmarks({required String bookId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 = cst_encode_String(bookId);
          return wire.wire__crate__api__clear_bookmarks(arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_usize,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClearBookmarksConstMeta,
        argValues: [bookId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClearBookmarksConstMeta =>
      const TaskConstMeta(debugName: "clear_bookmarks", argNames: ["bookId"]);

  @override
  bool crateApiClearReadingProgress({required String bookId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 = cst_encode_String(bookId);
          return wire.wire__crate__api__clear_reading_progress(arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClearReadingProgressConstMeta,
        argValues: [bookId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClearReadingProgressConstMeta =>
      const TaskConstMeta(
        debugName: "clear_reading_progress",
        argNames: ["bookId"],
      );

  @override
  PageStreamer crateApiCreatePageStreamer({
    required String content,
    required TypesetConfig config,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 = cst_encode_String(content);
          var arg1 = cst_encode_box_autoadd_typeset_config(config);
          return wire.wire__crate__api__create_page_streamer(arg0, arg1);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_page_streamer,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCreatePageStreamerConstMeta,
        argValues: [content, config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCreatePageStreamerConstMeta => const TaskConstMeta(
    debugName: "create_page_streamer",
    argNames: ["content", "config"],
  );

  @override
  List<Bookmark> crateApiGetAllBookmarks() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          return wire.wire__crate__api__get_all_bookmarks();
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_bookmark,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetAllBookmarksConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetAllBookmarksConstMeta =>
      const TaskConstMeta(debugName: "get_all_bookmarks", argNames: []);

  @override
  List<ReadingProgress> crateApiGetAllReadingProgress() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          return wire.wire__crate__api__get_all_reading_progress();
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_reading_progress,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetAllReadingProgressConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetAllReadingProgressConstMeta =>
      const TaskConstMeta(debugName: "get_all_reading_progress", argNames: []);

  @override
  List<Bookmark> crateApiGetBookmarks({required String bookId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 = cst_encode_String(bookId);
          return wire.wire__crate__api__get_bookmarks(arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_bookmark,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetBookmarksConstMeta,
        argValues: [bookId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetBookmarksConstMeta =>
      const TaskConstMeta(debugName: "get_bookmarks", argNames: ["bookId"]);

  @override
  ApiResultI64 crateApiGetFileSize({required String filePath}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 = cst_encode_String(filePath);
          return wire.wire__crate__api__get_file_size(arg0);
        },
        codec: DcoCodec(
          decodeSuccessData:
              dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResulti64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetFileSizeConstMeta,
        argValues: [filePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetFileSizeConstMeta =>
      const TaskConstMeta(debugName: "get_file_size", argNames: ["filePath"]);

  @override
  ReadingProgress? crateApiGetReadingProgress({required String bookId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 = cst_encode_String(bookId);
          return wire.wire__crate__api__get_reading_progress(arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_opt_box_autoadd_reading_progress,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetReadingProgressConstMeta,
        argValues: [bookId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetReadingProgressConstMeta => const TaskConstMeta(
    debugName: "get_reading_progress",
    argNames: ["bookId"],
  );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 = cst_encode_String(name);
          return wire.wire__crate__api__simple__greet(arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          return wire.wire__crate__api__init_app(port_);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  List<PageContent> crateApiPaginateAllContent({
    required String content,
    required int chapterId,
    required TypesetConfig config,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 = cst_encode_String(content);
          var arg1 = cst_encode_i_32(chapterId);
          var arg2 = cst_encode_box_autoadd_typeset_config(config);
          return wire.wire__crate__api__paginate_all_content(arg0, arg1, arg2);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_page_content,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPaginateAllContentConstMeta,
        argValues: [content, chapterId, config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPaginateAllContentConstMeta => const TaskConstMeta(
    debugName: "paginate_all_content",
    argNames: ["content", "chapterId", "config"],
  );

  @override
  ApiResultParseResult crateApiParseEpubFile({required String filePath}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 = cst_encode_String(filePath);
          return wire.wire__crate__api__parse_epub_file(arg0);
        },
        codec: DcoCodec(
          decodeSuccessData:
              dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultParseResult,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiParseEpubFileConstMeta,
        argValues: [filePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiParseEpubFileConstMeta =>
      const TaskConstMeta(debugName: "parse_epub_file", argNames: ["filePath"]);

  @override
  ApiResultParseResult crateApiParseTxtFile({required String filePath}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 = cst_encode_String(filePath);
          return wire.wire__crate__api__parse_txt_file(arg0);
        },
        codec: DcoCodec(
          decodeSuccessData:
              dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultParseResult,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiParseTxtFileConstMeta,
        argValues: [filePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiParseTxtFileConstMeta =>
      const TaskConstMeta(debugName: "parse_txt_file", argNames: ["filePath"]);

  @override
  ApiResultString crateApiReadFileChunk({
    required String filePath,
    required PlatformInt64 startPos,
    required PlatformInt64 chunkSize,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 = cst_encode_String(filePath);
          var arg1 = cst_encode_i_64(startPos);
          var arg2 = cst_encode_i_64(chunkSize);
          return wire.wire__crate__api__read_file_chunk(arg0, arg1, arg2);
        },
        codec: DcoCodec(
          decodeSuccessData:
              dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultString,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiReadFileChunkConstMeta,
        argValues: [filePath, startPos, chunkSize],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReadFileChunkConstMeta => const TaskConstMeta(
    debugName: "read_file_chunk",
    argNames: ["filePath", "startPos", "chunkSize"],
  );

  @override
  bool crateApiRemoveBookmark({
    required String bookId,
    required String bookmarkId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 = cst_encode_String(bookId);
          var arg1 = cst_encode_String(bookmarkId);
          return wire.wire__crate__api__remove_bookmark(arg0, arg1);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRemoveBookmarkConstMeta,
        argValues: [bookId, bookmarkId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRemoveBookmarkConstMeta => const TaskConstMeta(
    debugName: "remove_bookmark",
    argNames: ["bookId", "bookmarkId"],
  );

  @override
  String crateApiTestConnection() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          return wire.wire__crate__api__test_connection();
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTestConnectionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTestConnectionConstMeta =>
      const TaskConstMeta(debugName: "test_connection", argNames: []);

  @override
  ApiResultString crateApiTypesetText({
    required String content,
    required String language,
    required TypesetConfig config,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 = cst_encode_String(content);
          var arg1 = cst_encode_String(language);
          var arg2 = cst_encode_box_autoadd_typeset_config(config);
          return wire.wire__crate__api__typeset_text(arg0, arg1, arg2);
        },
        codec: DcoCodec(
          decodeSuccessData:
              dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultString,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTypesetTextConstMeta,
        argValues: [content, language, config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTypesetTextConstMeta => const TaskConstMeta(
    debugName: "typeset_text",
    argNames: ["content", "language", "config"],
  );

  @override
  ReadingProgress crateApiUpdateReadingProgress({
    required String bookId,
    required int chapterId,
    required int pageIndex,
    required int totalPages,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 = cst_encode_String(bookId);
          var arg1 = cst_encode_i_32(chapterId);
          var arg2 = cst_encode_i_32(pageIndex);
          var arg3 = cst_encode_i_32(totalPages);
          return wire.wire__crate__api__update_reading_progress(
            arg0,
            arg1,
            arg2,
            arg3,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_reading_progress,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiUpdateReadingProgressConstMeta,
        argValues: [bookId, chapterId, pageIndex, totalPages],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUpdateReadingProgressConstMeta =>
      const TaskConstMeta(
        debugName: "update_reading_progress",
        argNames: ["bookId", "chapterId", "pageIndex", "totalPages"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ApiResultParseResult => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultParseResult;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ApiResultParseResult => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultParseResult;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ApiResultString => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultString;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ApiResultString => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultString;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ApiResultI64 => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResulti64;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ApiResultI64 => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResulti64;

  @protected
  ApiResultParseResult
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultParseResult(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ApiResultParseResultImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ApiResultString
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultString(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ApiResultStringImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ApiResultI64
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResulti64(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ApiResultI64Impl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ApiResultParseResult
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultParseResult(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ApiResultParseResultImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ApiResultString
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultString(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ApiResultStringImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ApiResultI64
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResulti64(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ApiResultI64Impl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  Bookmark dco_decode_bookmark(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return Bookmark(
      bookmarkId: dco_decode_String(arr[0]),
      bookId: dco_decode_String(arr[1]),
      chapterId: dco_decode_i_32(arr[2]),
      pageIndex: dco_decode_i_32(arr[3]),
      title: dco_decode_String(arr[4]),
      createdTimestamp: dco_decode_i_64(arr[5]),
      note: dco_decode_opt_String(arr[6]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ReadingProgress dco_decode_box_autoadd_reading_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_reading_progress(raw);
  }

  @protected
  TypesetConfig dco_decode_box_autoadd_typeset_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_typeset_config(raw);
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  LanguageType dco_decode_language_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LanguageType.values[raw as int];
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<Bookmark> dco_decode_list_bookmark(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_bookmark).toList();
  }

  @protected
  List<PageContent> dco_decode_list_page_content(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_page_content).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<ReadingProgress> dco_decode_list_reading_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_reading_progress).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  ReadingProgress? dco_decode_opt_box_autoadd_reading_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_reading_progress(raw);
  }

  @protected
  PageContent dco_decode_page_content(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return PageContent(
      chapterId: dco_decode_i_32(arr[0]),
      pageIndex: dco_decode_i_32(arr[1]),
      content: dco_decode_String(arr[2]),
      isLastPage: dco_decode_bool(arr[3]),
    );
  }

  @protected
  PageStreamer dco_decode_page_streamer(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return PageStreamer(
      lines: dco_decode_list_String(arr[0]),
      currentPage: dco_decode_usize(arr[1]),
      linesPerPage: dco_decode_usize(arr[2]),
    );
  }

  @protected
  ReadingProgress dco_decode_reading_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ReadingProgress(
      chapterId: dco_decode_i_32(arr[0]),
      pageIndex: dco_decode_i_32(arr[1]),
      totalPages: dco_decode_i_32(arr[2]),
      progress: dco_decode_f_32(arr[3]),
      readingTimeSeconds: dco_decode_i_64(arr[4]),
      lastReadTimestamp: dco_decode_i_64(arr[5]),
    );
  }

  @protected
  TypesetConfig dco_decode_typeset_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return TypesetConfig(
      pageWidth: dco_decode_i_32(arr[0]),
      pageHeight: dco_decode_i_32(arr[1]),
      fontSize: dco_decode_i_32(arr[2]),
      lineSpacing: dco_decode_f_32(arr[3]),
      letterSpacing: dco_decode_f_32(arr[4]),
      paragraphSpacing: dco_decode_f_32(arr[5]),
      firstLineIndent: dco_decode_u_8(arr[6]),
      language: dco_decode_language_type(arr[7]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  ApiResultParseResult
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultParseResult(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ApiResultParseResultImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ApiResultString
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultString(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ApiResultStringImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ApiResultI64
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResulti64(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ApiResultI64Impl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ApiResultParseResult
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultParseResult(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ApiResultParseResultImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ApiResultString
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultString(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ApiResultStringImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ApiResultI64
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResulti64(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ApiResultI64Impl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  Bookmark sse_decode_bookmark(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_bookmarkId = sse_decode_String(deserializer);
    var var_bookId = sse_decode_String(deserializer);
    var var_chapterId = sse_decode_i_32(deserializer);
    var var_pageIndex = sse_decode_i_32(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_createdTimestamp = sse_decode_i_64(deserializer);
    var var_note = sse_decode_opt_String(deserializer);
    return Bookmark(
      bookmarkId: var_bookmarkId,
      bookId: var_bookId,
      chapterId: var_chapterId,
      pageIndex: var_pageIndex,
      title: var_title,
      createdTimestamp: var_createdTimestamp,
      note: var_note,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ReadingProgress sse_decode_box_autoadd_reading_progress(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_reading_progress(deserializer));
  }

  @protected
  TypesetConfig sse_decode_box_autoadd_typeset_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_typeset_config(deserializer));
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  LanguageType sse_decode_language_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return LanguageType.values[inner];
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<Bookmark> sse_decode_list_bookmark(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Bookmark>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bookmark(deserializer));
    }
    return ans_;
  }

  @protected
  List<PageContent> sse_decode_list_page_content(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PageContent>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_page_content(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<ReadingProgress> sse_decode_list_reading_progress(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ReadingProgress>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_reading_progress(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ReadingProgress? sse_decode_opt_box_autoadd_reading_progress(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_reading_progress(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PageContent sse_decode_page_content(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_chapterId = sse_decode_i_32(deserializer);
    var var_pageIndex = sse_decode_i_32(deserializer);
    var var_content = sse_decode_String(deserializer);
    var var_isLastPage = sse_decode_bool(deserializer);
    return PageContent(
      chapterId: var_chapterId,
      pageIndex: var_pageIndex,
      content: var_content,
      isLastPage: var_isLastPage,
    );
  }

  @protected
  PageStreamer sse_decode_page_streamer(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_lines = sse_decode_list_String(deserializer);
    var var_currentPage = sse_decode_usize(deserializer);
    var var_linesPerPage = sse_decode_usize(deserializer);
    return PageStreamer(
      lines: var_lines,
      currentPage: var_currentPage,
      linesPerPage: var_linesPerPage,
    );
  }

  @protected
  ReadingProgress sse_decode_reading_progress(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_chapterId = sse_decode_i_32(deserializer);
    var var_pageIndex = sse_decode_i_32(deserializer);
    var var_totalPages = sse_decode_i_32(deserializer);
    var var_progress = sse_decode_f_32(deserializer);
    var var_readingTimeSeconds = sse_decode_i_64(deserializer);
    var var_lastReadTimestamp = sse_decode_i_64(deserializer);
    return ReadingProgress(
      chapterId: var_chapterId,
      pageIndex: var_pageIndex,
      totalPages: var_totalPages,
      progress: var_progress,
      readingTimeSeconds: var_readingTimeSeconds,
      lastReadTimestamp: var_lastReadTimestamp,
    );
  }

  @protected
  TypesetConfig sse_decode_typeset_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_pageWidth = sse_decode_i_32(deserializer);
    var var_pageHeight = sse_decode_i_32(deserializer);
    var var_fontSize = sse_decode_i_32(deserializer);
    var var_lineSpacing = sse_decode_f_32(deserializer);
    var var_letterSpacing = sse_decode_f_32(deserializer);
    var var_paragraphSpacing = sse_decode_f_32(deserializer);
    var var_firstLineIndent = sse_decode_u_8(deserializer);
    var var_language = sse_decode_language_type(deserializer);
    return TypesetConfig(
      pageWidth: var_pageWidth,
      pageHeight: var_pageHeight,
      fontSize: var_fontSize,
      lineSpacing: var_lineSpacing,
      letterSpacing: var_letterSpacing,
      paragraphSpacing: var_paragraphSpacing,
      firstLineIndent: var_firstLineIndent,
      language: var_language,
    );
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultParseResult(
    ApiResultParseResult raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    // ignore: invalid_use_of_internal_member
    return (raw as ApiResultParseResultImpl).frbInternalCstEncode(move: true);
  }

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultString(
    ApiResultString raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    // ignore: invalid_use_of_internal_member
    return (raw as ApiResultStringImpl).frbInternalCstEncode(move: true);
  }

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResulti64(
    ApiResultI64 raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    // ignore: invalid_use_of_internal_member
    return (raw as ApiResultI64Impl).frbInternalCstEncode(move: true);
  }

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultParseResult(
    ApiResultParseResult raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    // ignore: invalid_use_of_internal_member
    return (raw as ApiResultParseResultImpl).frbInternalCstEncode();
  }

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultString(
    ApiResultString raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    // ignore: invalid_use_of_internal_member
    return (raw as ApiResultStringImpl).frbInternalCstEncode();
  }

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResulti64(
    ApiResultI64 raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    // ignore: invalid_use_of_internal_member
    return (raw as ApiResultI64Impl).frbInternalCstEncode();
  }

  @protected
  bool cst_encode_bool(bool raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  double cst_encode_f_32(double raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_i_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_language_type(LanguageType raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_32(raw.index);
  }

  @protected
  int cst_encode_u_8(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void cst_encode_unit(void raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultParseResult(
    ApiResultParseResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ApiResultParseResultImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultString(
    ApiResultString self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ApiResultStringImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResulti64(
    ApiResultI64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ApiResultI64Impl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultParseResult(
    ApiResultParseResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ApiResultParseResultImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResultString(
    ApiResultString self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ApiResultStringImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiResulti64(
    ApiResultI64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ApiResultI64Impl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bookmark(Bookmark self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.bookmarkId, serializer);
    sse_encode_String(self.bookId, serializer);
    sse_encode_i_32(self.chapterId, serializer);
    sse_encode_i_32(self.pageIndex, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_i_64(self.createdTimestamp, serializer);
    sse_encode_opt_String(self.note, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_reading_progress(
    ReadingProgress self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_reading_progress(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_typeset_config(
    TypesetConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_typeset_config(self, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_language_type(LanguageType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_bookmark(List<Bookmark> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bookmark(item, serializer);
    }
  }

  @protected
  void sse_encode_list_page_content(
    List<PageContent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_page_content(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_reading_progress(
    List<ReadingProgress> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_reading_progress(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_reading_progress(
    ReadingProgress? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_reading_progress(self, serializer);
    }
  }

  @protected
  void sse_encode_page_content(PageContent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.chapterId, serializer);
    sse_encode_i_32(self.pageIndex, serializer);
    sse_encode_String(self.content, serializer);
    sse_encode_bool(self.isLastPage, serializer);
  }

  @protected
  void sse_encode_page_streamer(PageStreamer self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_String(self.lines, serializer);
    sse_encode_usize(self.currentPage, serializer);
    sse_encode_usize(self.linesPerPage, serializer);
  }

  @protected
  void sse_encode_reading_progress(
    ReadingProgress self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.chapterId, serializer);
    sse_encode_i_32(self.pageIndex, serializer);
    sse_encode_i_32(self.totalPages, serializer);
    sse_encode_f_32(self.progress, serializer);
    sse_encode_i_64(self.readingTimeSeconds, serializer);
    sse_encode_i_64(self.lastReadTimestamp, serializer);
  }

  @protected
  void sse_encode_typeset_config(TypesetConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.pageWidth, serializer);
    sse_encode_i_32(self.pageHeight, serializer);
    sse_encode_i_32(self.fontSize, serializer);
    sse_encode_f_32(self.lineSpacing, serializer);
    sse_encode_f_32(self.letterSpacing, serializer);
    sse_encode_f_32(self.paragraphSpacing, serializer);
    sse_encode_u_8(self.firstLineIndent, serializer);
    sse_encode_language_type(self.language, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class ApiResultI64Impl extends RustOpaque implements ApiResultI64 {
  // Not to be used by end users
  ApiResultI64Impl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ApiResultI64Impl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_ApiResultI64,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_ApiResultI64,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_ApiResultI64Ptr,
  );
}

@sealed
class ApiResultParseResultImpl extends RustOpaque
    implements ApiResultParseResult {
  // Not to be used by end users
  ApiResultParseResultImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ApiResultParseResultImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_increment_strong_count_ApiResultParseResult,
    rustArcDecrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_ApiResultParseResult,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_ApiResultParseResultPtr,
  );
}

@sealed
class ApiResultStringImpl extends RustOpaque implements ApiResultString {
  // Not to be used by end users
  ApiResultStringImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ApiResultStringImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_ApiResultString,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_ApiResultString,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_ApiResultStringPtr,
  );
}
