// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 书籍分类
class DbBookCategory {
  final String id;
  final String name;
  final String color;
  final int sortOrder;
  final bool isSystem;
  final DateTime createdAt;
  final DateTime updatedAt;

  const DbBookCategory({
    required this.id,
    required this.name,
    required this.color,
    required this.sortOrder,
    required this.isSystem,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      color.hashCode ^
      sortOrder.hashCode ^
      isSystem.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbBookCategory &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          color == other.color &&
          sortOrder == other.sortOrder &&
          isSystem == other.isSystem &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

/// 书籍格式
enum DbBookFormat { txt, epub, pdf }

/// 书籍元数据
class DbBookRecord {
  final String bookId;
  final String filePath;
  final PlatformInt64 fileSize;
  final String title;
  final String author;
  final String? description;
  final String? coverPath;
  final int chapterCount;
  final PlatformInt64 totalCharacters;
  final DbBookFormat format;
  final DateTime addedAt;
  final DateTime? lastOpenedAt;
  final DbBookStatus status;
  final bool isPinned;
  final List<String> categoryIds;
  final DateTime? lastReadAt;

  const DbBookRecord({
    required this.bookId,
    required this.filePath,
    required this.fileSize,
    required this.title,
    required this.author,
    this.description,
    this.coverPath,
    required this.chapterCount,
    required this.totalCharacters,
    required this.format,
    required this.addedAt,
    this.lastOpenedAt,
    required this.status,
    required this.isPinned,
    required this.categoryIds,
    this.lastReadAt,
  });

  @override
  int get hashCode =>
      bookId.hashCode ^
      filePath.hashCode ^
      fileSize.hashCode ^
      title.hashCode ^
      author.hashCode ^
      description.hashCode ^
      coverPath.hashCode ^
      chapterCount.hashCode ^
      totalCharacters.hashCode ^
      format.hashCode ^
      addedAt.hashCode ^
      lastOpenedAt.hashCode ^
      status.hashCode ^
      isPinned.hashCode ^
      categoryIds.hashCode ^
      lastReadAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbBookRecord &&
          runtimeType == other.runtimeType &&
          bookId == other.bookId &&
          filePath == other.filePath &&
          fileSize == other.fileSize &&
          title == other.title &&
          author == other.author &&
          description == other.description &&
          coverPath == other.coverPath &&
          chapterCount == other.chapterCount &&
          totalCharacters == other.totalCharacters &&
          format == other.format &&
          addedAt == other.addedAt &&
          lastOpenedAt == other.lastOpenedAt &&
          status == other.status &&
          isPinned == other.isPinned &&
          categoryIds == other.categoryIds &&
          lastReadAt == other.lastReadAt;
}

/// 书籍阅读状态
enum DbBookStatus { reading, completed, dropped, planned }

/// 书签（数据库模型）
///
/// 纯位置标记，仅记录阅读位置，不包含内容注释
class DbBookmark {
  final String id;
  final String bookId;
  final int chapterIndex;
  final PlatformInt64 charOffset;
  final String title;
  final DateTime createdAt;

  const DbBookmark({
    required this.id,
    required this.bookId,
    required this.chapterIndex,
    required this.charOffset,
    required this.title,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      bookId.hashCode ^
      chapterIndex.hashCode ^
      charOffset.hashCode ^
      title.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbBookmark &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          bookId == other.bookId &&
          chapterIndex == other.chapterIndex &&
          charOffset == other.charOffset &&
          title == other.title &&
          createdAt == other.createdAt;
}

/// 章节元数据
class DbChapter {
  final String id;
  final String bookId;
  final String title;
  final String contentFile;
  final int chapterIndex;
  final PlatformInt64 wordCount;
  final DateTime cachedAt;

  const DbChapter({
    required this.id,
    required this.bookId,
    required this.title,
    required this.contentFile,
    required this.chapterIndex,
    required this.wordCount,
    required this.cachedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      bookId.hashCode ^
      title.hashCode ^
      contentFile.hashCode ^
      chapterIndex.hashCode ^
      wordCount.hashCode ^
      cachedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbChapter &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          bookId == other.bookId &&
          title == other.title &&
          contentFile == other.contentFile &&
          chapterIndex == other.chapterIndex &&
          wordCount == other.wordCount &&
          cachedAt == other.cachedAt;
}

/// 每日阅读统计
class DbDailyReadingStats {
  final String date;
  final PlatformInt64 totalReadingTimeSeconds;
  final PlatformInt64 totalCharactersRead;
  final List<String> booksRead;
  final int sessionCount;
  final int chaptersRead;
  final int pagesRead;

  const DbDailyReadingStats({
    required this.date,
    required this.totalReadingTimeSeconds,
    required this.totalCharactersRead,
    required this.booksRead,
    required this.sessionCount,
    required this.chaptersRead,
    required this.pagesRead,
  });

  @override
  int get hashCode =>
      date.hashCode ^
      totalReadingTimeSeconds.hashCode ^
      totalCharactersRead.hashCode ^
      booksRead.hashCode ^
      sessionCount.hashCode ^
      chaptersRead.hashCode ^
      pagesRead.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbDailyReadingStats &&
          runtimeType == other.runtimeType &&
          date == other.date &&
          totalReadingTimeSeconds == other.totalReadingTimeSeconds &&
          totalCharactersRead == other.totalCharactersRead &&
          booksRead == other.booksRead &&
          sessionCount == other.sessionCount &&
          chaptersRead == other.chaptersRead &&
          pagesRead == other.pagesRead;
}

/// 全局阅读统计汇总
class DbGlobalStats {
  final PlatformInt64 totalReadingTimeSeconds;
  final PlatformInt64 totalCharactersRead;
  final int booksReadCount;
  final int booksCompletedCount;
  final int consecutiveReadingDays;
  final PlatformInt64 todayReadingTimeSeconds;
  final PlatformInt64 todayCharactersRead;
  final double averageReadingSpeed;

  const DbGlobalStats({
    required this.totalReadingTimeSeconds,
    required this.totalCharactersRead,
    required this.booksReadCount,
    required this.booksCompletedCount,
    required this.consecutiveReadingDays,
    required this.todayReadingTimeSeconds,
    required this.todayCharactersRead,
    required this.averageReadingSpeed,
  });

  @override
  int get hashCode =>
      totalReadingTimeSeconds.hashCode ^
      totalCharactersRead.hashCode ^
      booksReadCount.hashCode ^
      booksCompletedCount.hashCode ^
      consecutiveReadingDays.hashCode ^
      todayReadingTimeSeconds.hashCode ^
      todayCharactersRead.hashCode ^
      averageReadingSpeed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbGlobalStats &&
          runtimeType == other.runtimeType &&
          totalReadingTimeSeconds == other.totalReadingTimeSeconds &&
          totalCharactersRead == other.totalCharactersRead &&
          booksReadCount == other.booksReadCount &&
          booksCompletedCount == other.booksCompletedCount &&
          consecutiveReadingDays == other.consecutiveReadingDays &&
          todayReadingTimeSeconds == other.todayReadingTimeSeconds &&
          todayCharactersRead == other.todayCharactersRead &&
          averageReadingSpeed == other.averageReadingSpeed;
}

/// 排版缓存值
class DbLayoutCache {
  final List<(PlatformInt64, PlatformInt64)> pageOffsets;
  final int totalPages;
  final DateTime createdAt;

  const DbLayoutCache({
    required this.pageOffsets,
    required this.totalPages,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      pageOffsets.hashCode ^ totalPages.hashCode ^ createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbLayoutCache &&
          runtimeType == other.runtimeType &&
          pageOffsets == other.pageOffsets &&
          totalPages == other.totalPages &&
          createdAt == other.createdAt;
}

/// 笔记类型
enum DbNoteType { highlight, annotation }

/// 阅读进度（数据库模型）
class DbReadingProgress {
  final String bookId;
  final int chapterIndex;
  final PlatformInt64 charOffset;
  final int pageIndex;
  final int totalPages;
  final double progress;
  final PlatformInt64 readingTimeSeconds;
  final DateTime lastReadAt;
  final bool isCompleted;

  const DbReadingProgress({
    required this.bookId,
    required this.chapterIndex,
    required this.charOffset,
    required this.pageIndex,
    required this.totalPages,
    required this.progress,
    required this.readingTimeSeconds,
    required this.lastReadAt,
    required this.isCompleted,
  });

  @override
  int get hashCode =>
      bookId.hashCode ^
      chapterIndex.hashCode ^
      charOffset.hashCode ^
      pageIndex.hashCode ^
      totalPages.hashCode ^
      progress.hashCode ^
      readingTimeSeconds.hashCode ^
      lastReadAt.hashCode ^
      isCompleted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbReadingProgress &&
          runtimeType == other.runtimeType &&
          bookId == other.bookId &&
          chapterIndex == other.chapterIndex &&
          charOffset == other.charOffset &&
          pageIndex == other.pageIndex &&
          totalPages == other.totalPages &&
          progress == other.progress &&
          readingTimeSeconds == other.readingTimeSeconds &&
          lastReadAt == other.lastReadAt &&
          isCompleted == other.isCompleted;
}

/// 阅读会话记录
class DbReadingSession {
  final String id;
  final String bookId;
  final int chapterIndex;
  final PlatformInt64 startCharOffset;
  final PlatformInt64 endCharOffset;
  final DateTime startedAt;
  final DateTime endedAt;
  final PlatformInt64 durationSeconds;
  final PlatformInt64 charactersRead;

  const DbReadingSession({
    required this.id,
    required this.bookId,
    required this.chapterIndex,
    required this.startCharOffset,
    required this.endCharOffset,
    required this.startedAt,
    required this.endedAt,
    required this.durationSeconds,
    required this.charactersRead,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      bookId.hashCode ^
      chapterIndex.hashCode ^
      startCharOffset.hashCode ^
      endCharOffset.hashCode ^
      startedAt.hashCode ^
      endedAt.hashCode ^
      durationSeconds.hashCode ^
      charactersRead.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbReadingSession &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          bookId == other.bookId &&
          chapterIndex == other.chapterIndex &&
          startCharOffset == other.startCharOffset &&
          endCharOffset == other.endCharOffset &&
          startedAt == other.startedAt &&
          endedAt == other.endedAt &&
          durationSeconds == other.durationSeconds &&
          charactersRead == other.charactersRead;
}

/// 同步状态记录
class DbSyncRecord {
  final String id;
  final String bookId;
  final String dataType;
  final String dataId;
  final int localVersion;
  final int? remoteVersion;
  final DbSyncStatus status;
  final DateTime modifiedAt;
  final String? etag;

  const DbSyncRecord({
    required this.id,
    required this.bookId,
    required this.dataType,
    required this.dataId,
    required this.localVersion,
    this.remoteVersion,
    required this.status,
    required this.modifiedAt,
    this.etag,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      bookId.hashCode ^
      dataType.hashCode ^
      dataId.hashCode ^
      localVersion.hashCode ^
      remoteVersion.hashCode ^
      status.hashCode ^
      modifiedAt.hashCode ^
      etag.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbSyncRecord &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          bookId == other.bookId &&
          dataType == other.dataType &&
          dataId == other.dataId &&
          localVersion == other.localVersion &&
          remoteVersion == other.remoteVersion &&
          status == other.status &&
          modifiedAt == other.modifiedAt &&
          etag == other.etag;
}

/// 同步状态
enum DbSyncStatus { synced, pendingUpload, pendingDownload, conflict }
