// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../ffi/types.dart';
import '../frb_generated.dart';
import '../stream/page_stream.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_parser_for_file`, `get_registry`, `init_parser_registry`

/// 解析书籍文件
///
/// 支持 TXT、EPUB、PDF 格式，自动识别文件类型并提取章节信息。
///
/// # 参数
/// * `file_path` - 文件的完整路径
///
/// # 返回值
/// * `Ok(ParseResult)` - 解析成功，包含书籍元数据和章节列表
/// * `Err(ParserError)` - 解析失败（文件不存在、格式不支持等）
ApiResultParseResult parseBook({required String filePath}) =>
    RustLib.instance.api.crateApiCoreParseBook(filePath: filePath);

/// 提取书籍元数据
///
/// 快速提取书籍的标题、作者、章节数等信息，不解析完整内容。
///
/// # 参数
/// * `file_path` - 文件的完整路径
///
/// # 返回值
/// * `Ok(BookMetadata)` - 元数据提取成功
/// * `Err(ParserError)` - 提取失败
ApiResultBookMetadata extractMetadata({required String filePath}) =>
    RustLib.instance.api.crateApiCoreExtractMetadata(filePath: filePath);

/// 提取指定章节的内容
///
/// 根据章节 ID 提取完整的章节文本内容。
///
/// # 参数
/// * `file_path` - 文件的完整路径
/// * `chapter_id` - 章节 ID（从 0 开始）
///
/// # 返回值
/// * `Ok(String)` - 章节内容
/// * `Err(ParserError)` - 提取失败（章节不存在等）
ApiResultString extractChapter({
  required String filePath,
  required int chapterId,
}) => RustLib.instance.api.crateApiCoreExtractChapter(
  filePath: filePath,
  chapterId: chapterId,
);

/// 获取 TXT 章节内容（带排版和分页）
///
/// 专门用于 TXT 文件，提取指定章节并进行排版处理后分页。
/// 与 `extract_chapter` 不同，此函数返回分页后的页面列表。
///
/// # 参数
/// * `file_path` - TXT 文件的完整路径
/// * `chapter_index` - 章节索引（从 0 开始）
/// * `config` - 排版配置（字体大小、行距、页面尺寸等）
///
/// # 返回值
/// * `Ok(Vec<PageContent>)` - 分页后的页面列表
/// * `Err(ParserError)` - 提取失败（章节不存在等）
ApiResultVecPageContent getTxtChapterContent({
  required String filePath,
  required int chapterIndex,
  required TypesetConfig config,
}) => RustLib.instance.api.crateApiCoreGetTxtChapterContent(
  filePath: filePath,
  chapterIndex: chapterIndex,
  config: config,
);

/// 获取支持的文件格式列表
///
/// 返回当前支持的文件格式扩展名列表（如 "txt", "epub", "pdf"）。
List<String> getSupportedFormats() =>
    RustLib.instance.api.crateApiCoreGetSupportedFormats();

/// 检查是否支持指定格式
///
/// # 参数
/// * `format` - 文件格式扩展名（如 "txt", "epub"）
///
/// # 返回值
/// `true` 如果格式受支持，`false` 否则
bool supportsFormat({required String format}) =>
    RustLib.instance.api.crateApiCoreSupportsFormat(format: format);

/// 对文本进行排版处理
///
/// 根据配置对文本进行智能排版，包括中文/英文换行、首行缩进等。
///
/// # 参数
/// * `content` - 原始文本内容
/// * `language` - 语言类型（"zh", "en", "auto"）
/// * `config` - 排版配置（字体大小、行距、页面尺寸等）
///
/// # 返回值
/// * `Ok(String)` - 排版后的文本
/// * `Err(ParserError)` - 排版失败
ApiResultString typesetText({
  required String content,
  required String language,
  required TypesetConfig config,
}) => RustLib.instance.api.crateApiCoreTypesetText(
  content: content,
  language: language,
  config: config,
);

/// 获取文件大小
///
/// # 参数
/// * `file_path` - 文件的完整路径
///
/// # 返回值
/// * `Ok(i64)` - 文件大小（字节）
/// * `Err(ParserError)` - 获取失败（文件不存在等）
ApiResultI64 getFileSize({required String filePath}) =>
    RustLib.instance.api.crateApiCoreGetFileSize(filePath: filePath);

/// 读取文件块
///
/// 支持大文件分块读取，避免内存溢出。
///
/// # 参数
/// * `file_path` - 文件的完整路径
/// * `start_pos` - 起始位置（字节偏移）
/// * `chunk_size` - 读取大小（字节）
///
/// # 返回值
/// * `Ok(String)` - 文件块内容
/// * `Err(ParserError)` - 读取失败
ApiResultString readFileChunk({
  required String filePath,
  required PlatformInt64 startPos,
  required PlatformInt64 chunkSize,
}) => RustLib.instance.api.crateApiCoreReadFileChunk(
  filePath: filePath,
  startPos: startPos,
  chunkSize: chunkSize,
);

/// 创建流式分页器
///
/// 返回一个 `PageStreamer` 实例，支持按需获取页面内容，
/// 避免一次性加载全部内容到内存，适用于大文件阅读场景。
///
/// # 参数
///
/// * `content` - 原始文本内容
/// * `config` - 排版配置（页面尺寸、字体大小等）
///
/// # 返回值
///
/// 返回配置好的 `PageStreamer` 实例
PageStreamer createPageStreamer({
  required String content,
  required TypesetConfig config,
}) => RustLib.instance.api.crateApiCoreCreatePageStreamer(
  content: content,
  config: config,
);

/// 对全部内容进行分页处理
///
/// 将完整文本内容按照配置分页，返回所有页面列表。
/// 适用于需要预加载全部页面的场景（如小文件或离线缓存）。
///
/// # 参数
///
/// * `content` - 原始文本内容
/// * `chapter_id` - 章节 ID（用于标识页面所属章节）
/// * `config` - 排版配置（页面尺寸、字体大小等）
///
/// # 返回值
///
/// 返回分页后的页面列表
List<PageContent> paginateAllContent({
  required String content,
  required int chapterId,
  required TypesetConfig config,
}) => RustLib.instance.api.crateApiCorePaginateAllContent(
  content: content,
  chapterId: chapterId,
  config: config,
);

String testConnection() => RustLib.instance.api.crateApiCoreTestConnection();

/// 设置允许访问的基础目录
///
/// 设置后，所有文件操作都会被限制在该目录内，防止路径遍历攻击。
/// 使用 RwLock 实现，支持多次调用更新目录。
///
/// # 参数
/// * `base_dir` - 基础目录的完整路径
///
/// # 返回值
/// * `Ok(())` - 设置成功
/// * `Err(ParserError)` - 设置失败（目录不存在等）
ApiResult setAllowedBaseDir({required String baseDir}) =>
    RustLib.instance.api.crateApiCoreSetAllowedBaseDir(baseDir: baseDir);

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < () >>>
abstract class ApiResult implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < BookMetadata >>>
abstract class ApiResultBookMetadata implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < ParseResult >>>
abstract class ApiResultParseResult implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < String >>>
abstract class ApiResultString implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < Vec < PageContent > >>>
abstract class ApiResultVecPageContent implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < i64 >>>
abstract class ApiResultI64 implements RustOpaqueInterface {}
