// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../domain/error.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 提取书籍封面
///
/// 自动检测文件类型并提取封面图片，保存到指定目录。
Future<String> extractBookCover({
  required String filePath,
  required String outputDir,
}) => RustLib.instance.api.crateApiCoverExtractBookCover(
  filePath: filePath,
  outputDir: outputDir,
);

/// 提取书籍封面并保存路径到数据库
///
/// 一次调用完成：提取封面 + 更新 DB 中的 cover_path。
/// 替代 Dart 侧 extractBookCover + updateBook 的两步调用。
Future<String> extractAndSaveCover({
  required String bookId,
  required String filePath,
  required String outputDir,
}) => RustLib.instance.api.crateApiCoverExtractAndSaveCover(
  bookId: bookId,
  filePath: filePath,
  outputDir: outputDir,
);

/// 检查是否支持封面提取
bool supportsCoverExtraction({required String filePath}) => RustLib.instance.api
    .crateApiCoverSupportsCoverExtraction(filePath: filePath);
