// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../domain/error.dart';
import '../domain/types/metadata.dart';
import '../domain/types/rich_text.dart';
import '../domain/types/typeset.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EpubImageInfo`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `eq`, `fmt`, `fmt`

/// 快速获取 EPUB 元数据
///
/// 无需完整解析 EPUB 文件即可获取书名、作者、封面、目录等信息。
/// 适用于文件列表预览、导入前预览等场景。
///
/// # 参数
/// * `file_path` - EPUB 文件路径
///
/// # 返回值
/// * `Ok(EpubMetadata)` - 元数据（包含标题、作者、封面、目录、阅读顺序）
/// * `Err(AppError)` - 解析失败（文件不存在、格式错误等）
Future<EpubMetadata> getEpubMetadata({required String filePath}) =>
    RustLib.instance.api.crateApiEpubGetEpubMetadata(filePath: filePath);

/// 获取 EPUB 章节富文本内容（带排版）
///
/// 解析 EPUB 章节为富文本格式，并应用排版配置（首行缩进、标点优化等）。
///
/// # 参数
/// * `file_path` - EPUB 文件路径
/// * `chapter_index` - 章节索引
/// * `config` - 排版配置
///
/// # 返回值
/// * `Ok(Vec<RichParagraph>)` - 排版后的富文本段落
/// * `Err(AppError)` - 解析失败
Future<List<RichParagraph>> getEpubChapterRichContent({
  required String filePath,
  required int chapterIndex,
  required TypesetConfig config,
}) => RustLib.instance.api.crateApiEpubGetEpubChapterRichContent(
  filePath: filePath,
  chapterIndex: chapterIndex,
  config: config,
);

/// 图片格式
enum ImageFormat {
  /// JPEG 格式
  jpeg,

  /// PNG 格式
  png,

  /// GIF 格式
  gif,

  /// WebP 格式
  webp,

  /// BMP 格式
  bmp,

  /// SVG 格式
  svg,

  /// 未知格式
  unknown;

  /// 获取图片格式对应的标准文件扩展名（不含点号）
  Future<String> extension_() =>
      RustLib.instance.api.crateApiEpubImageFormatExtension(that: this);

  /// 根据文件扩展名识别图片格式
  ///
  /// # 参数
  /// - `ext`: 文件扩展名（可含前导点号，如 `.jpg` 或 `jpg`）
  ///
  /// # 返回值
  /// 返回匹配的 ImageFormat，无法识别时返回 `Unknown`
  static Future<ImageFormat> fromExtension({required String ext}) =>
      RustLib.instance.api.crateApiEpubImageFormatFromExtension(ext: ext);

  /// 获取图片格式对应的 MIME 类型字符串
  Future<String> mimeType() =>
      RustLib.instance.api.crateApiEpubImageFormatMimeType(that: this);
}
