// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../ffi/types.dart';
import '../frb_generated.dart';
import 'core.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 快速获取 EPUB 元数据
///
/// 无需完整解析 EPUB 文件即可获取书名、作者、封面、目录等信息。
/// 适用于文件列表预览、导入前预览等场景。
///
/// # 参数
/// * `file_path` - EPUB 文件路径
///
/// # 返回值
/// * `Ok(EpubMetadata)` - 元数据（包含标题、作者、封面、目录、阅读顺序）
/// * `Err(ParserError)` - 解析失败（文件不存在、格式错误等）
ApiResultEpubMetadata getEpubMetadata({required String filePath}) =>
    RustLib.instance.api.crateApiEpubGetEpubMetadata(filePath: filePath);

/// 解析 EPUB 章节（富文本）
///
/// 解析 EPUB 章节内容为富文本格式，保留 HTML 标签用于显示。
///
/// **注意**: 这是一个 EPUB 特有的功能，用于需要保留 HTML 格式的场景。
/// 普通文本解析请使用 `core::extract_chapter`。
ApiResultRichChapterContent parseEpubChapterRich({
  required String filePath,
  required int chapterIndex,
}) => RustLib.instance.api.crateApiEpubParseEpubChapterRich(
  filePath: filePath,
  chapterIndex: chapterIndex,
);

/// 获取 EPUB 章节内容（使用排版配置）
///
/// **注意**: 这是一个 EPUB 特有的功能。
/// 通用章节内容获取请使用 `core::extract_chapter`。
ApiResultVecPageContent getEpubChapterContent({
  required String filePath,
  required int chapterId,
  required TypesetConfig config,
}) => RustLib.instance.api.crateApiEpubGetEpubChapterContent(
  filePath: filePath,
  chapterId: chapterId,
  config: config,
);

/// 获取 EPUB 章节富文本内容（带排版）
///
/// 解析 EPUB 章节为富文本格式，并应用排版配置（首行缩进、标点优化等）。
///
/// # 参数
/// * `file_path` - EPUB 文件路径
/// * `chapter_id` - 章节 ID
/// * `config` - 排版配置
///
/// # 返回值
/// * `Ok(Vec<RichParagraph>)` - 排版后的富文本段落
/// * `Err(ParserError)` - 解析失败
ApiResultVecRichParagraph getEpubChapterRichContent({
  required String filePath,
  required int chapterId,
  required TypesetConfig config,
}) => RustLib.instance.api.crateApiEpubGetEpubChapterRichContent(
  filePath: filePath,
  chapterId: chapterId,
  config: config,
);

/// 将 EPUB 章节富文本分页
///
/// 将富文本段落分割为适合阅读的页面。
///
/// # 参数
/// * `paragraphs` - 富文本段落列表
/// * `chapter_index` - 章节索引
/// * `config` - 排版配置
///
/// # 返回值
/// * `Vec<PageContent>` - 分页后的页面列表
List<PageContent> paginateEpubRichContent({
  required List<RichParagraph> paragraphs,
  required int chapterIndex,
  required TypesetConfig config,
}) => RustLib.instance.api.crateApiEpubPaginateEpubRichContent(
  paragraphs: paragraphs,
  chapterIndex: chapterIndex,
  config: config,
);

/// 检查文件是否为 EPUB 格式
bool isEpubFile({required String filePath}) =>
    RustLib.instance.api.crateApiEpubIsEpubFile(filePath: filePath);

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < EpubMetadata >>>
abstract class ApiResultEpubMetadata implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < RichChapterContent >>>
abstract class ApiResultRichChapterContent implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < Vec < RichParagraph > >>>
abstract class ApiResultVecRichParagraph implements RustOpaqueInterface {}
