// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'core.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_parser_for_file`, `get_parser`

ApiResult initIncrementalParser() =>
    RustLib.instance.api.crateApiIncrementalInitIncrementalParser();

/// 增量解析书籍
///
/// 如果文件已缓存且未变更，直接返回缓存结果；
/// 否则重新解析并更新缓存。
ApiResultLocalBookInfo parseLocalBookIncremental({required String filePath}) =>
    RustLib.instance.api.crateApiIncrementalParseLocalBookIncremental(
      filePath: filePath,
    );

/// 清除增量解析缓存
ApiResult clearIncrementalParserCache() =>
    RustLib.instance.api.crateApiIncrementalClearIncrementalParserCache();

/// 获取增量解析缓存统计信息
ApiResultCacheStats getIncrementalParserStats() =>
    RustLib.instance.api.crateApiIncrementalGetIncrementalParserStats();

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < CacheStats >>>
abstract class ApiResultCacheStats implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < LocalBookInfo >>>
abstract class ApiResultLocalBookInfo implements RustOpaqueInterface {}
