// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'core.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_search_engine`

/// 初始化搜索引擎（需要数据库路径）
Future<ApiResult> initSearchEngine({required String dbPath}) =>
    RustLib.instance.api.crateApiSearchInitSearchEngine(dbPath: dbPath);

/// 索引章节内容
///
/// 将指定章节的文本内容添加到搜索索引中。
///
/// # 参数
///
/// * `book_id` - 书籍唯一标识
/// * `chapter_id` - 章节ID
/// * `chapter_title` - 章节标题
/// * `content` - 章节文本内容
Future<ApiResult> indexChapterContent({
  required String bookId,
  required int chapterId,
  required String chapterTitle,
  required String content,
}) => RustLib.instance.api.crateApiSearchIndexChapterContent(
  bookId: bookId,
  chapterId: chapterId,
  chapterTitle: chapterTitle,
  content: content,
);

/// 在书籍中搜索
///
/// 在指定书籍的索引中搜索关键词，返回匹配的搜索结果。
///
/// # 参数
///
/// * `book_id` - 书籍唯一标识
/// * `query` - 搜索关键词
/// * `limit` - 返回结果数量限制
ApiResultVecSearchResult searchInBook({
  required String bookId,
  required String query,
  required int limit,
}) => RustLib.instance.api.crateApiSearchSearchInBook(
  bookId: bookId,
  query: query,
  limit: limit,
);

/// 删除指定书籍的所有搜索索引
///
/// 当书籍被删除时调用，防止搜索索引孤立。
///
/// # 参数
///
/// * `book_id` - 书籍唯一标识
ApiResult deleteBookSearchIndex({required String bookId}) =>
    RustLib.instance.api.crateApiSearchDeleteBookSearchIndex(bookId: bookId);

/// 清除所有搜索索引
Future<ApiResult> clearAllSearchIndex() =>
    RustLib.instance.api.crateApiSearchClearAllSearchIndex();

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < Vec < SearchResult > >>>
abstract class ApiResultVecSearchResult implements RustOpaqueInterface {}
