// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../domain/error.dart';
import '../domain/types/pagination.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_search_engine`

/// 初始化搜索引擎
Future<void> initSearchEngine() =>
    RustLib.instance.api.crateApiSearchInitSearchEngine();

/// 索引章节内容
Future<void> indexChapter({
  required String bookId,
  required String chapterId,
  required int chapterIndex,
  required String chapterTitle,
  required String content,
}) => RustLib.instance.api.crateApiSearchIndexChapter(
  bookId: bookId,
  chapterId: chapterId,
  chapterIndex: chapterIndex,
  chapterTitle: chapterTitle,
  content: content,
);

/// 在书籍中搜索
Future<List<SearchResult>> search({
  required String bookId,
  required String query,
  required int limit,
}) => RustLib.instance.api.crateApiSearchSearch(
  bookId: bookId,
  query: query,
  limit: limit,
);

/// 搜索所有书籍内容
Future<List<SearchResult>> searchAllBooks({
  required String query,
  required int limit,
  required int offset,
}) => RustLib.instance.api.crateApiSearchSearchAllBooks(
  query: query,
  limit: limit,
  offset: offset,
);

/// 清除所有搜索索引
Future<void> clearAll() => RustLib.instance.api.crateApiSearchClearAll();

/// 删除某本书的搜索索引
Future<void> deleteByBook({required String bookId}) =>
    RustLib.instance.api.crateApiSearchDeleteByBook(bookId: bookId);
