// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../domain/error.dart';
import '../domain/types.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_search_engine`

/// 初始化搜索引擎
Future<void> initSearchEngine() =>
    RustLib.instance.api.crateApiSearchInitSearchEngine();

/// 索引章节内容
Future<void> indexChapterContent({
  required String bookId,
  required int chapterId,
  required String chapterTitle,
  required String content,
}) => RustLib.instance.api.crateApiSearchIndexChapterContent(
  bookId: bookId,
  chapterId: chapterId,
  chapterTitle: chapterTitle,
  content: content,
);

/// 在书籍中搜索
Future<List<SearchResult>> searchInBook({
  required String bookId,
  required String query,
  required int limit,
}) => RustLib.instance.api.crateApiSearchSearchInBook(
  bookId: bookId,
  query: query,
  limit: limit,
);

/// 清除所有搜索索引
Future<void> clearAllSearchIndex() =>
    RustLib.instance.api.crateApiSearchClearAllSearchIndex();

/// 删除某本书的搜索索引
Future<void> deleteBookSearchIndex({required String bookId}) =>
    RustLib.instance.api.crateApiSearchDeleteBookSearchIndex(bookId: bookId);
