// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../ffi/error.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 验证文件路径是否安全
///
/// 确保文件路径在允许的基目录内，防止路径遍历攻击。
///
/// # 参数
///
/// * `file_path` - 待验证的文件路径
/// * `allowed_base` - 允许的基目录路径（字符串）
///
/// # 返回值
///
/// * `Ok(String)` - 验证通过的规范化路径
/// * `Err(ParserError)` - 路径不安全或无效
Future<String> validatePathSecurely({
  required String filePath,
  required String allowedBase,
}) => RustLib.instance.api.crateApiSecurityValidatePathSecurely(
  filePath: filePath,
  allowedBase: allowedBase,
);

/// 验证文件路径并返回规范化的路径
///
/// # 注意
///
/// 此函数使用严格的路径规范化，确保路径安全性。
Future<String> validateFilePath({required String filePath}) =>
    RustLib.instance.api.crateApiSecurityValidateFilePath(filePath: filePath);
