// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../ffi/error.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `validate_path_securely`

/// 验证文件路径并返回规范化的路径
///
/// # 安全性
///
/// 此函数直接调用 `canonicalize()` 避免 TOCTOU 竞态条件，
/// 不分离 `exists()` 检查，确保路径验证的原子性。
///
/// # 注意
///
/// 此函数使用严格的路径规范化，确保路径安全性。
Future<String> validateFilePath({required String filePath}) =>
    RustLib.instance.api.crateApiSecurityValidateFilePath(filePath: filePath);
