// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../domain/error.dart';
import '../frb_generated.dart';
import '../storage/models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> initStorage({required String dataDir}) =>
    RustLib.instance.api.crateApiStorageInitStorage(dataDir: dataDir);

Future<List<Book>> getAllBooks() =>
    RustLib.instance.api.crateApiStorageGetAllBooks();

Future<void> saveBook({required Book book}) =>
    RustLib.instance.api.crateApiStorageSaveBook(book: book);

Future<void> deleteBook({required String bookId}) =>
    RustLib.instance.api.crateApiStorageDeleteBook(bookId: bookId);

Future<List<Book>> searchBooks({required String keyword}) =>
    RustLib.instance.api.crateApiStorageSearchBooks(keyword: keyword);

Future<Book?> getBook({required String bookId}) =>
    RustLib.instance.api.crateApiStorageGetBook(bookId: bookId);

Future<List<Book>> getBooksByStatus({required BookStatus status}) =>
    RustLib.instance.api.crateApiStorageGetBooksByStatus(status: status);

Future<List<Book>> getPinnedBooks() =>
    RustLib.instance.api.crateApiStorageGetPinnedBooks();

Future<List<Book>> getRecentlyReadBooks({required BigInt limit}) =>
    RustLib.instance.api.crateApiStorageGetRecentlyReadBooks(limit: limit);

Future<List<Book>> getBooksPaginated({
  required int limit,
  required int offset,
  String? sortBy,
  String? sortOrder,
}) => RustLib.instance.api.crateApiStorageGetBooksPaginated(
  limit: limit,
  offset: offset,
  sortBy: sortBy,
  sortOrder: sortOrder,
);

Future<PlatformInt64> getBookCount() =>
    RustLib.instance.api.crateApiStorageGetBookCount();

Future<ReadingProgress?> getReadingProgress({required String bookId}) =>
    RustLib.instance.api.crateApiStorageGetReadingProgress(bookId: bookId);

Future<void> saveReadingProgress({required ReadingProgress progress}) =>
    RustLib.instance.api.crateApiStorageSaveReadingProgress(progress: progress);

Future<void> clearReadingProgress({required String bookId}) =>
    RustLib.instance.api.crateApiStorageClearReadingProgress(bookId: bookId);

Future<List<Bookmark>> getBookmarks({required String bookId}) =>
    RustLib.instance.api.crateApiStorageGetBookmarks(bookId: bookId);

Future<void> createBookmark({required Bookmark bookmark}) =>
    RustLib.instance.api.crateApiStorageCreateBookmark(bookmark: bookmark);

Future<void> deleteBookmark({required String bookmarkId}) =>
    RustLib.instance.api.crateApiStorageDeleteBookmark(bookmarkId: bookmarkId);

Future<Bookmark?> getBookmark({required String bookmarkId}) =>
    RustLib.instance.api.crateApiStorageGetBookmark(bookmarkId: bookmarkId);

Future<void> deleteBookmarksByBook({required String bookId}) =>
    RustLib.instance.api.crateApiStorageDeleteBookmarksByBook(bookId: bookId);

Future<void> importBookmarks({required List<Bookmark> bookmarks}) =>
    RustLib.instance.api.crateApiStorageImportBookmarks(bookmarks: bookmarks);

Future<List<Bookmark>> syncBookmarks({
  required List<Bookmark> localBookmarks,
  required List<Bookmark> remoteBookmarks,
}) => RustLib.instance.api.crateApiStorageSyncBookmarks(
  localBookmarks: localBookmarks,
  remoteBookmarks: remoteBookmarks,
);

Future<int> getBookmarkStats({required String bookId}) =>
    RustLib.instance.api.crateApiStorageGetBookmarkStats(bookId: bookId);

Future<void> recordReadingSession({required ReadingSession session}) =>
    RustLib.instance.api.crateApiStorageRecordReadingSession(session: session);

Future<List<ReadingSession>> getReadingSessions({
  required String bookId,
  required BigInt limit,
}) => RustLib.instance.api.crateApiStorageGetReadingSessions(
  bookId: bookId,
  limit: limit,
);

Future<List<ReadingSession>> getSessionsByDateRange({
  required String bookId,
  required String startDate,
  required String endDate,
}) => RustLib.instance.api.crateApiStorageGetSessionsByDateRange(
  bookId: bookId,
  startDate: startDate,
  endDate: endDate,
);

Future<List<ReadingSession>> getRecentSessions({required BigInt limit}) =>
    RustLib.instance.api.crateApiStorageGetRecentSessions(limit: limit);

Future<void> deleteSessionsByBook({required String bookId}) =>
    RustLib.instance.api.crateApiStorageDeleteSessionsByBook(bookId: bookId);

Future<List<ReadingStats>> getTodayReadingStats() =>
    RustLib.instance.api.crateApiStorageGetTodayReadingStats();

Future<List<ReadingStats>> getReadingStatsRange({
  required String startDate,
  required String endDate,
}) => RustLib.instance.api.crateApiStorageGetReadingStatsRange(
  startDate: startDate,
  endDate: endDate,
);

Future<GlobalStats> getGlobalReadingStats() =>
    RustLib.instance.api.crateApiStorageGetGlobalReadingStats();

Future<void> updateDailyStats({required ReadingStats stats}) =>
    RustLib.instance.api.crateApiStorageUpdateDailyStats(stats: stats);

Future<List<Chapter>> getChaptersByBook({required String bookId}) =>
    RustLib.instance.api.crateApiStorageGetChaptersByBook(bookId: bookId);

Future<void> saveChapters({
  required String bookId,
  required List<Chapter> chapters,
}) => RustLib.instance.api.crateApiStorageSaveChapters(
  bookId: bookId,
  chapters: chapters,
);

Future<void> deleteChaptersByBook({required String bookId}) =>
    RustLib.instance.api.crateApiStorageDeleteChaptersByBook(bookId: bookId);

Future<Chapter?> getChapterByIndex({
  required String bookId,
  required int chapterIndex,
}) => RustLib.instance.api.crateApiStorageGetChapterByIndex(
  bookId: bookId,
  chapterIndex: chapterIndex,
);

Future<List<BookCategory>> getAllCategories() =>
    RustLib.instance.api.crateApiStorageGetAllCategories();

Future<void> saveCategory({required BookCategory category}) =>
    RustLib.instance.api.crateApiStorageSaveCategory(category: category);

Future<void> deleteCategory({required String categoryId}) =>
    RustLib.instance.api.crateApiStorageDeleteCategory(categoryId: categoryId);

Future<BookCategory?> getCategory({required String categoryId}) =>
    RustLib.instance.api.crateApiStorageGetCategory(categoryId: categoryId);

Future<List<BookCategory>> getCategoriesForBook({required String bookId}) =>
    RustLib.instance.api.crateApiStorageGetCategoriesForBook(bookId: bookId);

Future<void> assignCategoryToBook({
  required String bookId,
  required String categoryId,
}) => RustLib.instance.api.crateApiStorageAssignCategoryToBook(
  bookId: bookId,
  categoryId: categoryId,
);

Future<void> removeCategoryFromBook({
  required String bookId,
  required String categoryId,
}) => RustLib.instance.api.crateApiStorageRemoveCategoryFromBook(
  bookId: bookId,
  categoryId: categoryId,
);

Future<void> setCategoriesForBook({
  required String bookId,
  required List<String> categoryIds,
}) => RustLib.instance.api.crateApiStorageSetCategoriesForBook(
  bookId: bookId,
  categoryIds: categoryIds,
);

Future<void> clearCategoriesForBook({required String bookId}) =>
    RustLib.instance.api.crateApiStorageClearCategoriesForBook(bookId: bookId);

Future<void> saveLayoutCache({
  required LayoutCache cache,
  required LayoutCacheKey key,
}) =>
    RustLib.instance.api.crateApiStorageSaveLayoutCache(cache: cache, key: key);

Future<LayoutCache?> getLayoutCache({
  required String bookId,
  required int chapterIndex,
  required String configHash,
}) => RustLib.instance.api.crateApiStorageGetLayoutCache(
  bookId: bookId,
  chapterIndex: chapterIndex,
  configHash: configHash,
);

Future<void> clearLayoutCache({required String bookId}) =>
    RustLib.instance.api.crateApiStorageClearLayoutCache(bookId: bookId);

Future<BigInt> cleanupExpiredLayoutCache({required PlatformInt64 maxAgeDays}) =>
    RustLib.instance.api.crateApiStorageCleanupExpiredLayoutCache(
      maxAgeDays: maxAgeDays,
    );

Future<void> updateBookStatus({
  required String bookId,
  required BookStatus status,
}) => RustLib.instance.api.crateApiStorageUpdateBookStatus(
  bookId: bookId,
  status: status,
);

Future<void> updateBookPin({required String bookId, required bool isPinned}) =>
    RustLib.instance.api.crateApiStorageUpdateBookPin(
      bookId: bookId,
      isPinned: isPinned,
    );

Future<Note> createNote({required Note note}) =>
    RustLib.instance.api.crateApiStorageCreateNote(note: note);

Future<void> updateNote({required Note note}) =>
    RustLib.instance.api.crateApiStorageUpdateNote(note: note);

Future<List<Note>> getNotes({required String bookId, NoteType? noteType}) =>
    RustLib.instance.api.crateApiStorageGetNotes(
      bookId: bookId,
      noteType: noteType,
    );

Future<void> deleteNote({required String noteId}) =>
    RustLib.instance.api.crateApiStorageDeleteNote(noteId: noteId);

Future<void> deleteNotesByBook({required String bookId}) =>
    RustLib.instance.api.crateApiStorageDeleteNotesByBook(bookId: bookId);

Future<NoteStats> getNoteStats({required String bookId}) =>
    RustLib.instance.api.crateApiStorageGetNoteStats(bookId: bookId);

Future<void> exportDatabase({required String destPath}) =>
    RustLib.instance.api.crateApiStorageExportDatabase(destPath: destPath);

Future<void> restoreDatabase({required String backupPath}) =>
    RustLib.instance.api.crateApiStorageRestoreDatabase(backupPath: backupPath);
