// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../storage/models.dart';
import 'core.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 获取所有书籍
Future<ApiResultVecDbBookRecord> getAllBooks() =>
    RustLib.instance.api.crateApiStorageGetAllBooks();

/// 保存书籍
Future<ApiResult> saveBook({required DbBookRecord book}) =>
    RustLib.instance.api.crateApiStorageSaveBook(book: book);

/// 删除书籍
Future<ApiResult> deleteBook({required String bookId}) =>
    RustLib.instance.api.crateApiStorageDeleteBook(bookId: bookId);

/// 搜索书籍
Future<ApiResultVecDbBookRecord> searchBooks({required String keyword}) =>
    RustLib.instance.api.crateApiStorageSearchBooks(keyword: keyword);

/// 获取章节列表
Future<ApiResultVecDbChapter> getChaptersByBook({required String bookId}) =>
    RustLib.instance.api.crateApiStorageGetChaptersByBook(bookId: bookId);

/// 保存章节列表
Future<ApiResult> saveChapters({
  required String bookId,
  required List<DbChapter> chapters,
}) => RustLib.instance.api.crateApiStorageSaveChapters(
  bookId: bookId,
  chapters: chapters,
);

/// 删除书籍的所有章节
Future<ApiResult> deleteChaptersByBook({required String bookId}) =>
    RustLib.instance.api.crateApiStorageDeleteChaptersByBook(bookId: bookId);

/// 获取阅读进度
Future<ApiResultOptionDbReadingProgress> getReadingProgress({
  required String bookId,
}) => RustLib.instance.api.crateApiStorageGetReadingProgress(bookId: bookId);

/// 保存阅读进度
Future<ApiResult> saveReadingProgress({
  required String bookId,
  required int chapterIndex,
  required PlatformInt64 charOffset,
  required int pageIndex,
  required int totalPages,
  required PlatformInt64 readingTimeSeconds,
}) => RustLib.instance.api.crateApiStorageSaveReadingProgress(
  bookId: bookId,
  chapterIndex: chapterIndex,
  charOffset: charOffset,
  pageIndex: pageIndex,
  totalPages: totalPages,
  readingTimeSeconds: readingTimeSeconds,
);

/// 清除阅读进度
Future<ApiResult> clearReadingProgress({required String bookId}) =>
    RustLib.instance.api.crateApiStorageClearReadingProgress(bookId: bookId);

/// 获取书签列表
Future<ApiResultVecDbBookmark> getBookmarks({required String bookId}) =>
    RustLib.instance.api.crateApiStorageGetBookmarks(bookId: bookId);

/// 创建书签
Future<ApiResultDbBookmark> createBookmark({
  required String bookId,
  required int chapterIndex,
  required PlatformInt64 charOffset,
  String? title,
}) => RustLib.instance.api.crateApiStorageCreateBookmark(
  bookId: bookId,
  chapterIndex: chapterIndex,
  charOffset: charOffset,
  title: title,
);

/// 删除书签
Future<ApiResult> deleteBookmark({required String bookmarkId}) =>
    RustLib.instance.api.crateApiStorageDeleteBookmark(bookmarkId: bookmarkId);

/// 保存书签（更新）
Future<ApiResult> saveBookmark({required DbBookmark bookmark}) =>
    RustLib.instance.api.crateApiStorageSaveBookmark(bookmark: bookmark);

/// 记录阅读会话
Future<ApiResult> recordReadingSession({
  required String bookId,
  required int chapterIndex,
  required PlatformInt64 startOffset,
  required PlatformInt64 endOffset,
  required PlatformInt64 durationSeconds,
  required PlatformInt64 charactersRead,
}) => RustLib.instance.api.crateApiStorageRecordReadingSession(
  bookId: bookId,
  chapterIndex: chapterIndex,
  startOffset: startOffset,
  endOffset: endOffset,
  durationSeconds: durationSeconds,
  charactersRead: charactersRead,
);

/// 获取今日统计
Future<ApiResultDbDailyReadingStats> getTodayReadingStats() =>
    RustLib.instance.api.crateApiStorageGetTodayReadingStats();

/// 获取日期范围统计
Future<ApiResultVecDbDailyReadingStats> getReadingStatsRange({
  required String startDate,
  required String endDate,
}) => RustLib.instance.api.crateApiStorageGetReadingStatsRange(
  startDate: startDate,
  endDate: endDate,
);

/// 获取全局统计
Future<ApiResultDbGlobalStats> getGlobalReadingStats() =>
    RustLib.instance.api.crateApiStorageGetGlobalReadingStats();

/// 获取所有分类
Future<ApiResultVecDbBookCategory> getAllCategories() =>
    RustLib.instance.api.crateApiStorageGetAllCategories();

/// 保存分类
Future<ApiResult> saveCategory({required DbBookCategory category}) =>
    RustLib.instance.api.crateApiStorageSaveCategory(category: category);

/// 删除分类
Future<ApiResult> deleteCategory({required String categoryId}) =>
    RustLib.instance.api.crateApiStorageDeleteCategory(categoryId: categoryId);

/// 获取书籍的分类
Future<ApiResultVecDbBookCategory> getCategoriesForBook({
  required String bookId,
}) => RustLib.instance.api.crateApiStorageGetCategoriesForBook(bookId: bookId);

/// 分配分类到书籍
Future<ApiResult> assignCategoryToBook({
  required String bookId,
  required String categoryId,
}) => RustLib.instance.api.crateApiStorageAssignCategoryToBook(
  bookId: bookId,
  categoryId: categoryId,
);

/// 移除书籍的分类
Future<ApiResult> removeCategoryFromBook({
  required String bookId,
  required String categoryId,
}) => RustLib.instance.api.crateApiStorageRemoveCategoryFromBook(
  bookId: bookId,
  categoryId: categoryId,
);

/// 设置书籍的分类列表
Future<ApiResult> setCategoriesForBook({
  required String bookId,
  required List<String> categoryIds,
}) => RustLib.instance.api.crateApiStorageSetCategoriesForBook(
  bookId: bookId,
  categoryIds: categoryIds,
);

/// 保存排版缓存
Future<ApiResult> saveLayoutCache({
  required String bookId,
  required int chapterIndex,
  required String configHash,
  required List<(PlatformInt64, PlatformInt64)> pageOffsets,
  required int totalPages,
}) => RustLib.instance.api.crateApiStorageSaveLayoutCache(
  bookId: bookId,
  chapterIndex: chapterIndex,
  configHash: configHash,
  pageOffsets: pageOffsets,
  totalPages: totalPages,
);

/// 获取排版缓存
Future<ApiResultOptionDbLayoutCache> getLayoutCache({
  required String bookId,
  required int chapterIndex,
  required String configHash,
}) => RustLib.instance.api.crateApiStorageGetLayoutCache(
  bookId: bookId,
  chapterIndex: chapterIndex,
  configHash: configHash,
);

/// 清除书籍排版缓存
Future<ApiResult> clearLayoutCache({required String bookId}) =>
    RustLib.instance.api.crateApiStorageClearLayoutCache(bookId: bookId);

/// 清理过期排版缓存
Future<ApiResultUsize> cleanupExpiredLayoutCache({
  required PlatformInt64 maxAgeDays,
}) => RustLib.instance.api.crateApiStorageCleanupExpiredLayoutCache(
  maxAgeDays: maxAgeDays,
);

/// 根据 ID 获取书籍
Future<ApiResultOptionDbBookRecord> getBook({required String bookId}) =>
    RustLib.instance.api.crateApiStorageGetBook(bookId: bookId);

/// 按状态筛选书籍
Future<ApiResultVecDbBookRecord> getBooksByStatus({
  required DbBookStatus status,
}) => RustLib.instance.api.crateApiStorageGetBooksByStatus(status: status);

/// 获取置顶书籍
Future<ApiResultVecDbBookRecord> getPinnedBooks() =>
    RustLib.instance.api.crateApiStorageGetPinnedBooks();

/// 获取最近阅读的书籍
Future<ApiResultVecDbBookRecord> getRecentlyReadBooks({
  required BigInt limit,
}) => RustLib.instance.api.crateApiStorageGetRecentlyReadBooks(limit: limit);

/// 更新完整阅读进度对象
Future<ApiResult> updateReadingProgress({
  required DbReadingProgress progress,
}) => RustLib.instance.api.crateApiStorageUpdateReadingProgress(
  progress: progress,
);

/// 部分更新阅读进度（自动合并已有字段）
Future<ApiResult> updateReadingProgressPartial({
  required String bookId,
  required int chapterIndex,
  required PlatformInt64 charOffset,
  required int pageIndex,
  required int totalPages,
  required PlatformInt64 readingTimeSeconds,
}) => RustLib.instance.api.crateApiStorageUpdateReadingProgressPartial(
  bookId: bookId,
  chapterIndex: chapterIndex,
  charOffset: charOffset,
  pageIndex: pageIndex,
  totalPages: totalPages,
  readingTimeSeconds: readingTimeSeconds,
);

/// 获取单个书签详情
Future<ApiResultOptionDbBookmark> getBookmark({required String bookmarkId}) =>
    RustLib.instance.api.crateApiStorageGetBookmark(bookmarkId: bookmarkId);

/// 更新书签标题
Future<ApiResultDbBookmark> updateBookmark({
  required String bookmarkId,
  required String title,
}) => RustLib.instance.api.crateApiStorageUpdateBookmark(
  bookmarkId: bookmarkId,
  title: title,
);

/// 删除书籍的所有书签
Future<ApiResult> deleteBookmarksByBook({required String bookId}) =>
    RustLib.instance.api.crateApiStorageDeleteBookmarksByBook(bookId: bookId);

/// 导入书签列表（upsert）
Future<ApiResult> importBookmarks({required List<DbBookmark> bookmarks}) =>
    RustLib.instance.api.crateApiStorageImportBookmarks(bookmarks: bookmarks);

/// 导出书籍的所有书签
Future<ApiResultVecDbBookmark> exportBookmarks({required String bookId}) =>
    RustLib.instance.api.crateApiStorageExportBookmarks(bookId: bookId);

/// 获取书籍的阅读会话列表
Future<ApiResultVecDbReadingSession> getReadingSessions({
  required String bookId,
  required BigInt limit,
}) => RustLib.instance.api.crateApiStorageGetReadingSessions(
  bookId: bookId,
  limit: limit,
);

/// 获取日期范围内的阅读会话
Future<ApiResultVecDbReadingSession> getSessionsByDateRange({
  required String bookId,
  required String startDate,
  required String endDate,
}) => RustLib.instance.api.crateApiStorageGetSessionsByDateRange(
  bookId: bookId,
  startDate: startDate,
  endDate: endDate,
);

/// 获取最近的阅读会话（跨书籍）
Future<ApiResultVecDbReadingSession> getRecentSessions({
  required BigInt limit,
}) => RustLib.instance.api.crateApiStorageGetRecentSessions(limit: limit);

/// 删除书籍的所有阅读会话
Future<ApiResult> deleteSessionsByBook({required String bookId}) =>
    RustLib.instance.api.crateApiStorageDeleteSessionsByBook(bookId: bookId);

/// 保存同步记录
Future<ApiResult> saveSyncRecord({
  required String bookId,
  required String dataType,
  required String dataId,
  required int localVersion,
  int? remoteVersion,
  required DbSyncStatus status,
}) => RustLib.instance.api.crateApiStorageSaveSyncRecord(
  bookId: bookId,
  dataType: dataType,
  dataId: dataId,
  localVersion: localVersion,
  remoteVersion: remoteVersion,
  status: status,
);

/// 获取待同步记录
Future<ApiResultVecDbSyncRecord> getPendingSyncRecords({
  required String bookId,
}) => RustLib.instance.api.crateApiStorageGetPendingSyncRecords(bookId: bookId);

/// 更新同步状态
Future<ApiResult> updateSyncStatus({
  required String recordId,
  required DbSyncStatus status,
  int? remoteVersion,
}) => RustLib.instance.api.crateApiStorageUpdateSyncStatus(
  recordId: recordId,
  status: status,
  remoteVersion: remoteVersion,
);

/// 获取同步冲突记录
Future<ApiResultVecDbSyncRecord> getSyncConflicts({required String bookId}) =>
    RustLib.instance.api.crateApiStorageGetSyncConflicts(bookId: bookId);

/// 清除同步冲突（标记为已同步）
Future<ApiResult> clearSyncConflicts({required String bookId}) =>
    RustLib.instance.api.crateApiStorageClearSyncConflicts(bookId: bookId);

/// 删除同步记录
Future<ApiResult> deleteSyncRecord({required String recordId}) =>
    RustLib.instance.api.crateApiStorageDeleteSyncRecord(recordId: recordId);

/// 获取单个分类详情
Future<ApiResultOptionDbBookCategory> getCategory({
  required String categoryId,
}) => RustLib.instance.api.crateApiStorageGetCategory(categoryId: categoryId);

/// 清除书籍的所有分类关联
Future<ApiResult> clearCategoriesForBook({required String bookId}) =>
    RustLib.instance.api.crateApiStorageClearCategoriesForBook(bookId: bookId);

/// 索引章节内容（用于全文搜索）
Future<ApiResult> indexChapterContent({
  required String bookId,
  required int chapterIndex,
  required String content,
}) => RustLib.instance.api.crateApiStorageIndexChapterContent(
  bookId: bookId,
  chapterIndex: chapterIndex,
  content: content,
);

/// 全文搜索
Future<ApiResultVecDbSearchResult> searchContent({
  required String query,
  String? bookId,
}) => RustLib.instance.api.crateApiStorageSearchContent(
  query: query,
  bookId: bookId,
);

/// 删除书籍的搜索索引
Future<ApiResult> deleteSearchIndex({required String bookId}) =>
    RustLib.instance.api.crateApiStorageDeleteSearchIndex(bookId: bookId);

/// 获取指定章节
Future<ApiResultOptionDbChapter> getChapterByIndex({
  required String bookId,
  required int chapterIndex,
}) => RustLib.instance.api.crateApiStorageGetChapterByIndex(
  bookId: bookId,
  chapterIndex: chapterIndex,
);

/// 批量保存书签（先清空再写入）
Future<ApiResult> saveBookmarksBatch({required List<DbBookmark> bookmarks}) =>
    RustLib.instance.api.crateApiStorageSaveBookmarksBatch(
      bookmarks: bookmarks,
    );

/// 同步书签（本地与远端合并，返回合并后列表）
Future<ApiResultVecDbBookmark> syncBookmarks({
  required List<DbBookmark> localBookmarks,
  required List<DbBookmark> remoteBookmarks,
}) => RustLib.instance.api.crateApiStorageSyncBookmarks(
  localBookmarks: localBookmarks,
  remoteBookmarks: remoteBookmarks,
);

/// 获取书签统计（总数、是否有高亮）
Future<ApiResultBookmarkStats> getBookmarkStats({required String bookId}) =>
    RustLib.instance.api.crateApiStorageGetBookmarkStats(bookId: bookId);

/// 清除所有同步记录
Future<ApiResult> clearAllSyncRecords() =>
    RustLib.instance.api.crateApiStorageClearAllSyncRecords();

/// 创建笔记
Future<ApiResultDbNote> createNote({
  required String bookId,
  required int chapterIndex,
  required PlatformInt64 charOffset,
  required PlatformInt64 length,
  required DbNoteType noteType,
  required String content,
  String? selectedText,
  int? highlightColor,
}) => RustLib.instance.api.crateApiStorageCreateNote(
  bookId: bookId,
  chapterIndex: chapterIndex,
  charOffset: charOffset,
  length: length,
  noteType: noteType,
  content: content,
  selectedText: selectedText,
  highlightColor: highlightColor,
);

/// 获取笔记列表
Future<ApiResultVecDbNote> getNotes({
  required String bookId,
  DbNoteType? noteType,
}) => RustLib.instance.api.crateApiStorageGetNotes(
  bookId: bookId,
  noteType: noteType,
);

/// 更新笔记
Future<ApiResultDbNote> updateNote({
  required String noteId,
  String? content,
  int? highlightColor,
}) => RustLib.instance.api.crateApiStorageUpdateNote(
  noteId: noteId,
  content: content,
  highlightColor: highlightColor,
);

/// 删除笔记
Future<ApiResult> deleteNote({required String noteId}) =>
    RustLib.instance.api.crateApiStorageDeleteNote(noteId: noteId);

/// 更新每日统计（确保 DbDailyReadingStats 生成独立 Dart 类）
Future<ApiResult> updateDailyStats({required DbDailyReadingStats stats}) =>
    RustLib.instance.api.crateApiStorageUpdateDailyStats(stats: stats);

/// 保存阅读会话（确保 DbReadingSession 生成独立 Dart 类）
Future<ApiResult> saveReadingSession({required DbReadingSession session}) =>
    RustLib.instance.api.crateApiStorageSaveReadingSession(session: session);

/// 保存同步记录（确保 DbSyncRecord 生成独立 Dart 类）
Future<ApiResult> saveSyncRecordFull({required DbSyncRecord record}) =>
    RustLib.instance.api.crateApiStorageSaveSyncRecordFull(record: record);

/// 保存排版缓存（确保 DbLayoutCache 生成独立 Dart 类）
Future<ApiResult> saveLayoutCacheFull({
  required String bookId,
  required int chapterIndex,
  required String configHash,
  required DbLayoutCache cache,
}) => RustLib.instance.api.crateApiStorageSaveLayoutCacheFull(
  bookId: bookId,
  chapterIndex: chapterIndex,
  configHash: configHash,
  cache: cache,
);

/// 接收全局统计（确保 DbGlobalStats 生成独立 Dart 类）
Future<ApiResult> receiveGlobalStats({required DbGlobalStats stats}) =>
    RustLib.instance.api.crateApiStorageReceiveGlobalStats(stats: stats);

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < BookmarkStats >>>
abstract class ApiResultBookmarkStats implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < DbBookmark >>>
abstract class ApiResultDbBookmark implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < DbDailyReadingStats >>>
abstract class ApiResultDbDailyReadingStats implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < DbGlobalStats >>>
abstract class ApiResultDbGlobalStats implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < DbNote >>>
abstract class ApiResultDbNote implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < Option < DbBookCategory > >>>
abstract class ApiResultOptionDbBookCategory implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < Option < DbBookRecord > >>>
abstract class ApiResultOptionDbBookRecord implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < Option < DbBookmark > >>>
abstract class ApiResultOptionDbBookmark implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < Option < DbChapter > >>>
abstract class ApiResultOptionDbChapter implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < Option < DbLayoutCache > >>>
abstract class ApiResultOptionDbLayoutCache implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < Option < DbReadingProgress > >>>
abstract class ApiResultOptionDbReadingProgress
    implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < Vec < DbBookCategory > >>>
abstract class ApiResultVecDbBookCategory implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < Vec < DbBookRecord > >>>
abstract class ApiResultVecDbBookRecord implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < Vec < DbBookmark > >>>
abstract class ApiResultVecDbBookmark implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < Vec < DbChapter > >>>
abstract class ApiResultVecDbChapter implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < Vec < DbDailyReadingStats > >>>
abstract class ApiResultVecDbDailyReadingStats implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < Vec < DbNote > >>>
abstract class ApiResultVecDbNote implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < Vec < DbReadingSession > >>>
abstract class ApiResultVecDbReadingSession implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < Vec < DbSearchResult > >>>
abstract class ApiResultVecDbSearchResult implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < Vec < DbSyncRecord > >>>
abstract class ApiResultVecDbSyncRecord implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiResult < usize >>>
abstract class ApiResultUsize implements RustOpaqueInterface {}
